using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Windows.Forms;
using PdfSharp.Pdf;
using PdfSharp.Pdf.IO;
using PdfiumViewer;

namespace TPL
{
    public class PdfPageItem
    {
        public string SourceFile { get; set; }
        public int PageIndex { get; set; }
        public Color GroupColor { get; set; }
        public string DisplayName { get; set; }

        public override string ToString() => DisplayName;
    }

    [System.ComponentModel.DesignerCategory("Code")]
    public class PdfEditorForm : Form
    {
        private ListBox lstPages;
        private PdfViewer pdfViewer;
        private Button btnUp, btnDown, btnRemove, btnAdd, btnSave, btnCancel, btnPlusPlot;
        private static PdfEditorForm _instance;
        private int _colorIndex = 0;
        private Point _dragStartPoint = Point.Empty;
        private bool _isSaved = false;
        private List<string> _autoGeneratedFiles = new List<string>();

        private TextBox txtFileName;

        public static PdfEditorForm Instance
        {
            get
            {
                if (_instance == null || _instance.IsDisposed)
                    _instance = new PdfEditorForm();
                return _instance;
            }
        }

        private PdfEditorForm()
        {
            InitializeComponent();
        }

        private void InitializeComponent()
        {
            this.Text = L10n.T("pdf_editor_title");
            this.Size = new Size(800, 500);
            this.MinimumSize = new Size(600, 400);
            this.StartPosition = FormStartPosition.CenterScreen;
            this.ShowIcon = false;

            var splitContainer = new SplitContainer { 
                Dock = DockStyle.Fill, 
                FixedPanel = FixedPanel.Panel1,
                IsSplitterFixed = true,
                Panel1MinSize = 320
            };
            this.Load += (s, e) => splitContainer.SplitterDistance = 320;
            this.Controls.Add(splitContainer);

            var pnlLeft = new Panel { Dock = DockStyle.Fill, Padding = new Padding(10) };
            splitContainer.Panel1.Controls.Add(pnlLeft);

            var pnlTools = new FlowLayoutPanel { Dock = DockStyle.Top, Height = 40, FlowDirection = FlowDirection.LeftToRight };
            pnlLeft.Controls.Add(pnlTools);

            btnPlusPlot = new Button { Text = L10n.T("btn_plot_more"), Width = 55, Height = 30, BackColor = Color.FromArgb(0, 122, 204), ForeColor = Color.White, Font = new Font("Segoe UI", 8.5F, FontStyle.Bold), FlatStyle = FlatStyle.Flat };
            btnPlusPlot.FlatAppearance.BorderSize = 0;

            btnAdd = new Button { Text = L10n.T("btn_add"), Width = 55, Height = 30, BackColor = Color.Black, ForeColor = Color.White, Font = new Font("Segoe UI", 8F, FontStyle.Bold), FlatStyle = FlatStyle.Flat };
            btnRemove = new Button { Text = L10n.T("btn_remove"), Width = 55, Height = 30, BackColor = Color.Black, ForeColor = Color.White, Font = new Font("Segoe UI", 8F, FontStyle.Bold), FlatStyle = FlatStyle.Flat };
            btnUp = new Button { Text = L10n.T("btn_up"), Width = 50, Height = 30, BackColor = Color.Black, ForeColor = Color.White, Font = new Font("Segoe UI", 8F, FontStyle.Bold), FlatStyle = FlatStyle.Flat };
            btnDown = new Button { Text = L10n.T("btn_down"), Width = 50, Height = 30, BackColor = Color.Black, ForeColor = Color.White, Font = new Font("Segoe UI", 8F, FontStyle.Bold), FlatStyle = FlatStyle.Flat };

            pnlTools.Controls.AddRange(new Control[] { btnPlusPlot, btnAdd, btnRemove, btnUp, btnDown });

            var pnlBottom = new Panel { Dock = DockStyle.Bottom, Height = 90 };
            pnlLeft.Controls.Add(pnlBottom);
            
            pnlBottom.Controls.Add(new Label { Text = L10n.T("label_basename"), Left = 10, Top = 0, AutoSize = true, ForeColor = Color.White, Font = new Font("Segoe UI", 8F) });
            txtFileName = new TextBox { Left = 10, Top = 20, Width = 290, Font = new Font("Segoe UI", 9F) };
            pnlBottom.Controls.Add(txtFileName);

            btnSave = new Button { Text = L10n.T("btn_save_file"), Width = 140, Height = 32, Left = 10, Top = 55, BackColor = Color.FromArgb(0, 122, 204), ForeColor = Color.White, Font = new Font("Segoe UI", 9F, FontStyle.Bold), FlatStyle = FlatStyle.Flat };
            btnSave.FlatAppearance.BorderSize = 0;
            btnCancel = new Button { Text = L10n.T("btn_cancel"), Width = 140, Height = 32, Left = 160, Top = 55, BackColor = Color.Black, ForeColor = Color.White, Font = new Font("Segoe UI", 9F, FontStyle.Bold), FlatStyle = FlatStyle.Flat };
            pnlBottom.Controls.AddRange(new Control[] { btnSave, btnCancel });

            foreach(var btn in new[] { btnAdd, btnRemove, btnUp, btnDown, btnCancel }) {
                btn.FlatAppearance.BorderColor = Color.Silver;
            }

            lstPages = new ListBox 
            { 
                Dock = DockStyle.Fill, 
                SelectionMode = SelectionMode.MultiExtended, 
                DrawMode = DrawMode.OwnerDrawFixed, 
                ItemHeight = 22, 
                Font = new Font("Segoe UI", 8.5F),
                AllowDrop = true
            };
            pnlLeft.Controls.Add(lstPages);
            lstPages.BringToFront();

            pdfViewer = new PdfViewer { 
                Dock = DockStyle.Fill,
                ShowToolbar = false,
                ShowBookmarks = false
            };
            splitContainer.Panel2.Controls.Add(pdfViewer);

            lstPages.DrawItem += LstPages_DrawItem;
            lstPages.SelectedIndexChanged += LstPages_SelectedIndexChanged;
            
            btnAdd.Click += BtnAdd_Click;
            btnRemove.Click += BtnRemove_Click;
            btnUp.Click += BtnUp_Click;
            btnDown.Click += BtnDown_Click;
            btnPlusPlot.Click += BtnPlusPlot_Click;
            btnSave.Click += BtnSave_Click;
            btnCancel.Click += (s, e) => this.Close();

            // Kéo thả
            lstPages.MouseDown += LstPages_MouseDown;
            lstPages.MouseMove += LstPages_MouseMove;
            lstPages.DragOver += LstPages_DragOver;
            lstPages.DragDrop += LstPages_DragDrop;

            ThemeManager.Apply(this, ThemeManager.IsDarkMode());
        }

        private Color GetNextColor()
        {
            double hue = (_colorIndex * 137.508) % 360.0;
            _colorIndex++;
            return HslToRgb(hue, 0.4, 0.85); // Saturation 40%, Lightness 85% for pastel colors
        }

        private Color HslToRgb(double h, double s, double l)
        {
            double c = (1.0 - Math.Abs(2.0 * l - 1.0)) * s;
            double x = c * (1.0 - Math.Abs((h / 60.0) % 2.0 - 1.0));
            double m = l - c / 2.0;

            double r = 0, g = 0, b = 0;
            if (h < 60) { r = c; g = x; }
            else if (h < 120) { r = x; g = c; }
            else if (h < 180) { g = c; b = x; }
            else if (h < 240) { g = x; b = c; }
            else if (h < 300) { r = x; b = c; }
            else { r = c; b = x; }

            return Color.FromArgb((int)((r + m) * 255), (int)((g + m) * 255), (int)((b + m) * 255));
        }

        public void AddPdfFiles(List<string> files, bool isAutoGenerated = true)
        {
            if (isAutoGenerated) _autoGeneratedFiles.AddRange(files);
            Color groupColor = GetNextColor();
            bool firstAdd = lstPages.Items.Count == 0;

            foreach (var file in files)
            {
                if (!File.Exists(file)) continue;
                try
                {
                    using (var doc = PdfReader.Open(file, PdfDocumentOpenMode.Import))
                    {
                        for (int i = 0; i < doc.PageCount; i++)
                        {
                            lstPages.Items.Add(new PdfPageItem
                            {
                                SourceFile = file,
                                PageIndex = i,
                                GroupColor = groupColor,
                                DisplayName = string.Format(L10n.T("page_name"), Path.GetFileName(file), i + 1)
                            });
                        }
                    }
                }
                catch { }
            }

            if (firstAdd && lstPages.Items.Count > 0)
                lstPages.SelectedIndex = 0;
        }

        private void LstPages_DrawItem(object sender, DrawItemEventArgs e)
        {
            if (e.Index < 0 || e.Index >= lstPages.Items.Count) return;

            var item = (PdfPageItem)lstPages.Items[e.Index];
            e.DrawBackground();

            // Tô màu nền theo group
            using (var brush = new SolidBrush(item.GroupColor))
            {
                e.Graphics.FillRectangle(brush, e.Bounds);
            }

            // Nếu đang chọn thì highlight đè lên
            if ((e.State & DrawItemState.Selected) == DrawItemState.Selected)
            {
                e.Graphics.FillRectangle(SystemBrushes.Highlight, e.Bounds);
            }

            var textColor = ((e.State & DrawItemState.Selected) == DrawItemState.Selected) ? SystemColors.HighlightText : SystemColors.ControlText;
            TextRenderer.DrawText(e.Graphics, item.DisplayName, e.Font, e.Bounds, textColor, TextFormatFlags.VerticalCenter | TextFormatFlags.Left);
            e.DrawFocusRectangle();
        }

        private void LstPages_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (lstPages.SelectedItem is PdfPageItem item)
            {
                try
                {
                    var oldDoc = pdfViewer.Document;

                    using (var sourceDoc = PdfReader.Open(item.SourceFile, PdfDocumentOpenMode.Import))
                    using (var singlePageDoc = new PdfSharp.Pdf.PdfDocument())
                    {
                        singlePageDoc.AddPage(sourceDoc.Pages[item.PageIndex]);
                        var ms = new MemoryStream();
                        singlePageDoc.Save(ms);
                        ms.Position = 0;
                        var doc = PdfiumViewer.PdfDocument.Load(ms);
                        pdfViewer.Document = doc;
                    }

                    oldDoc?.Dispose();
                }
                catch { }
            }
        }

        private void BtnAdd_Click(object sender, EventArgs e)
        {
            using (var ofd = new OpenFileDialog { Filter = "PDF Files|*.pdf", Multiselect = true, Title = L10n.T("dlg_add_pdf") })
            {
                if (ofd.ShowDialog() == DialogResult.OK)
                {
                    AddPdfFiles(ofd.FileNames.ToList(), false);
                }
            }
        }

        private void BtnRemove_Click(object sender, EventArgs e)
        {
            var selected = lstPages.SelectedItems.Cast<PdfPageItem>().ToList();
            lstPages.ClearSelected();
            foreach (var item in selected)
                lstPages.Items.Remove(item);
        }

        private void BtnUp_Click(object sender, EventArgs e)
        {
            MoveSelectedItems(-1);
        }

        private void BtnDown_Click(object sender, EventArgs e)
        {
            MoveSelectedItems(1);
        }

        private void MoveSelectedItems(int direction)
        {
            if (lstPages.SelectedItems.Count == 0) return;

            var selectedItems = lstPages.SelectedItems.Cast<PdfPageItem>().ToList();
            var selectedIndices = lstPages.SelectedIndices.Cast<int>().ToList();

            if (direction == -1 && selectedIndices.Min() == 0) return;
            if (direction == 1 && selectedIndices.Max() == lstPages.Items.Count - 1) return;

            lstPages.BeginUpdate();
            lstPages.ClearSelected();

            if (direction == 1)
            {
                selectedIndices.Reverse();
                selectedItems.Reverse();
            }

            for (int i = 0; i < selectedIndices.Count; i++)
            {
                int index = selectedIndices[i];
                var item = selectedItems[i];
                lstPages.Items.RemoveAt(index);
                lstPages.Items.Insert(index + direction, item);
                lstPages.SetSelected(index + direction, true);
            }
            lstPages.EndUpdate();
        }

        private void BtnPlusPlot_Click(object sender, EventArgs e)
        {
            this.Hide();
            if (Commands.MainFormInstance != null)
            {
                Commands.MainFormInstance.SetSubPlotMode(true);
                Commands.MainFormInstance.Show();
            }
        }

        public void SetDefaultFileName(string name)
        {
            if (string.IsNullOrEmpty(txtFileName.Text))
                txtFileName.Text = name;
        }

        private void BtnSave_Click(object sender, EventArgs e)
        {
            if (lstPages.Items.Count == 0) return;

            using (var sfd = new SaveFileDialog { Filter = "PDF File|*.pdf", Title = L10n.T("dlg_save_pdf"), FileName = txtFileName.Text })
            {
                if (sfd.ShowDialog() == DialogResult.OK)
                {
                    try
                    {
                        using (var outDoc = new PdfSharp.Pdf.PdfDocument())
                        {
                            foreach (PdfPageItem item in lstPages.Items)
                            {
                                using (var inDoc = PdfReader.Open(item.SourceFile, PdfDocumentOpenMode.Import))
                                {
                                    outDoc.AddPage(inDoc.Pages[item.PageIndex]);
                                }
                            }
                            outDoc.Save(sfd.FileName);
                        }
                        MessageBox.Show(L10n.T("msg_save_success"), L10n.T("app_title"), MessageBoxButtons.OK, MessageBoxIcon.Information);
                        try { System.Diagnostics.Process.Start(sfd.FileName); } catch { }
                    }
                    catch (Exception ex)
                    {
                        MessageBox.Show(string.Format(L10n.T("msg_save_error"), ex.Message), L10n.T("err_title"), MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }
            }
        }

        private void LstPages_MouseDown(object sender, MouseEventArgs e)
        {
            if (e.Button == MouseButtons.Left)
                _dragStartPoint = e.Location;
        }

        private void LstPages_MouseMove(object sender, MouseEventArgs e)
        {
            if (e.Button == MouseButtons.Left && _dragStartPoint != Point.Empty)
            {
                if (Math.Abs(e.X - _dragStartPoint.X) > SystemInformation.DragSize.Width ||
                    Math.Abs(e.Y - _dragStartPoint.Y) > SystemInformation.DragSize.Height)
                {
                    var selected = lstPages.SelectedItems.Cast<PdfPageItem>().ToList();
                    if (selected.Count > 0)
                    {
                        lstPages.DoDragDrop(selected, DragDropEffects.Move);
                    }
                }
            }
        }

        private void LstPages_DragOver(object sender, DragEventArgs e)
        {
            e.Effect = DragDropEffects.Move;
        }

        private void LstPages_DragDrop(object sender, DragEventArgs e)
        {
            Point point = lstPages.PointToClient(new Point(e.X, e.Y));
            int index = lstPages.IndexFromPoint(point);
            if (index < 0) index = lstPages.Items.Count - 1;

            if (e.Data.GetDataPresent(typeof(List<PdfPageItem>)))
            {
                var itemsToMove = (List<PdfPageItem>)e.Data.GetData(typeof(List<PdfPageItem>));
                
                lstPages.BeginUpdate();
                lstPages.ClearSelected();
                foreach (var item in itemsToMove)
                    lstPages.Items.Remove(item);

                int insertIndex = index;
                if (insertIndex > lstPages.Items.Count) insertIndex = lstPages.Items.Count;

                for (int i = 0; i < itemsToMove.Count; i++)
                {
                    lstPages.Items.Insert(insertIndex + i, itemsToMove[i]);
                    lstPages.SetSelected(insertIndex + i, true);
                }
                lstPages.EndUpdate();
            }
            _dragStartPoint = Point.Empty;
        }

        protected override void OnFormClosed(FormClosedEventArgs e)
        {
            if (!_isSaved)
            {
                foreach (string file in _autoGeneratedFiles)
                {
                    try { if (File.Exists(file)) File.Delete(file); } catch { }
                }
            }
            _autoGeneratedFiles.Clear();
            _isSaved = false;
            lstPages.Items.Clear();
            
            if (Commands.MainFormInstance != null)
            {
                Commands.MainFormInstance.SetSubPlotMode(false);
                Commands.MainFormInstance.Show();
            }
            base.OnFormClosed(e);
        }
    }
}
