using PdfiumViewer;
using PdfSharp.Pdf.IO;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Interop;
using System.Windows.Media;
using Point = System.Windows.Point;

namespace TPL
{
    /// <summary>
    /// Model cho mỗi trang PDF trong danh sách.
    /// Implements INotifyPropertyChanged để cập nhật STT khi thay đổi vị trí.
    /// </summary>
    public class PdfPageViewModel : INotifyPropertyChanged
    {
        private int _sequenceNumber;

        public string SourceFile { get; set; }
        public int PageIndex { get; set; }
        public int RotationDelta { get; set; } = 0;
        public System.Drawing.Color GroupColor { get; set; }
        public string DisplayName { get; set; }

        /// <summary>Cached single-page PDF bytes for instant preview.</summary>
        public byte[] PreviewData { get; set; }

        /// <summary>Nhãn nguồn gốc: "Plot" cho xuất từ AutoCAD, "File" cho thêm từ file.</summary>
        public string SourceLabel { get; set; } = "Plot";

        /// <summary>Mã nhóm để nhận diện batch (mỗi lần Plot hoặc Add file là 1 group).</summary>
        public int GroupId { get; set; }

        public int SequenceNumber
        {
            get => _sequenceNumber;
            set { _sequenceNumber = value; OnPropertyChanged(nameof(SequenceNumber)); }
        }

        /// <summary>Brush WPF dùng để hiển thị color indicator trong ListView.</summary>
        public SolidColorBrush GroupColorBrush =>
            new SolidColorBrush(Color.FromArgb(GroupColor.A, GroupColor.R, GroupColor.G, GroupColor.B));

        /// <summary>Màu nền nhạt (~18% opacity) để phân biệt rõ các nhóm PDF khác nhau.</summary>
        public SolidColorBrush RowBackgroundColorBrush =>
            new SolidColorBrush(Color.FromArgb(45, GroupColor.R, GroupColor.G, GroupColor.B));

        /// <summary>Màu nền khi hover — giữ tint nhóm + tăng sáng nhẹ.</summary>
        public SolidColorBrush HoverBackgroundBrush =>
            new SolidColorBrush(Color.FromArgb(70, GroupColor.R, GroupColor.G, GroupColor.B));

        /// <summary>Màu nền khi selected — blend accent blue + tint nhóm.</summary>
        public SolidColorBrush SelectedBackgroundBrush
        {
            get
            {
                // Blend group color với accent blue (#2563EB), ratio 40/60
                byte r = (byte)((GroupColor.R * 0.4) + (0x25 * 0.6));
                byte g = (byte)((GroupColor.G * 0.4) + (0x63 * 0.6));
                byte b = (byte)((GroupColor.B * 0.4) + (0xEB * 0.6));
                return new SolidColorBrush(Color.FromArgb(50, r, g, b));
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged(string name) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
    }

    /// <summary>
    /// PDF Editor WPF Window — thay thế PdfEditorForm (WinForms).
    /// Tính năng: STT column, multi-drag-drop reorder, progress bar khi save,
    /// fix preview kẹt khi remove, dark theme #181A1F, custom scrollbar.
    /// </summary>
    public partial class PdfEditorWindow : Window
    {
        // ─── Singleton ──────────────────────────────────────────────────────
        private static PdfEditorWindow _instance;
        public static PdfEditorWindow Instance
        {
            get
            {
                if (_instance == null || !_instance.IsLoaded)
                    _instance = new PdfEditorWindow();
                return _instance;
            }
        }

        // ─── Data ───────────────────────────────────────────────────────────
        private readonly ObservableCollection<PdfPageViewModel> _pages = new ObservableCollection<PdfPageViewModel>();
        private int _colorIndex = 0;
        private int _groupIdCounter = 0;
        private bool _isSaved = false;
        private readonly List<string> _autoGeneratedFiles = new List<string>();

        // Drag-drop state
        private Point _dragStartPoint;
        private bool _isDragging = false;

        // PDF Viewer (WinForms control hosted via WindowsFormsHost)
        private PdfViewer _pdfViewer;

        // ─── Constructor ────────────────────────────────────────────────────
        private PdfEditorWindow()
        {
            InitializeComponent();

            // Tạo PdfViewer (WinForms) và host trong WPF
            _pdfViewer = new PdfViewer
            {
                ShowToolbar = false,
                ShowBookmarks = false,
                Dock = System.Windows.Forms.DockStyle.Fill
            };
            pdfHost.Child = _pdfViewer;

            lstPages.ItemsSource = _pages;

            this.SourceInitialized += PdfEditorWindow_SourceInitialized;
        }

        // ─── Resize Flicker Fix ─────────────────────────────────────────────
        private void PdfEditorWindow_SourceInitialized(object sender, EventArgs e)
        {
            var hwndSource = PresentationSource.FromVisual(this) as HwndSource;
            hwndSource?.AddHook(HwndHook);
        }

        private const int WM_ENTERSIZEMOVE = 0x0231;
        private const int WM_EXITSIZEMOVE = 0x0232;

        private IntPtr HwndHook(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
        {
            if (msg == WM_ENTERSIZEMOVE)
            {
                // Ẩn WinFormsHost khi bắt đầu co kéo để chống nhấp nháy (airspace flicker)
                pdfHost.Visibility = Visibility.Hidden;
            }
            else if (msg == WM_EXITSIZEMOVE)
            {
                // Hiện lại khi thả chuột hoàn tất co kéo
                pdfHost.Visibility = Visibility.Visible;
            }
            return IntPtr.Zero;
        }

        // ─── Public API ─────────────────────────────────────────────────────

        /// <summary>Thêm danh sách file PDF vào editor.</summary>
        public void AddPdfFiles(List<string> files, bool isAutoGenerated = true)
        {
            if (isAutoGenerated) _autoGeneratedFiles.AddRange(files);

            System.Drawing.Color groupColor = GetNextColor();
            int currentGroupId = _groupIdCounter++;
            string sourceLabel = isAutoGenerated ? "Plot" : "File";
            bool firstAdd = _pages.Count == 0;

            foreach (string file in files)
            {
                if (!File.Exists(file)) continue;
                try
                {
                    using (var doc = PdfReader.Open(file, PdfDocumentOpenMode.Import))
                    {
                        bool separate = chkSeparatePdfs.IsChecked == true;

                        if (separate || isAutoGenerated)
                        {
                            // Chia từng trang như cũ
                            for (int i = 0; i < doc.PageCount; i++)
                            {
                                byte[] previewBytes;
                                using (var singlePageDoc = new PdfSharp.Pdf.PdfDocument())
                                {
                                    singlePageDoc.AddPage(doc.Pages[i]);
                                    using (var ms = new MemoryStream())
                                    {
                                        singlePageDoc.Save(ms);
                                        previewBytes = ms.ToArray();
                                    }
                                }

                                _pages.Add(new PdfPageViewModel
                                {
                                    SourceFile = file,
                                    PageIndex = i,
                                    GroupColor = groupColor,
                                    GroupId = currentGroupId,
                                    SourceLabel = sourceLabel,
                                    PreviewData = previewBytes,
                                    DisplayName = string.Format(L10n.T("page_name"), Path.GetFileName(file), i + 1),
                                    SequenceNumber = _pages.Count + 1
                                });
                            }
                        }
                        else
                        {
                            // Thêm nguyên 1 file PDF nhiều trang vào làm 1 dòng duy nhất
                            byte[] previewBytes = File.ReadAllBytes(file);
                            _pages.Add(new PdfPageViewModel
                            {
                                SourceFile = file,
                                PageIndex = -1, // -1 means All Pages
                                GroupColor = groupColor,
                                GroupId = currentGroupId,
                                SourceLabel = sourceLabel,
                                PreviewData = previewBytes,
                                DisplayName = Path.GetFileName(file),
                                SequenceNumber = _pages.Count + 1
                            });
                        }
                    }
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine($"[PdfEditor] Error loading {file}: {ex.Message}");
                }
            }

            AutoResizeSequenceColumn();

            if (firstAdd && _pages.Count > 0)
                lstPages.SelectedIndex = 0;
        }

        /// <summary>Đặt tên file mặc định (chỉ khi trống).</summary>
        public void SetDefaultFileName(string name)
        {
            if (string.IsNullOrEmpty(txtFileName.Text))
                txtFileName.Text = name;
        }

        // ─── Title bar (drag window) ────────────────────────────────────────
        private void TitleBar_MouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            if (e.ClickCount == 2)
            {
                // Double-click to maximize/restore
                WindowState = WindowState == WindowState.Maximized
                    ? WindowState.Normal
                    : WindowState.Maximized;
            }
            else
            {
                DragMove();
            }
        }

        private void BtnMinimize_Click(object sender, RoutedEventArgs e) => WindowState = WindowState.Minimized;
        private void BtnMaximize_Click(object sender, RoutedEventArgs e) => WindowState = WindowState == WindowState.Maximized ? WindowState.Normal : WindowState.Maximized;
        private void BtnClose_Click(object sender, RoutedEventArgs e) => Close();

        protected override void OnKeyDown(KeyEventArgs e)
        {
            if (e.Key == Key.Escape && WindowState == WindowState.Maximized)
            {
                WindowState = WindowState.Normal;
                e.Handled = true;
                return;
            }
            base.OnKeyDown(e);
        }

        private bool _isReordering = false;

        // ─── Page Selection → Preview ───────────────────────────────────────
        private void LstPages_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (_isReordering) return;

            if (lstPages.SelectedItem is PdfPageViewModel item)
            {
                try
                {
                    var oldDoc = _pdfViewer.Document;

                    // Load from cached bytes — no file I/O, instant preview
                    var ms = new MemoryStream(item.PreviewData);
                    var pdfDoc = PdfiumViewer.PdfDocument.Load(ms);
                    _pdfViewer.Document = pdfDoc;

                    oldDoc?.Dispose();
                    txtNoPreview.Visibility = Visibility.Collapsed;
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine($"[PdfEditor] Preview error: {ex.Message}");
                }
            }
            else
            {
                // Không có trang nào được chọn → hiện placeholder
                txtNoPreview.Visibility = Visibility.Visible;
            }
        }

        // ─── Toolbar Actions ────────────────────────────────────────────────

        private void BtnAdd_Click(object sender, RoutedEventArgs e)
        {
            var ofd = new Microsoft.Win32.OpenFileDialog
            {
                Filter = "PDF Files|*.pdf",
                Multiselect = true,
                Title = L10n.T("dlg_add_pdf")
            };

            if (ofd.ShowDialog() == true)
            {
                AddPdfFiles(ofd.FileNames.ToList(), false);
            }
        }

        private void BtnRemove_Click(object sender, RoutedEventArgs e)
        {
            var selected = lstPages.SelectedItems.Cast<PdfPageViewModel>().ToList();
            if (selected.Count == 0) return;

            // Ghi lại index trước khi xóa để chọn lại trang hợp lệ sau đó
            int firstSelectedIndex = lstPages.SelectedIndex;

            _isReordering = true;
            try
            {
                foreach (var item in selected)
                    _pages.Remove(item);

                RefreshSequenceNumbers();

                // ═══ FIX: sau khi xoá, chọn trang gần nhất (tránh preview kẹt) ═══
                if (_pages.Count > 0)
                {
                    int newIndex = Math.Min(firstSelectedIndex, _pages.Count - 1);
                    lstPages.SelectedIndex = newIndex;
                }
                else
                {
                    // Không còn trang nào → clear preview
                    var oldDoc = _pdfViewer.Document;
                    _pdfViewer.Document = null;
                    oldDoc?.Dispose();
                    txtNoPreview.Visibility = Visibility.Visible;
                }
            }
            finally
            {
                _isReordering = false;
                if (_pages.Count > 0)
                    LstPages_SelectionChanged(lstPages, null);
            }
        }

        private void BtnUp_Click(object sender, RoutedEventArgs e) => MoveSelectedItems(-1);
        private void BtnDown_Click(object sender, RoutedEventArgs e) => MoveSelectedItems(1);

        private void BtnRotate_Click(object sender, RoutedEventArgs e)
        {
            var selected = lstPages.SelectedItems.Cast<PdfPageViewModel>().ToList();
            if (selected.Count == 0) return;

            foreach (var item in selected)
            {
                item.RotationDelta = (item.RotationDelta + 90) % 360;

                // Update preview data to show rotation immediately
                try
                {
                    using (var ms = new MemoryStream(item.PreviewData))
                    using (var doc = PdfReader.Open(ms, PdfDocumentOpenMode.Modify))
                    {
                        foreach (var page in doc.Pages)
                        {
                            page.Rotate = (page.Rotate + 90) % 360;
                        }
                        using (var outMs = new MemoryStream())
                        {
                            doc.Save(outMs);
                            item.PreviewData = outMs.ToArray();
                        }
                    }
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine($"[PdfEditor] Rotate error: {ex.Message}");
                }
            }

            // Force refresh preview if a rotated item is currently viewed
            LstPages_SelectionChanged(lstPages, null);
        }

        private void MoveSelectedItems(int direction)
        {
            var selectedIndices = new List<int>();
            foreach (var item in lstPages.SelectedItems)
            {
                int idx = _pages.IndexOf((PdfPageViewModel)item);
                if (idx >= 0) selectedIndices.Add(idx);
            }
            if (selectedIndices.Count == 0) return;

            selectedIndices.Sort();

            if (direction == -1 && selectedIndices[0] == 0) return;
            if (direction == 1 && selectedIndices[selectedIndices.Count - 1] == _pages.Count - 1) return;

            // Di chuyển theo thứ tự phù hợp
            if (direction == 1) selectedIndices.Reverse();

            _isReordering = true;
            try
            {
                var newIndices = new List<int>();
                foreach (int idx in selectedIndices)
                {
                    int newIdx = idx + direction;
                    _pages.Move(idx, newIdx);
                    newIndices.Add(newIdx);
                }

                RefreshSequenceNumbers();

                // Giữ lại selection
                lstPages.SelectedItems.Clear();
                foreach (int idx in newIndices)
                    lstPages.SelectedItems.Add(_pages[idx]);
            }
            finally
            {
                _isReordering = false;
                LstPages_SelectionChanged(lstPages, null);
            }
        }

        private void BtnPlusPlot_Click(object sender, RoutedEventArgs e)
        {
            this.Hide();
            if (Commands.MainFormInstance != null)
            {
                Commands.MainFormInstance.SetSubPlotMode(true);
                Commands.MainFormInstance.Show();
            }
        }

        // ─── Save with Progress Bar ─────────────────────────────────────────
        private void BtnSave_Click(object sender, RoutedEventArgs e)
        {
            if (_pages.Count == 0) return;

            var sfd = new Microsoft.Win32.SaveFileDialog
            {
                Filter = "PDF File|*.pdf",
                Title = L10n.T("dlg_save_pdf"),
                FileName = txtFileName.Text
            };

            if (sfd.ShowDialog() == true)
            {
                try
                {
                    // Hiện progress bar
                    pnlProgress.Visibility = Visibility.Visible;
                    progressBar.Value = 0;
                    txtProgressLabel.Text = L10n.T("prog_merging");
                    txtProgressPercent.Text = "0%";
                    btnSave.IsEnabled = false;

                    // Force UI update
                    Dispatcher.Invoke(System.Windows.Threading.DispatcherPriority.Render, new Action(() => { }));

                    using (var outDoc = new PdfSharp.Pdf.PdfDocument())
                    {
                        int total = _pages.Count;
                        for (int i = 0; i < total; i++)
                        {
                            var item = _pages[i];
                            using (var inDoc = PdfReader.Open(item.SourceFile, PdfDocumentOpenMode.Import))
                            {
                                if (item.PageIndex == -1)
                                {
                                    for (int p = 0; p < inDoc.PageCount; p++)
                                    {
                                        var newPage = outDoc.AddPage(inDoc.Pages[p]);
                                        if (item.RotationDelta != 0) newPage.Rotate = (newPage.Rotate + item.RotationDelta) % 360;
                                    }
                                }
                                else
                                {
                                    var newPage = outDoc.AddPage(inDoc.Pages[item.PageIndex]);
                                    if (item.RotationDelta != 0) newPage.Rotate = (newPage.Rotate + item.RotationDelta) % 360;
                                }
                            }

                            // Cập nhật progress
                            int percent = (int)((double)(i + 1) / total * 100);
                            progressBar.Value = percent;
                            txtProgressPercent.Text = $"{percent}%";
                            txtProgressLabel.Text = string.Format(L10n.T("prog_progress"), i + 1, total);

                            // Force UI refresh
                            Dispatcher.Invoke(System.Windows.Threading.DispatcherPriority.Render, new Action(() => { }));
                        }

                        outDoc.Save(sfd.FileName);
                    }

                    // Hoàn tất
                    progressBar.Value = 100;
                    txtProgressPercent.Text = "100%";
                    txtProgressLabel.Text = "✅ " + L10n.T("msg_save_success");
                    _isSaved = true;

                    try { System.Diagnostics.Process.Start(sfd.FileName); } catch { }
                }
                catch (Exception ex)
                {
                    MessageBox.Show(
                        string.Format(L10n.T("msg_save_error"), ex.Message),
                        L10n.T("err_title"),
                        MessageBoxButton.OK, MessageBoxImage.Error);
                }
                finally
                {
                    btnSave.IsEnabled = true;
                    // Ẩn progress bar sau 2 giây
                    var timer = new System.Windows.Threading.DispatcherTimer { Interval = TimeSpan.FromSeconds(2) };
                    timer.Tick += (s2, e2) =>
                    {
                        pnlProgress.Visibility = Visibility.Collapsed;
                        timer.Stop();
                    };
                    timer.Start();
                }
            }
        }

        private void BtnCancel_Click(object sender, RoutedEventArgs e) => Close();

        // ─── Multi-item Drag & Drop with Drop Indicator ────────────────────

        private readonly PdfPageViewModel _dummyItem = new PdfPageViewModel { SourceLabel = "DUMMY", SequenceNumber = 0, DisplayName = "" };

        /// <summary>Kiểm tra nếu element thuộc Scrollbar → không cho kéo.</summary>
        private bool IsOverScrollbar(DependencyObject element)
        {
            while (element != null)
            {
                if (element is System.Windows.Controls.Primitives.ScrollBar)
                    return true;
                element = VisualTreeHelper.GetParent(element);
            }
            return false;
        }

        private void LstPages_PreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            // Nếu click trên Scrollbar → bỏ qua, không bắt đầu drag
            if (IsOverScrollbar(e.OriginalSource as DependencyObject))
            {
                _isDragging = false;
                return;
            }
            _dragStartPoint = e.GetPosition(lstPages);
            _isDragging = false;
        }

        private void LstPages_PreviewMouseMove(object sender, MouseEventArgs e)
        {
            if (e.LeftButton != MouseButtonState.Pressed) return;

            // Nếu click ban đầu trên Scrollbar → bỏ qua
            if (IsOverScrollbar(e.OriginalSource as DependencyObject)) return;

            Point currentPos = e.GetPosition(lstPages);
            Vector diff = _dragStartPoint - currentPos;

            // Kiểm tra ngưỡng kéo
            if (Math.Abs(diff.X) > SystemParameters.MinimumHorizontalDragDistance ||
                Math.Abs(diff.Y) > SystemParameters.MinimumVerticalDragDistance)
            {
                if (_isDragging) return;
                _isDragging = true;

                var selectedItems = lstPages.SelectedItems.Cast<PdfPageViewModel>().ToList();
                if (selectedItems.Count == 0) return;

                var dragData = new DataObject("PdfPages", selectedItems);
                DragDrop.DoDragDrop(lstPages, dragData, DragDropEffects.Move);
                _isDragging = false;

                // Xoá dummy sau khi kéo xong (dù thành công hay huỷ)
                RemoveDropAdorner();
            }
        }

        private void LstPages_DragOver(object sender, DragEventArgs e)
        {
            if (e.Data.GetDataPresent("PdfPages"))
            {
                e.Effects = DragDropEffects.Move;
                UpdateDropAdorner(e);
            }
            else
                e.Effects = DragDropEffects.None;
            e.Handled = true;
        }

        /// <summary>
        /// Chèn dummy item để tạo khoảng trống đẩy các item khác xuống.
        /// Chỉ kích hoạt khi chuột nằm gần viền trên/dưới của 1 item (vùng ranh giới giữa 2 dòng).
        /// Khi chuột ở giữa item → xoá dummy để tránh nhấp nháy.
        /// </summary>
        private const double EdgeThreshold = 3; // px — vùng kích hoạt ở mỗi mép trên/dưới

        private void UpdateDropAdorner(DragEventArgs e)
        {
            var targetElement = e.OriginalSource as DependencyObject;
            ListViewItem targetListViewItem = null;

            while (targetElement != null)
            {
                if (targetElement is ListViewItem lvi)
                {
                    targetListViewItem = lvi;
                    break;
                }
                targetElement = VisualTreeHelper.GetParent(targetElement);
            }

            // Nếu đang hover trên chính dummy → giữ nguyên, không làm gì
            if (targetListViewItem != null)
            {
                var targetItem = targetListViewItem.Content as PdfPageViewModel;
                if (targetItem == _dummyItem) return;
            }

            // Nếu không tìm thấy ListViewItem (hover trên vùng trống cuối list)
            if (targetListViewItem == null)
            {
                // Kiểm tra nếu đang hover trên Header hoặc Scrollbar thì không nhảy xuống cuối
                var curr = e.OriginalSource as DependencyObject;
                while (curr != null)
                {
                    if (curr is GridViewColumnHeader || curr is System.Windows.Controls.Primitives.ScrollBar)
                        return;
                    curr = VisualTreeHelper.GetParent(curr);
                }
                // Chèn dummy ở cuối list
                int dropIndex = _pages.Count;
                int currentDummyIndex = _pages.IndexOf(_dummyItem);

                // Loại trừ dummy khi tính vị trí
                if (currentDummyIndex >= 0 && currentDummyIndex < dropIndex) dropIndex--;
                if (currentDummyIndex == dropIndex) return;

                _isReordering = true;
                try
                {
                    if (currentDummyIndex >= 0) _pages.Remove(_dummyItem);
                    if (dropIndex > _pages.Count) dropIndex = _pages.Count;
                    _pages.Insert(dropIndex, _dummyItem);
                }
                finally { _isReordering = false; }
                return;
            }

            // Xác định vị trí chuột trong item
            Point pos = e.GetPosition(targetListViewItem);
            double itemHeight = targetListViewItem.ActualHeight;
            bool nearTop = pos.Y < EdgeThreshold;
            bool nearBottom = pos.Y > (itemHeight - EdgeThreshold);

            // Chuột ở giữa item (dead zone) → xoá dummy nếu đang có
            if (!nearTop && !nearBottom)
            {
                RemoveDropAdorner();
                return;
            }

            // Chuột gần mép → tính dropIndex
            var hoveredItem = targetListViewItem.Content as PdfPageViewModel;
            if (hoveredItem == null) return;

            int hoveredIndex = _pages.IndexOf(hoveredItem);
            int newDropIndex = nearTop ? hoveredIndex : hoveredIndex + 1;

            int curDummyIdx = _pages.IndexOf(_dummyItem);

            // Điều chỉnh nếu dummy đang đứng trước dropIndex
            if (curDummyIdx >= 0 && curDummyIdx < newDropIndex)
                newDropIndex--;

            // Nếu vị trí không đổi → bỏ qua
            if (curDummyIdx == newDropIndex) return;

            _isReordering = true;
            try
            {
                if (curDummyIdx >= 0) _pages.Remove(_dummyItem);

                if (newDropIndex < 0) newDropIndex = 0;
                if (newDropIndex > _pages.Count) newDropIndex = _pages.Count;

                _pages.Insert(newDropIndex, _dummyItem);
            }
            finally
            {
                _isReordering = false;
            }
        }

        private void RemoveDropAdorner()
        {
            if (_pages.Contains(_dummyItem))
            {
                _isReordering = true;
                _pages.Remove(_dummyItem);
                _isReordering = false;
            }
        }

        private void LstPages_Drop(object sender, DragEventArgs e)
        {
            int dummyIndex = _pages.IndexOf(_dummyItem);
            RemoveDropAdorner();

            if (!e.Data.GetDataPresent("PdfPages")) return;

            var droppedItems = e.Data.GetData("PdfPages") as List<PdfPageViewModel>;
            if (droppedItems == null || droppedItems.Count == 0) return;

            int dropIndex = dummyIndex >= 0 ? dummyIndex : _pages.Count;

            _isReordering = true;
            try
            {
                // Tính xem có bao nhiêu item được thả nằm trước dropIndex để lùi vị trí chèn
                int shift = 0;
                foreach (var item in droppedItems)
                {
                    if (_pages.IndexOf(item) < dropIndex)
                        shift++;
                }
                dropIndex -= shift;

                // Xoá items cũ
                foreach (var item in droppedItems)
                    _pages.Remove(item);

                // Điều chỉnh dropIndex sau khi xoá
                if (dropIndex < 0) dropIndex = 0;
                if (dropIndex > _pages.Count) dropIndex = _pages.Count;

                // Chèn lại tại vị trí mới
                for (int i = 0; i < droppedItems.Count; i++)
                    _pages.Insert(dropIndex + i, droppedItems[i]);

                RefreshSequenceNumbers();

                // Giữ selection
                lstPages.SelectedItems.Clear();
                foreach (var item in droppedItems)
                    lstPages.SelectedItems.Add(item);
            }
            finally
            {
                _isReordering = false;
                LstPages_SelectionChanged(lstPages, null);
            }
        }

        // ─── Helpers ────────────────────────────────────────────────────────

        /// <summary>Cập nhật cột STT cho toàn bộ danh sách.</summary>
        private void RefreshSequenceNumbers()
        {
            for (int i = 0; i < _pages.Count; i++)
                _pages[i].SequenceNumber = i + 1;
            AutoResizeSequenceColumn();
        }

        /// <summary>Tự động điều chỉnh chiều rộng các cột cho phù hợp với nội dung.</summary>
        private void AutoResizeSequenceColumn()
        {
            if (_pages.Count == 0) return;

            // Tính chiều rộng cần thiết dựa trên số chữ số lớn nhất (cột STT)
            int maxDigits = _pages.Count.ToString().Length;
            double needed = Math.Max(35, maxDigits * 8 + 10);

            var gridView = lstPages.View as GridView;
            if (gridView != null && gridView.Columns.Count >= 4)
            {
                // Thay đổi chiều rộng cột #
                gridView.Columns[0].Width = needed;

                // Thay đổi chiều rộng cột Page để tự động fit chữ dài nhất
                if (double.IsNaN(gridView.Columns[3].Width))
                    gridView.Columns[3].Width = gridView.Columns[3].ActualWidth;

                gridView.Columns[3].Width = double.NaN; // Force Auto size
            }
        }

        /// <summary>Tạo màu pastel theo golden angle để phân biệt nhóm PDF.</summary>
        private System.Drawing.Color GetNextColor()
        {
            double hue = (_colorIndex * 137.508) % 360.0;
            _colorIndex++;
            return HslToRgb(hue, 0.4, 0.85);
        }

        private System.Drawing.Color HslToRgb(double h, double s, double l)
        {
            double c = (1.0 - Math.Abs(2.0 * l - 1.0)) * s;
            double x = c * (1.0 - Math.Abs((h / 60.0) % 2.0 - 1.0));
            double m = l - c / 2.0;

            double r = 0, g = 0, b = 0;
            if (h < 60) { r = c; g = x; }
            else if (h < 120) { r = x; g = c; }
            else if (h < 180) { g = c; b = x; }
            else if (h < 240) { g = x; b = c; }
            else if (h < 300) { r = x; b = c; }
            else { r = c; b = x; }

            return System.Drawing.Color.FromArgb(
                (int)((r + m) * 255),
                (int)((g + m) * 255),
                (int)((b + m) * 255));
        }

        // ─── Window Lifecycle ───────────────────────────────────────────────

        protected override void OnClosed(EventArgs e)
        {
            // Cleanup PDF viewer
            try
            {
                var oldDoc = _pdfViewer?.Document;
                if (_pdfViewer != null) _pdfViewer.Document = null;
                oldDoc?.Dispose();
            }
            catch { }

            // Xoá file tạm nếu chưa save
            if (!_isSaved)
            {
                foreach (string file in _autoGeneratedFiles)
                {
                    try { if (File.Exists(file)) File.Delete(file); } catch { }
                }
            }
            _autoGeneratedFiles.Clear();
            _isSaved = false;
            _colorIndex = 0;
            _groupIdCounter = 0;
            _pages.Clear();
            _instance = null;

            // Trở về MainForm
            if (Commands.MainFormInstance != null)
            {
                Commands.MainFormInstance.SetSubPlotMode(false);
                Commands.MainFormInstance.Show();
            }

            base.OnClosed(e);
        }
    }

}

