using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using PdfSharp.Pdf;
using PdfSharp.Pdf.IO;
using PdfiumViewer;
using Point = System.Windows.Point;

namespace TPL
{
    /// <summary>
    /// Model cho mỗi trang PDF trong danh sách.
    /// Implements INotifyPropertyChanged để cập nhật STT khi thay đổi vị trí.
    /// </summary>
    public class PdfPageViewModel : INotifyPropertyChanged
    {
        private int _sequenceNumber;

        public string SourceFile { get; set; }
        public int PageIndex { get; set; }
        public System.Drawing.Color GroupColor { get; set; }
        public string DisplayName { get; set; }

        public int SequenceNumber
        {
            get => _sequenceNumber;
            set { _sequenceNumber = value; OnPropertyChanged(nameof(SequenceNumber)); }
        }

        /// <summary>Brush WPF dùng để hiển thị color indicator trong ListView.</summary>
        public SolidColorBrush GroupColorBrush =>
            new SolidColorBrush(Color.FromArgb(GroupColor.A, GroupColor.R, GroupColor.G, GroupColor.B));

        public event PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged(string name) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
    }

    /// <summary>
    /// PDF Editor WPF Window — thay thế PdfEditorForm (WinForms).
    /// Tính năng: STT column, multi-drag-drop reorder, progress bar khi save,
    /// fix preview kẹt khi remove, dark theme #181A1F, custom scrollbar.
    /// </summary>
    public partial class PdfEditorWindow : Window
    {
        // ─── Singleton ──────────────────────────────────────────────────────
        private static PdfEditorWindow _instance;
        public static PdfEditorWindow Instance
        {
            get
            {
                if (_instance == null || !_instance.IsLoaded)
                    _instance = new PdfEditorWindow();
                return _instance;
            }
        }

        // ─── Data ───────────────────────────────────────────────────────────
        private readonly ObservableCollection<PdfPageViewModel> _pages = new ObservableCollection<PdfPageViewModel>();
        private int _colorIndex = 0;
        private bool _isSaved = false;
        private readonly List<string> _autoGeneratedFiles = new List<string>();

        // Drag-drop state
        private Point _dragStartPoint;
        private bool _isDragging = false;

        // PDF Viewer (WinForms control hosted via WindowsFormsHost)
        private PdfViewer _pdfViewer;

        // ─── Constructor ────────────────────────────────────────────────────
        private PdfEditorWindow()
        {
            InitializeComponent();

            // Tạo PdfViewer (WinForms) và host trong WPF
            _pdfViewer = new PdfViewer
            {
                ShowToolbar = false,
                ShowBookmarks = false,
                Dock = System.Windows.Forms.DockStyle.Fill
            };
            pdfHost.Child = _pdfViewer;

            lstPages.ItemsSource = _pages;
        }

        // ─── Public API ─────────────────────────────────────────────────────

        /// <summary>Thêm danh sách file PDF vào editor.</summary>
        public void AddPdfFiles(List<string> files, bool isAutoGenerated = true)
        {
            if (isAutoGenerated) _autoGeneratedFiles.AddRange(files);

            System.Drawing.Color groupColor = GetNextColor();
            bool firstAdd = _pages.Count == 0;

            foreach (string file in files)
            {
                if (!File.Exists(file)) continue;
                try
                {
                    using (var doc = PdfReader.Open(file, PdfDocumentOpenMode.Import))
                    {
                        for (int i = 0; i < doc.PageCount; i++)
                        {
                            _pages.Add(new PdfPageViewModel
                            {
                                SourceFile = file,
                                PageIndex = i,
                                GroupColor = groupColor,
                                DisplayName = string.Format(L10n.T("page_name"), Path.GetFileName(file), i + 1),
                                SequenceNumber = _pages.Count + 1
                            });
                        }
                    }
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine($"[PdfEditor] Error loading {file}: {ex.Message}");
                }
            }

            if (firstAdd && _pages.Count > 0)
                lstPages.SelectedIndex = 0;
        }

        /// <summary>Đặt tên file mặc định (chỉ khi trống).</summary>
        public void SetDefaultFileName(string name)
        {
            if (string.IsNullOrEmpty(txtFileName.Text))
                txtFileName.Text = name;
        }

        // ─── Title bar (drag window) ────────────────────────────────────────
        private void TitleBar_MouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            if (e.ClickCount == 2)
            {
                // Double-click to maximize/restore
                WindowState = WindowState == WindowState.Maximized
                    ? WindowState.Normal
                    : WindowState.Maximized;
            }
            else
            {
                DragMove();
            }
        }

        private void BtnMinimize_Click(object sender, RoutedEventArgs e) => WindowState = WindowState.Minimized;
        private void BtnClose_Click(object sender, RoutedEventArgs e) => Close();

        // ─── Page Selection → Preview ───────────────────────────────────────
        private void LstPages_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (lstPages.SelectedItem is PdfPageViewModel item)
            {
                try
                {
                    var oldDoc = _pdfViewer.Document;

                    using (var sourceDoc = PdfReader.Open(item.SourceFile, PdfDocumentOpenMode.Import))
                    using (var singlePageDoc = new PdfSharp.Pdf.PdfDocument())
                    {
                        singlePageDoc.AddPage(sourceDoc.Pages[item.PageIndex]);
                        var ms = new MemoryStream();
                        singlePageDoc.Save(ms);
                        ms.Position = 0;
                        var pdfDoc = PdfiumViewer.PdfDocument.Load(ms);
                        _pdfViewer.Document = pdfDoc;
                    }

                    oldDoc?.Dispose();
                    txtNoPreview.Visibility = Visibility.Collapsed;
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine($"[PdfEditor] Preview error: {ex.Message}");
                }
            }
            else
            {
                // Không có trang nào được chọn → hiện placeholder
                txtNoPreview.Visibility = Visibility.Visible;
            }
        }

        // ─── Toolbar Actions ────────────────────────────────────────────────

        private void BtnAdd_Click(object sender, RoutedEventArgs e)
        {
            var ofd = new Microsoft.Win32.OpenFileDialog
            {
                Filter = "PDF Files|*.pdf",
                Multiselect = true,
                Title = L10n.T("dlg_add_pdf")
            };

            if (ofd.ShowDialog() == true)
            {
                AddPdfFiles(ofd.FileNames.ToList(), false);
            }
        }

        private void BtnRemove_Click(object sender, RoutedEventArgs e)
        {
            var selected = lstPages.SelectedItems.Cast<PdfPageViewModel>().ToList();
            if (selected.Count == 0) return;

            // Ghi lại index trước khi xóa để chọn lại trang hợp lệ sau đó
            int firstSelectedIndex = lstPages.SelectedIndex;

            foreach (var item in selected)
                _pages.Remove(item);

            RefreshSequenceNumbers();

            // ═══ FIX: sau khi xoá, chọn trang gần nhất (tránh preview kẹt) ═══
            if (_pages.Count > 0)
            {
                int newIndex = Math.Min(firstSelectedIndex, _pages.Count - 1);
                lstPages.SelectedIndex = newIndex;
            }
            else
            {
                // Không còn trang nào → clear preview
                var oldDoc = _pdfViewer.Document;
                _pdfViewer.Document = null;
                oldDoc?.Dispose();
                txtNoPreview.Visibility = Visibility.Visible;
            }
        }

        private void BtnUp_Click(object sender, RoutedEventArgs e) => MoveSelectedItems(-1);
        private void BtnDown_Click(object sender, RoutedEventArgs e) => MoveSelectedItems(1);

        private void MoveSelectedItems(int direction)
        {
            var selectedIndices = new List<int>();
            foreach (var item in lstPages.SelectedItems)
            {
                int idx = _pages.IndexOf((PdfPageViewModel)item);
                if (idx >= 0) selectedIndices.Add(idx);
            }
            if (selectedIndices.Count == 0) return;

            selectedIndices.Sort();

            if (direction == -1 && selectedIndices[0] == 0) return;
            if (direction == 1 && selectedIndices[selectedIndices.Count - 1] == _pages.Count - 1) return;

            // Di chuyển theo thứ tự phù hợp
            if (direction == 1) selectedIndices.Reverse();

            var newIndices = new List<int>();
            foreach (int idx in selectedIndices)
            {
                int newIdx = idx + direction;
                _pages.Move(idx, newIdx);
                newIndices.Add(newIdx);
            }

            RefreshSequenceNumbers();

            // Giữ lại selection
            lstPages.SelectedItems.Clear();
            foreach (int idx in newIndices)
                lstPages.SelectedItems.Add(_pages[idx]);
        }

        private void BtnPlusPlot_Click(object sender, RoutedEventArgs e)
        {
            this.Hide();
            if (Commands.MainFormInstance != null)
            {
                Commands.MainFormInstance.SetSubPlotMode(true);
                Commands.MainFormInstance.Show();
            }
        }

        // ─── Save with Progress Bar ─────────────────────────────────────────
        private void BtnSave_Click(object sender, RoutedEventArgs e)
        {
            if (_pages.Count == 0) return;

            var sfd = new Microsoft.Win32.SaveFileDialog
            {
                Filter = "PDF File|*.pdf",
                Title = L10n.T("dlg_save_pdf"),
                FileName = txtFileName.Text
            };

            if (sfd.ShowDialog() == true)
            {
                try
                {
                    // Hiện progress bar
                    pnlProgress.Visibility = Visibility.Visible;
                    progressBar.Value = 0;
                    txtProgressLabel.Text = L10n.T("prog_merging");
                    txtProgressPercent.Text = "0%";
                    btnSave.IsEnabled = false;

                    // Force UI update
                    Dispatcher.Invoke(System.Windows.Threading.DispatcherPriority.Render, new Action(() => { }));

                    using (var outDoc = new PdfSharp.Pdf.PdfDocument())
                    {
                        int total = _pages.Count;
                        for (int i = 0; i < total; i++)
                        {
                            var item = _pages[i];
                            using (var inDoc = PdfReader.Open(item.SourceFile, PdfDocumentOpenMode.Import))
                            {
                                outDoc.AddPage(inDoc.Pages[item.PageIndex]);
                            }

                            // Cập nhật progress
                            int percent = (int)((double)(i + 1) / total * 100);
                            progressBar.Value = percent;
                            txtProgressPercent.Text = $"{percent}%";
                            txtProgressLabel.Text = string.Format(L10n.T("prog_progress"), i + 1, total);

                            // Force UI refresh
                            Dispatcher.Invoke(System.Windows.Threading.DispatcherPriority.Render, new Action(() => { }));
                        }

                        outDoc.Save(sfd.FileName);
                    }

                    // Hoàn tất
                    progressBar.Value = 100;
                    txtProgressPercent.Text = "100%";
                    txtProgressLabel.Text = "✅ " + L10n.T("msg_save_success");
                    _isSaved = true;

                    try { System.Diagnostics.Process.Start(sfd.FileName); } catch { }
                }
                catch (Exception ex)
                {
                    MessageBox.Show(
                        string.Format(L10n.T("msg_save_error"), ex.Message),
                        L10n.T("err_title"),
                        MessageBoxButton.OK, MessageBoxImage.Error);
                }
                finally
                {
                    btnSave.IsEnabled = true;
                    // Ẩn progress bar sau 2 giây
                    var timer = new System.Windows.Threading.DispatcherTimer { Interval = TimeSpan.FromSeconds(2) };
                    timer.Tick += (s2, e2) =>
                    {
                        pnlProgress.Visibility = Visibility.Collapsed;
                        timer.Stop();
                    };
                    timer.Start();
                }
            }
        }

        private void BtnCancel_Click(object sender, RoutedEventArgs e) => Close();

        // ─── Multi-item Drag & Drop ─────────────────────────────────────────

        private void LstPages_PreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            _dragStartPoint = e.GetPosition(lstPages);
            _isDragging = false;
        }

        private void LstPages_PreviewMouseMove(object sender, MouseEventArgs e)
        {
            if (e.LeftButton != MouseButtonState.Pressed) return;

            Point currentPos = e.GetPosition(lstPages);
            Vector diff = _dragStartPoint - currentPos;

            // Kiểm tra ngưỡng kéo
            if (Math.Abs(diff.X) > SystemParameters.MinimumHorizontalDragDistance ||
                Math.Abs(diff.Y) > SystemParameters.MinimumVerticalDragDistance)
            {
                if (_isDragging) return;
                _isDragging = true;

                var selectedItems = lstPages.SelectedItems.Cast<PdfPageViewModel>().ToList();
                if (selectedItems.Count == 0) return;

                var dragData = new DataObject("PdfPages", selectedItems);
                DragDrop.DoDragDrop(lstPages, dragData, DragDropEffects.Move);
                _isDragging = false;
            }
        }

        private void LstPages_DragOver(object sender, DragEventArgs e)
        {
            if (e.Data.GetDataPresent("PdfPages"))
                e.Effects = DragDropEffects.Move;
            else
                e.Effects = DragDropEffects.None;
            e.Handled = true;
        }

        private void LstPages_Drop(object sender, DragEventArgs e)
        {
            if (!e.Data.GetDataPresent("PdfPages")) return;

            var droppedItems = e.Data.GetData("PdfPages") as List<PdfPageViewModel>;
            if (droppedItems == null || droppedItems.Count == 0) return;

            // Tìm vị trí drop
            int dropIndex = _pages.Count; // mặc định cuối list
            var targetElement = e.OriginalSource as DependencyObject;

            while (targetElement != null)
            {
                if (targetElement is ListViewItem listViewItem)
                {
                    var targetItem = listViewItem.Content as PdfPageViewModel;
                    if (targetItem != null)
                    {
                        dropIndex = _pages.IndexOf(targetItem);
                    }
                    break;
                }
                targetElement = VisualTreeHelper.GetParent(targetElement);
            }

            // Xoá items cũ
            foreach (var item in droppedItems)
                _pages.Remove(item);

            // Điều chỉnh dropIndex sau khi xoá
            if (dropIndex > _pages.Count) dropIndex = _pages.Count;

            // Chèn lại tại vị trí mới
            for (int i = 0; i < droppedItems.Count; i++)
                _pages.Insert(dropIndex + i, droppedItems[i]);

            RefreshSequenceNumbers();

            // Giữ selection
            lstPages.SelectedItems.Clear();
            foreach (var item in droppedItems)
                lstPages.SelectedItems.Add(item);
        }

        // ─── Helpers ────────────────────────────────────────────────────────

        /// <summary>Cập nhật cột STT cho toàn bộ danh sách.</summary>
        private void RefreshSequenceNumbers()
        {
            for (int i = 0; i < _pages.Count; i++)
                _pages[i].SequenceNumber = i + 1;
        }

        /// <summary>Tạo màu pastel theo golden angle để phân biệt nhóm PDF.</summary>
        private System.Drawing.Color GetNextColor()
        {
            double hue = (_colorIndex * 137.508) % 360.0;
            _colorIndex++;
            return HslToRgb(hue, 0.4, 0.85);
        }

        private System.Drawing.Color HslToRgb(double h, double s, double l)
        {
            double c = (1.0 - Math.Abs(2.0 * l - 1.0)) * s;
            double x = c * (1.0 - Math.Abs((h / 60.0) % 2.0 - 1.0));
            double m = l - c / 2.0;

            double r = 0, g = 0, b = 0;
            if (h < 60) { r = c; g = x; }
            else if (h < 120) { r = x; g = c; }
            else if (h < 180) { g = c; b = x; }
            else if (h < 240) { g = x; b = c; }
            else if (h < 300) { r = x; b = c; }
            else { r = c; b = x; }

            return System.Drawing.Color.FromArgb(
                (int)((r + m) * 255),
                (int)((g + m) * 255),
                (int)((b + m) * 255));
        }

        // ─── Window Lifecycle ───────────────────────────────────────────────

        protected override void OnClosed(EventArgs e)
        {
            // Cleanup PDF viewer
            try
            {
                var oldDoc = _pdfViewer?.Document;
                if (_pdfViewer != null) _pdfViewer.Document = null;
                oldDoc?.Dispose();
            }
            catch { }

            // Xoá file tạm nếu chưa save
            if (!_isSaved)
            {
                foreach (string file in _autoGeneratedFiles)
                {
                    try { if (File.Exists(file)) File.Delete(file); } catch { }
                }
            }
            _autoGeneratedFiles.Clear();
            _isSaved = false;
            _pages.Clear();
            _instance = null;

            // Trở về MainForm
            if (Commands.MainFormInstance != null)
            {
                Commands.MainFormInstance.SetSubPlotMode(false);
                Commands.MainFormInstance.Show();
            }

            base.OnClosed(e);
        }
    }
}
