; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define AppName "TPL - AutoCAD Batch Plotter"
#define AppVersion "1.0.0"
#define AppPublisher "Tam Hoang"
#define AppId "{{A9D12F2C-6C4B-4813-97BA-FF8B2D5D4E12}"
#define BundleDirName "TPL.bundle"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
AppId={#AppId}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
DefaultDirName={userappdata}\Autodesk\ApplicationPlugins\{#BundleDirName}
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
DirExistsWarning=no
; Cài đặt cho User hiện tại (không yêu cầu quyền Admin tối cao)
PrivilegesRequired=lowest
OutputBaseFilename=TPL_Setup
SetupIconFile=Resource\IconRibbon_32px.ico
UninstallDisplayIcon={app}\IconRibbon_32px.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
; Sao chép file cấu hình PackageContents.xml vào thư mục gốc của bundle
Source: "TPL.bundle\PackageContents.xml"; DestDir: "{app}"; Flags: ignoreversion

; Sao chép file Icon để hiển thị trong Control Panel và Shortcut
Source: "Resource\IconRibbon_32px.ico"; DestDir: "{app}"; Flags: ignoreversion

; Sao chép toàn bộ thư viện và tệp DLL cho AutoCAD 2015-2024 (.NET Framework 4.8)
Source: "bin\x64\Release\net48\*"; DestDir: "{app}\Contents\v2021-2024"; Flags: ignoreversion recursesubdirs createallsubdirs

; Sao chép toàn bộ thư viện và tệp DLL cho AutoCAD 2025-2026+ (.NET 8.0-windows)
Source: "bin\x64\Release\net8.0-windows\*"; DestDir: "{app}\Contents\v2025-2026"; Flags: ignoreversion recursesubdirs createallsubdirs

; Standalone PDF editor shared by every AutoCAD version
Source: "PdfEditor\bin\x64\Release\net48\*"; DestDir: "{app}\Contents\PdfEditor"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{userprograms}\{#AppName}\TPL PDF Editor"; Filename: "{app}\Contents\PdfEditor\TPL.PdfEditor.exe"; IconFilename: "{app}\IconRibbon_32px.ico"
; Tạo shortcut gỡ cài đặt có Icon chuyên nghiệp trong Start Menu
Name: "{userprograms}\{#AppName}\Uninstall TPL Plotter"; Filename: "{uninstallexe}"; IconFilename: "{app}\IconRibbon_32px.ico"

[InstallDelete]
; Dọn dẹp thư mục Contents cũ trước khi ghi đè bản mới
Type: filesandordirs; Name: "{app}\Contents\*"

[UninstallDelete]
; Xóa sạch thư mục bundle khi người dùng Uninstall
Type: filesandordirs; Name: "{app}"
