using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Interop;
using System.Windows.Media;
using PdfiumViewer;
using PdfSharp.Pdf.IO;
using TPL.Presentation.ViewModels;
using Point = System.Windows.Point;

namespace TPL.Presentation.Views
{
	/// <summary>
	/// PDF Editor WPF Window — tính năng: STT column, multi-drag-drop reorder,
	/// progress bar khi save, preview PDF (WinForms PdfiumViewer hosted).
	/// </summary>
	public partial class PdfEditorWindow : Window
	{
		// ─── Singleton ──────────────────────────────────────────────────────
		private static PdfEditorWindow _instance;
		private bool _isClosing = false;
		public static PdfEditorWindow Instance
		{
			get
			{
				if (_instance == null || _instance._isClosing || !_instance.IsLoaded)
					_instance = new PdfEditorWindow();
				return _instance;
			}
		}

		// ─── Callbacks for host (TPL.App) ───────────────────────────────
		public Action OnPlusPlotRequested { get; set; }
		public Action OnCloseReturnToMain { get; set; }
		public Func<string, string> Localize { get; set; }

		// ─── Data ───────────────────────────────────────────────────────────
		private readonly ObservableCollection<PdfPageViewModel> _pages = new();
		private int _colorIndex = 0;
		private int _groupIdCounter = 0;
		private readonly List<string> _autoGeneratedFiles = new();

		// Drag-drop state
		private Point _dragStartPoint;
		private bool _isDragging = false;

		// PDF Viewer (WinForms control hosted via WindowsFormsHost)
		private readonly PdfViewer _pdfViewer;
		private MemoryStream _currentPreviewStream;

		// ─── Constructor ────────────────────────────────────────────────────
		private PdfEditorWindow()
		{
			Localize = key => key; // Default passthrough
			InitializeComponent();

			_pdfViewer = new PdfViewer
			{
				ShowToolbar = false,
				ShowBookmarks = false,
				Dock = System.Windows.Forms.DockStyle.Fill
			};
			pdfHost.Child = _pdfViewer;
			lstPages.ItemsSource = _pages;
			this.SourceInitialized += PdfEditorWindow_SourceInitialized;
		}

		// ─── Resize Flicker Fix ─────────────────────────────────────────────
		private void PdfEditorWindow_SourceInitialized(object sender, EventArgs e)
		{
			var hwndSource = PresentationSource.FromVisual(this) as HwndSource;
			hwndSource?.AddHook(HwndHook);
		}

		private const int WM_ENTERSIZEMOVE = 0x0231;
		private const int WM_EXITSIZEMOVE = 0x0232;

		private IntPtr HwndHook(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
		{
			if (msg == WM_ENTERSIZEMOVE) pdfHost.Visibility = Visibility.Hidden;
			else if (msg == WM_EXITSIZEMOVE) pdfHost.Visibility = Visibility.Visible;
			return IntPtr.Zero;
		}

		private string L(string key) => Localize?.Invoke(key) ?? key;

		// ─── Public API ─────────────────────────────────────────────────────

		public async void AddPdfFiles(List<string> files, bool isAutoGenerated = true)
		{
			if (isAutoGenerated) _autoGeneratedFiles.AddRange(files);

			System.Drawing.Color groupColor = GetNextColor();
			int currentGroupId = _groupIdCounter++;
			string sourceLabel = isAutoGenerated ? "Plot" : "File";
			bool firstAdd = _pages.Count == 0;
			bool separate = chkSeparatePdfs.IsChecked == true;

			btnAdd.IsEnabled = false;
			btnPlusPlot.IsEnabled = false;

			try
			{
				var loadedPages = await Task.Run(() =>
				{
					var results = new List<PdfPageViewModel>();
					foreach (string file in files)
					{
						if (!File.Exists(file)) continue;
						try
						{
							using var doc = PdfReader.Open(file, PdfDocumentOpenMode.Import);
							if (separate || isAutoGenerated)
							{
								for (int i = 0; i < doc.PageCount; i++)
								{
									byte[] previewBytes;
									using (var singlePageDoc = new PdfSharp.Pdf.PdfDocument())
									{
										singlePageDoc.AddPage(doc.Pages[i]);
										using var ms = new MemoryStream();
										singlePageDoc.Save(ms);
										previewBytes = ms.ToArray();
									}
									results.Add(new PdfPageViewModel
									{
										SourceFile = file,
										PageIndex = i,
										GroupColor = groupColor,
										GroupId = currentGroupId,
										SourceLabel = sourceLabel,
										PreviewData = previewBytes,
										DisplayName = $"{Path.GetFileName(file)} (p{i + 1})"
									});
								}
							}
							else
							{
								byte[] previewBytes = File.ReadAllBytes(file);
								results.Add(new PdfPageViewModel
								{
									SourceFile = file,
									PageIndex = -1,
									GroupColor = groupColor,
									GroupId = currentGroupId,
									SourceLabel = sourceLabel,
									PreviewData = previewBytes,
									DisplayName = Path.GetFileName(file)
								});
							}
						}
						catch (System.Exception ex)
						{
							System.Diagnostics.Debug.WriteLine($"[PdfEditor] Error loading {file}: {ex.Message}");
						}
					}
					return results;
				});

				foreach (var page in loadedPages)
				{
					page.SequenceNumber = _pages.Count + 1;
					_pages.Add(page);
				}
				AutoResizeSequenceColumn();
				if (firstAdd && _pages.Count > 0) lstPages.SelectedIndex = 0;
			}
			catch (System.Exception ex)
			{
				System.Diagnostics.Debug.WriteLine($"[PdfEditor] AddPdfFiles error: {ex.Message}");
			}
			finally
			{
				btnAdd.IsEnabled = true;
				btnPlusPlot.IsEnabled = true;
			}
		}

		public void SetDefaultFileName(string name)
		{
			if (string.IsNullOrEmpty(txtFileName.Text))
				txtFileName.Text = name;
		}

		// ─── Title bar ────────────────────────────────────────────────
		private void TitleBar_MouseLeftButtonDown(object sender, MouseButtonEventArgs e)
		{
			if (e.ClickCount == 2)
				WindowState = WindowState == WindowState.Maximized ? WindowState.Normal : WindowState.Maximized;
			else
				DragMove();
		}
		private void BtnMinimize_Click(object sender, RoutedEventArgs e) => WindowState = WindowState.Minimized;
		private void BtnMaximize_Click(object sender, RoutedEventArgs e) => WindowState = WindowState == WindowState.Maximized ? WindowState.Normal : WindowState.Maximized;
		private void BtnClose_Click(object sender, RoutedEventArgs e) => Close();

		protected override void OnKeyDown(KeyEventArgs e)
		{
			if (e.Key == Key.Escape && WindowState == WindowState.Maximized)
			{
				WindowState = WindowState.Normal;
				e.Handled = true;
				return;
			}
			base.OnKeyDown(e);
		}

		private bool _isReordering = false;

		// ─── Page Selection → Preview ──────────────────────────────────
		private void LstPages_SelectionChanged(object sender, SelectionChangedEventArgs e)
		{
			if (_isReordering) return;
			if (lstPages.SelectedItem is PdfPageViewModel item)
			{
				try
				{
					var oldDoc = _pdfViewer.Document;
					var oldStream = _currentPreviewStream;
					var ms = new MemoryStream(item.PreviewData);
					_currentPreviewStream = ms;
					var pdfDoc = PdfiumViewer.PdfDocument.Load(ms);
					_pdfViewer.Document = pdfDoc;
					oldDoc?.Dispose();
					oldStream?.Dispose();
					txtNoPreview.Visibility = Visibility.Collapsed;
				}
				catch (System.Exception ex)
				{
					System.Diagnostics.Debug.WriteLine($"[PdfEditor] Preview error: {ex.Message}");
				}
			}
			else
			{
				txtNoPreview.Visibility = Visibility.Visible;
			}
		}

		// ─── Toolbar Actions ──────────────────────────────────────────
		private void BtnAdd_Click(object sender, RoutedEventArgs e)
		{
			var ofd = new Microsoft.Win32.OpenFileDialog
			{
				Filter = "PDF Files|*.pdf",
				Multiselect = true,
				Title = L("dlg_add_pdf")
			};
			if (ofd.ShowDialog() == true) AddPdfFiles(ofd.FileNames.ToList(), false);
		}

		private void BtnRemove_Click(object sender, RoutedEventArgs e)
		{
			var selected = lstPages.SelectedItems.Cast<PdfPageViewModel>().ToList();
			if (selected.Count == 0) return;
			int firstSelectedIndex = lstPages.SelectedIndex;

			_isReordering = true;
			try
			{
				foreach (var item in selected) _pages.Remove(item);
				RefreshSequenceNumbers();
				if (_pages.Count > 0)
				{
					int newIndex = Math.Min(firstSelectedIndex, _pages.Count - 1);
					lstPages.SelectedIndex = newIndex;
				}
				else
				{
					var oldDoc = _pdfViewer.Document;
					_pdfViewer.Document = null;
					oldDoc?.Dispose();
					txtNoPreview.Visibility = Visibility.Visible;
				}
			}
			finally
			{
				_isReordering = false;
				if (_pages.Count > 0) LstPages_SelectionChanged(lstPages, null);
			}
		}

		private void BtnUp_Click(object sender, RoutedEventArgs e) => MoveSelectedItems(-1);
		private void BtnDown_Click(object sender, RoutedEventArgs e) => MoveSelectedItems(1);

		private void BtnRotate_Click(object sender, RoutedEventArgs e)
		{
			var selected = lstPages.SelectedItems.Cast<PdfPageViewModel>().ToList();
			if (selected.Count == 0) return;
			foreach (var item in selected)
			{
				item.RotationDelta = (item.RotationDelta + 90) % 360;
				try
				{
					using var ms = new MemoryStream(item.PreviewData);
					using var doc = PdfReader.Open(ms, PdfDocumentOpenMode.Modify);
					foreach (var page in doc.Pages) page.Rotate = (page.Rotate + 90) % 360;
					using var outMs = new MemoryStream();
					doc.Save(outMs);
					item.PreviewData = outMs.ToArray();
				}
				catch (System.Exception ex)
				{
					System.Diagnostics.Debug.WriteLine($"[PdfEditor] Rotate error: {ex.Message}");
				}
			}
			LstPages_SelectionChanged(lstPages, null);
		}

		private void MoveSelectedItems(int direction)
		{
			var selectedIndices = new List<int>();
			foreach (var item in lstPages.SelectedItems)
			{
				int idx = _pages.IndexOf((PdfPageViewModel)item);
				if (idx >= 0) selectedIndices.Add(idx);
			}
			if (selectedIndices.Count == 0) return;
			selectedIndices.Sort();
			if (direction == -1 && selectedIndices[0] == 0) return;
			if (direction == 1 && selectedIndices[selectedIndices.Count - 1] == _pages.Count - 1) return;
			if (direction == 1) selectedIndices.Reverse();

			_isReordering = true;
			try
			{
				var newIndices = new List<int>();
				foreach (int idx in selectedIndices)
				{
					int newIdx = idx + direction;
					_pages.Move(idx, newIdx);
					newIndices.Add(newIdx);
				}
				RefreshSequenceNumbers();
				lstPages.SelectedItems.Clear();
				foreach (int idx in newIndices) lstPages.SelectedItems.Add(_pages[idx]);
			}
			finally
			{
				_isReordering = false;
				LstPages_SelectionChanged(lstPages, null);
			}
		}

		private void BtnPlusPlot_Click(object sender, RoutedEventArgs e)
		{
			this.Hide();
			OnPlusPlotRequested?.Invoke();
		}

		// ─── Save ────────────────────────────────────────────────────────
		private async void BtnSave_Click(object sender, RoutedEventArgs e)
		{
			if (_pages.Count == 0) return;
			var sfd = new Microsoft.Win32.SaveFileDialog
			{
				Filter = "PDF File|*.pdf",
				Title = L("dlg_save_pdf"),
				FileName = txtFileName.Text
			};
			if (sfd.ShowDialog() != true) return;
			string savePath = sfd.FileName;

			pnlProgress.Visibility = Visibility.Visible;
			pnlProgress.Value = 0;
			pnlProgress.Label = L("prog_merging");
			pnlProgress.Percent = "0%";
			btnSave.IsEnabled = false;
			btnCancel.IsEnabled = false;

			var pageSnapshots = _pages
				.Where(p => p.SourceLabel != "DUMMY")
				.Select(p => new { p.SourceFile, p.PageIndex, p.RotationDelta, p.PreviewData })
				.ToList();

			try
			{
				int total = pageSnapshots.Count;
				await Task.Run(() =>
				{
					using var outDoc = new PdfSharp.Pdf.PdfDocument();
					for (int i = 0; i < total; i++)
					{
						var item = pageSnapshots[i];
						if (item.PreviewData != null && item.PreviewData.Length > 0)
						{
							using var ms = new MemoryStream(item.PreviewData);
							using var inDoc = PdfReader.Open(ms, PdfDocumentOpenMode.Import);
							for (int p = 0; p < inDoc.PageCount; p++) outDoc.AddPage(inDoc.Pages[p]);
						}
						else
						{
							using var inDoc = PdfReader.Open(item.SourceFile, PdfDocumentOpenMode.Import);
							if (item.PageIndex == -1)
							{
								for (int p = 0; p < inDoc.PageCount; p++)
								{
									var newPage = outDoc.AddPage(inDoc.Pages[p]);
									if (item.RotationDelta != 0) newPage.Rotate = (newPage.Rotate + item.RotationDelta) % 360;
								}
							}
							else
							{
								var newPage = outDoc.AddPage(inDoc.Pages[item.PageIndex]);
								if (item.RotationDelta != 0) newPage.Rotate = (newPage.Rotate + item.RotationDelta) % 360;
							}
						}
						int percent = (int)((double)(i + 1) / total * 100);
						int currentIndex = i;
						Dispatcher.InvokeAsync(() =>
						{
							pnlProgress.Value = percent;
							pnlProgress.Percent = $"{percent}%";
							pnlProgress.Label = $"Page {currentIndex + 1}/{total}";
						});
					}
					outDoc.Save(savePath);
				});

				pnlProgress.Value = 100;
				pnlProgress.Percent = "100%";
				pnlProgress.Label = "✅ Saved!";
				try { System.Diagnostics.Process.Start(savePath); } catch { }
			}
			catch (System.Exception ex)
			{
				MessageBox.Show($"Save error: {ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
			}
			finally
			{
				btnSave.IsEnabled = true;
				btnCancel.IsEnabled = true;
				var timer = new System.Windows.Threading.DispatcherTimer { Interval = TimeSpan.FromSeconds(2) };
				timer.Tick += (s2, e2) => { pnlProgress.Visibility = Visibility.Collapsed; timer.Stop(); };
				timer.Start();
			}
		}

		private void BtnCancel_Click(object sender, RoutedEventArgs e) => Close();

		// ─── Multi-item Drag & Drop ──────────────────────────────────────
		private readonly PdfPageViewModel _dummyItem = new() { SourceLabel = "DUMMY", SequenceNumber = 0, DisplayName = "" };

		private bool IsOverScrollbar(DependencyObject element)
		{
			while (element != null)
			{
				if (element is System.Windows.Controls.Primitives.ScrollBar) return true;
				element = VisualTreeHelper.GetParent(element);
			}
			return false;
		}

		private void LstPages_PreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
		{
			if (IsOverScrollbar(e.OriginalSource as DependencyObject)) { _isDragging = false; return; }
			_dragStartPoint = e.GetPosition(lstPages);
			_isDragging = false;
		}

		private void LstPages_PreviewMouseMove(object sender, MouseEventArgs e)
		{
			if (e.LeftButton != MouseButtonState.Pressed) return;
			if (IsOverScrollbar(e.OriginalSource as DependencyObject)) return;
			Point currentPos = e.GetPosition(lstPages);
			Vector diff = _dragStartPoint - currentPos;
			if (Math.Abs(diff.X) > SystemParameters.MinimumHorizontalDragDistance ||
				Math.Abs(diff.Y) > SystemParameters.MinimumVerticalDragDistance)
			{
				if (_isDragging) return;
				_isDragging = true;
				var selectedItems = lstPages.SelectedItems.Cast<PdfPageViewModel>().ToList();
				if (selectedItems.Count == 0) return;
				var dragData = new DataObject("PdfPages", selectedItems);
				DragDrop.DoDragDrop(lstPages, dragData, DragDropEffects.Move);
				_isDragging = false;
				RemoveDropAdorner();
			}
		}

		private void LstPages_DragOver(object sender, DragEventArgs e)
		{
			if (e.Data.GetDataPresent("PdfPages")) { e.Effects = DragDropEffects.Move; UpdateDropAdorner(e); }
			else e.Effects = DragDropEffects.None;
			e.Handled = true;
		}

		private const double EdgeThreshold = 3;

		private void UpdateDropAdorner(DragEventArgs e)
		{
			var targetElement = e.OriginalSource as DependencyObject;
			ListViewItem targetListViewItem = null;
			while (targetElement != null)
			{
				if (targetElement is ListViewItem lvi) { targetListViewItem = lvi; break; }
				targetElement = VisualTreeHelper.GetParent(targetElement);
			}
			if (targetListViewItem != null)
			{
				var targetItem = targetListViewItem.Content as PdfPageViewModel;
				if (targetItem == _dummyItem) return;
			}
			if (targetListViewItem == null)
			{
				var curr = e.OriginalSource as DependencyObject;
				while (curr != null)
				{
					if (curr is GridViewColumnHeader || curr is System.Windows.Controls.Primitives.ScrollBar) return;
					curr = VisualTreeHelper.GetParent(curr);
				}
				int dropIndex = _pages.Count;
				int currentDummyIndex = _pages.IndexOf(_dummyItem);
				if (currentDummyIndex >= 0 && currentDummyIndex < dropIndex) dropIndex--;
				if (currentDummyIndex == dropIndex) return;
				_isReordering = true;
				try
				{
					if (currentDummyIndex >= 0) _pages.Remove(_dummyItem);
					if (dropIndex > _pages.Count) dropIndex = _pages.Count;
					_pages.Insert(dropIndex, _dummyItem);
				}
				finally { _isReordering = false; }
				return;
			}

			Point pos = e.GetPosition(targetListViewItem);
			double itemHeight = targetListViewItem.ActualHeight;
			bool nearTop = pos.Y < EdgeThreshold;
			bool nearBottom = pos.Y > (itemHeight - EdgeThreshold);
			if (!nearTop && !nearBottom) { RemoveDropAdorner(); return; }

			if (!(targetListViewItem.Content is PdfPageViewModel hoveredItem)) return;
			int hoveredIndex = _pages.IndexOf(hoveredItem);
			int newDropIndex = nearTop ? hoveredIndex : hoveredIndex + 1;
			int curDummyIdx = _pages.IndexOf(_dummyItem);
			if (curDummyIdx >= 0 && curDummyIdx < newDropIndex) newDropIndex--;
			if (curDummyIdx == newDropIndex) return;

			_isReordering = true;
			try
			{
				if (curDummyIdx >= 0) _pages.Remove(_dummyItem);
				if (newDropIndex < 0) newDropIndex = 0;
				if (newDropIndex > _pages.Count) newDropIndex = _pages.Count;
				_pages.Insert(newDropIndex, _dummyItem);
			}
			finally { _isReordering = false; }
		}

		private void RemoveDropAdorner()
		{
			if (_pages.Contains(_dummyItem))
			{
				_isReordering = true;
				_pages.Remove(_dummyItem);
				_isReordering = false;
			}
		}

		private void LstPages_Drop(object sender, DragEventArgs e)
		{
			int dummyIndex = _pages.IndexOf(_dummyItem);
			RemoveDropAdorner();
			if (!e.Data.GetDataPresent("PdfPages")) return;
			if (!(e.Data.GetData("PdfPages") is List<PdfPageViewModel> droppedItems) || droppedItems.Count == 0) return;
			int dropIndex = dummyIndex >= 0 ? dummyIndex : _pages.Count;

			_isReordering = true;
			try
			{
				int shift = 0;
				foreach (var item in droppedItems)
				{
					if (_pages.IndexOf(item) < dropIndex) shift++;
				}
				dropIndex -= shift;
				foreach (var item in droppedItems) _pages.Remove(item);
				if (dropIndex < 0) dropIndex = 0;
				if (dropIndex > _pages.Count) dropIndex = _pages.Count;
				for (int i = 0; i < droppedItems.Count; i++) _pages.Insert(dropIndex + i, droppedItems[i]);
				RefreshSequenceNumbers();
				lstPages.SelectedItems.Clear();
				foreach (var item in droppedItems) lstPages.SelectedItems.Add(item);
			}
			finally
			{
				_isReordering = false;
				LstPages_SelectionChanged(lstPages, null);
			}
		}

		// ─── Helpers ────────────────────────────────────────────────────────
		private void RefreshSequenceNumbers()
		{
			for (int i = 0; i < _pages.Count; i++) _pages[i].SequenceNumber = i + 1;
			AutoResizeSequenceColumn();
		}

		private void AutoResizeSequenceColumn()
		{
			if (_pages.Count == 0) return;
			int maxDigits = _pages.Count.ToString().Length;
			double needed = Math.Max(35, maxDigits * 8 + 10);
			if (lstPages.View is GridView gridView && gridView.Columns.Count >= 4)
			{
				gridView.Columns[0].Width = needed;
				if (double.IsNaN(gridView.Columns[3].Width))
					gridView.Columns[3].Width = gridView.Columns[3].ActualWidth;
				gridView.Columns[3].Width = double.NaN;
			}
		}

		private System.Drawing.Color GetNextColor()
		{
			double hue = (_colorIndex * 137.508) % 360.0;
			_colorIndex++;
			return HslToRgb(hue, 0.4, 0.85);
		}

		private System.Drawing.Color HslToRgb(double h, double s, double l)
		{
			double c = (1.0 - Math.Abs(2.0 * l - 1.0)) * s;
			double x = c * (1.0 - Math.Abs((h / 60.0) % 2.0 - 1.0));
			double m = l - c / 2.0;
			double r = 0, g = 0, b = 0;
			if (h < 60) { r = c; g = x; }
			else if (h < 120) { r = x; g = c; }
			else if (h < 180) { g = c; b = x; }
			else if (h < 240) { g = x; b = c; }
			else if (h < 300) { r = x; b = c; }
			else { r = c; b = x; }
			return System.Drawing.Color.FromArgb(
				(int)((r + m) * 255),
				(int)((g + m) * 255),
				(int)((b + m) * 255));
		}

		// ─── Window Lifecycle ───────────────────────────────────────────────
		protected override void OnClosing(CancelEventArgs e)
		{
			_isClosing = true;
			base.OnClosing(e);
		}

		protected override void OnClosed(EventArgs e)
		{
			try
			{
				var oldDoc = _pdfViewer?.Document;
				if (_pdfViewer != null) _pdfViewer.Document = null;
				oldDoc?.Dispose();
				_currentPreviewStream?.Dispose();
				_currentPreviewStream = null;
			}
			catch { }

			foreach (string file in _autoGeneratedFiles)
			{
				try { if (File.Exists(file)) File.Delete(file); } catch { }
			}
			_autoGeneratedFiles.Clear();
			_colorIndex = 0;
			_groupIdCounter = 0;
			_pages.Clear();
			_instance = null;

			OnCloseReturnToMain?.Invoke();
			base.OnClosed(e);
		}
	}
}
