using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Interop;
using System.Windows.Media;
using PdfiumViewer;
using PdfSharp.Pdf.IO;
using Point = System.Windows.Point;

namespace TPL
{
	/// <summary>
	/// Model cho mỗi trang PDF trong danh sách.
	/// Implements INotifyPropertyChanged để cập nhật STT khi thay đổi vị trí.
	/// </summary>
	public class PdfPageViewModel : INotifyPropertyChanged
	{
		private int _sequenceNumber;

		public string SourceFile { get; set; }
		public int PageIndex { get; set; }
		public int RotationDelta { get; set; } = 0;
		public System.Drawing.Color GroupColor { get; set; }
		public string DisplayName { get; set; }

		/// <summary>Lazy preview cache. Populated only after the page is selected.</summary>
		public byte[] PreviewData { get; set; }

		/// <summary>Nhãn nguồn gốc: "Plot" cho xuất từ AutoCAD, "File" cho thêm từ file.</summary>
		public string SourceLabel { get; set; } = "Plot";

		/// <summary>Mã nhóm để nhận diện batch (mỗi lần Plot hoặc Add file là 1 group).</summary>
		public int GroupId { get; set; }

		public int SequenceNumber
		{
			get => _sequenceNumber;
			set { _sequenceNumber = value; OnPropertyChanged(nameof(SequenceNumber)); }
		}

		/// <summary>Brush WPF dùng để hiển thị color indicator trong ListView.</summary>
		private SolidColorBrush _groupColorBrush;
		public SolidColorBrush GroupColorBrush =>
			_groupColorBrush ??= new(Color.FromArgb(GroupColor.A, GroupColor.R, GroupColor.G, GroupColor.B));

		/// <summary>Màu nền nhạt (~18% opacity) để phân biệt rõ các nhóm PDF khác nhau.</summary>
		private SolidColorBrush _rowBackgroundColorBrush;
		public SolidColorBrush RowBackgroundColorBrush =>
			_rowBackgroundColorBrush ??= new(Color.FromArgb(45, GroupColor.R, GroupColor.G, GroupColor.B));

		/// <summary>Màu nền khi hover — giữ tint nhóm + tăng sáng nhẹ.</summary>
		private SolidColorBrush _hoverBackgroundBrush;
		public SolidColorBrush HoverBackgroundBrush =>
			_hoverBackgroundBrush ??= new(Color.FromArgb(70, GroupColor.R, GroupColor.G, GroupColor.B));

		/// <summary>Màu nền khi selected — blend accent blue + tint nhóm.</summary>
		private SolidColorBrush _selectedBackgroundBrush;
		public SolidColorBrush SelectedBackgroundBrush
		{
			get
			{
				if (_selectedBackgroundBrush != null) return _selectedBackgroundBrush;
				// Blend group color với accent blue (#2563EB), ratio 40/60
				byte r = (byte)((GroupColor.R * 0.4) + (0x25 * 0.6));
				byte g = (byte)((GroupColor.G * 0.4) + (0x63 * 0.6));
				byte b = (byte)((GroupColor.B * 0.4) + (0xEB * 0.6));
				_selectedBackgroundBrush = new SolidColorBrush(Color.FromArgb(50, r, g, b));
				return _selectedBackgroundBrush;
			}
		}

		public event PropertyChangedEventHandler PropertyChanged;
		protected void OnPropertyChanged(string name) =>
			PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
	}

	/// <summary>
	/// PDF Editor WPF Window — thay thế PdfEditorForm (WinForms).
	/// Tính năng: STT column, multi-drag-drop reorder, progress bar khi save,
	/// fix preview kẹt khi remove, dark theme #181A1F, custom scrollbar.
	/// </summary>
	public partial class PdfEditorWindow : Window
	{
		// ─── Singleton ──────────────────────────────────────────────────────
		private static PdfEditorWindow _instance;
		private bool _isClosing = false;
		public static PdfEditorWindow Instance
		{
			get
			{
				if (_instance == null || _instance._isClosing || !_instance.IsLoaded)
					_instance = new PdfEditorWindow();
				return _instance;
			}
		}

		// ─── Data ───────────────────────────────────────────────────────────
		private readonly ObservableCollection<PdfPageViewModel> _pages = new();
		private int _colorIndex = 0;
		private int _groupIdCounter = 0;
		private readonly List<string> _autoGeneratedFiles = new();
		private readonly SemaphoreSlim _pdfLoadGate = new(1, 1);
		private readonly CancellationTokenSource _loadCancellation = new();

		// Drag-drop state
		private const string PdfPagesDataFormat = "TPL.PdfPages";
		private const double AutoScrollBoundary = 28;
		private static readonly TimeSpan AutoScrollInterval = TimeSpan.FromMilliseconds(50);
		private Point _dragStartPoint;
		private PdfPageViewModel _dragStartItem;
		private bool _collapseSelectionOnMouseUp;
		private bool _isDragging;
		private int _dropInsertIndex = -1;
		private DateTime _lastAutoScrollUtc = DateTime.MinValue;
		private ScrollViewer _pageListScrollViewer;
		private DropInsertionAdorner _dropInsertionAdorner;

		// PDF Viewer (WinForms control hosted via WindowsFormsHost)
		private static readonly int[] StandardZoomPercentages =
		{
			10, 25, 50, 75, 100, 125, 150, 200, 250, 300, 400, 500
		};
		private readonly ObservableCollection<int> _zoomPercentOptions = new(StandardZoomPercentages);
		private readonly PdfViewer _pdfViewer;
		private MemoryStream _currentPreviewStream;
		private int _previewRequestId;
		private int? _customZoomPercentage;
		private bool _isUpdatingZoomSelection;
		private HwndSource _hwndSource;

		// ─── Constructor ────────────────────────────────────────────────────
		private PdfEditorWindow()
		{
			InitializeComponent();

			// Tạo PdfViewer (WinForms) và host trong WPF
			_pdfViewer = new PdfViewer
			{
				ShowToolbar = false,
				ShowBookmarks = false,
				Dock = System.Windows.Forms.DockStyle.Fill,
				BackColor = System.Drawing.Color.FromArgb(0x18, 0x1A, 0x1F)
			};
			_pdfViewer.Renderer.BackColor = System.Drawing.Color.FromArgb(0x18, 0x1A, 0x1F);
			_pdfViewer.Renderer.MouseWheelMode = MouseWheelMode.Zoom;
			_pdfViewer.Renderer.ZoomChanged += PdfRenderer_ZoomChanged;
			_pdfViewer.Renderer.HandleCreated += PdfRenderer_HandleCreated;
			cmbZoomPercent.ItemsSource = _zoomPercentOptions;
			pdfHost.Child = _pdfViewer;
			UpdateZoomControls();
			UpdateWindowStateVisual();

			lstPages.ItemsSource = _pages;

			this.SourceInitialized += PdfEditorWindow_SourceInitialized;
		}

		// ─── Resize Flicker Fix ─────────────────────────────────────────────
		private void PdfEditorWindow_SourceInitialized(object sender, EventArgs e)
		{
			_hwndSource = PresentationSource.FromVisual(this) as HwndSource;
			_hwndSource?.AddHook(HwndHook);
		}

		private const int WM_GETMINMAXINFO = 0x0024;
		private const int WM_ENTERSIZEMOVE = 0x0231;
		private const int WM_EXITSIZEMOVE = 0x0232;
		private const uint MONITOR_DEFAULTTONEAREST = 0x00000002;

		private IntPtr HwndHook(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
		{
			try
			{
				if (msg == WM_GETMINMAXINFO)
				{
					ApplyWindowSizeConstraints(hwnd, lParam);
					handled = true;
				}
				else if (msg == WM_ENTERSIZEMOVE)
				{
					// Ẩn WinFormsHost khi bắt đầu co kéo để chống nhấp nháy (airspace flicker)
					pdfHost.Visibility = Visibility.Hidden;
				}
				else if (msg == WM_EXITSIZEMOVE)
				{
					// Hiện lại khi thả chuột hoàn tất co kéo
					pdfHost.Visibility = Visibility.Visible;
				}
			}
			catch (Exception ex)
			{
				System.Diagnostics.Debug.WriteLine($"[PdfEditor] Window message error: {ex.Message}");
			}

			return IntPtr.Zero;
		}

		private void ApplyWindowSizeConstraints(IntPtr hwnd, IntPtr minMaxInfoPointer)
		{
			if (minMaxInfoPointer == IntPtr.Zero)
				return;

			IntPtr monitor = MonitorFromWindow(hwnd, MONITOR_DEFAULTTONEAREST);
			if (monitor == IntPtr.Zero)
				return;

			var monitorInfo = new MonitorInfo
			{
				Size = Marshal.SizeOf<MonitorInfo>()
			};
			if (!GetMonitorInfo(monitor, ref monitorInfo))
				return;

			MinMaxInfo minMaxInfo = Marshal.PtrToStructure<MinMaxInfo>(minMaxInfoPointer);
			minMaxInfo.MaxPosition.X = monitorInfo.WorkArea.Left - monitorInfo.MonitorArea.Left;
			minMaxInfo.MaxPosition.Y = monitorInfo.WorkArea.Top - monitorInfo.MonitorArea.Top;
			minMaxInfo.MaxSize.X = monitorInfo.WorkArea.Right - monitorInfo.WorkArea.Left;
			minMaxInfo.MaxSize.Y = monitorInfo.WorkArea.Bottom - monitorInfo.WorkArea.Top;

			// WM_GETMINMAXINFO uses physical pixels, while WPF MinWidth/MinHeight use DIPs.
			// Preserve the XAML minimum size on the current monitor so the preview toolbar
			// and footer buttons cannot be clipped by native window resizing.
			double scaleX = 1.0;
			double scaleY = 1.0;
			if (_hwndSource?.CompositionTarget != null)
			{
				Matrix transformToDevice = _hwndSource.CompositionTarget.TransformToDevice;
				scaleX = transformToDevice.M11;
				scaleY = transformToDevice.M22;
			}

			minMaxInfo.MinTrackSize.X = Math.Max(
				minMaxInfo.MinTrackSize.X,
				(int)Math.Ceiling(MinWidth * scaleX));
			minMaxInfo.MinTrackSize.Y = Math.Max(
				minMaxInfo.MinTrackSize.Y,
				(int)Math.Ceiling(MinHeight * scaleY));
			Marshal.StructureToPtr(minMaxInfo, minMaxInfoPointer, false);
		}

		private void PdfRenderer_HandleCreated(object sender, EventArgs e)
		{
			ApplyPdfPreviewTheme();
		}

		private void ApplyPdfPreviewTheme()
		{
			try
			{
				PdfRenderer renderer = _pdfViewer.Renderer;
				if (!renderer.IsHandleCreated)
					return;

				int result = SetWindowTheme(renderer.Handle, "DarkMode_Explorer", null);
				if (result < 0)
					System.Diagnostics.Debug.WriteLine($"[PdfEditor] Native scrollbar theme returned 0x{result:X8}.");
			}
			catch (Exception ex)
			{
				System.Diagnostics.Debug.WriteLine($"[PdfEditor] Preview theme error: {ex.Message}");
			}
		}

		// ─── Public API ─────────────────────────────────────────────────────

		/// <summary>Thêm danh sách file PDF vào editor (async — không block UI).</summary>
		public async Task AddPdfFilesAsync(List<string> files, bool isAutoGenerated = true)
		{
			if (files == null || files.Count == 0) return;
			try
			{
				await _pdfLoadGate.WaitAsync(_loadCancellation.Token);
			}
			catch (OperationCanceledException)
			{
				return;
			}

			try
			{
				if (_isClosing || _loadCancellation.IsCancellationRequested) return;
				if (isAutoGenerated) _autoGeneratedFiles.AddRange(files);

				System.Drawing.Color groupColor = GetNextColor();
				int currentGroupId = _groupIdCounter++;
				string sourceLabel = isAutoGenerated ? "Plot" : "File";
				bool firstAdd = _pages.Count == 0;
				bool separate = chkSeparatePdfs.IsChecked == true;
				CancellationToken cancellationToken = _loadCancellation.Token;

				// Disable UI trong lúc load
				btnAdd.IsEnabled = false;
				btnPlusPlot.IsEnabled = false;

				try
				{
					// Heavy I/O chạy trên background thread
					var loadedPages = await Task.Run(() =>
					{
						var results = new List<PdfPageViewModel>();
						foreach (string file in files)
						{
							cancellationToken.ThrowIfCancellationRequested();
							if (!File.Exists(file)) continue;
							try
							{
								using var doc = PdfReader.Open(file, PdfDocumentOpenMode.Import);

								if (separate || isAutoGenerated)
								{
									for (int i = 0; i < doc.PageCount; i++)
									{
										cancellationToken.ThrowIfCancellationRequested();
										results.Add(new PdfPageViewModel
										{
											SourceFile = file,
											PageIndex = i,
											GroupColor = groupColor,
											GroupId = currentGroupId,
											SourceLabel = sourceLabel,
											DisplayName = isAutoGenerated
												? Path.GetFileName(file)
												: string.Format(L10n.T("page_name"), Path.GetFileName(file), i + 1)
										});
									}
								}
								else
								{
									results.Add(new PdfPageViewModel
									{
										SourceFile = file,
										PageIndex = -1,
										GroupColor = groupColor,
										GroupId = currentGroupId,
										SourceLabel = sourceLabel,
										DisplayName = Path.GetFileName(file)
									});
								}
							}
							catch (OperationCanceledException)
							{
								throw;
							}
							catch (Exception ex)
							{
								System.Diagnostics.Debug.WriteLine($"[PdfEditor] Error loading {file}: {ex.Message}");
							}
						}
						return results;
					}, cancellationToken);

					if (_isClosing || cancellationToken.IsCancellationRequested) return;

					// Add vào ObservableCollection trên UI thread
					foreach (var page in loadedPages)
					{
						page.SequenceNumber = _pages.Count + 1;
						_pages.Add(page);
					}

					AutoResizeSequenceColumn();

					if (firstAdd && _pages.Count > 0)
						lstPages.SelectedIndex = 0;
				}
				catch (OperationCanceledException) when (_loadCancellation.IsCancellationRequested)
				{
					// Expected when the window is closing.
				}
				catch (Exception ex)
				{
					System.Diagnostics.Debug.WriteLine($"[PdfEditor] AddPdfFiles error: {ex.Message}");
				}
				finally
				{
					if (!_isClosing)
					{
						btnAdd.IsEnabled = true;
						btnPlusPlot.IsEnabled = true;
					}
				}
			}
			finally
			{
				_pdfLoadGate.Release();
				if (_isClosing && isAutoGenerated)
				{
					foreach (string file in files)
					{
						try { if (File.Exists(file)) File.Delete(file); } catch { }
					}
				}
			}
		}

		/// <summary>Đặt tên file mặc định (chỉ khi trống).</summary>
		public void SetDefaultFileName(string name)
		{
			if (string.IsNullOrEmpty(txtFileName.Text))
				txtFileName.Text = name;
		}

		// ─── Title bar (drag window) ────────────────────────────────────────
		private void TitleBar_MouseLeftButtonDown(object sender, MouseButtonEventArgs e)
		{
			if (e.ClickCount == 2)
			{
				ToggleMaximizedState();
			}
			else
			{
				DragMove();
			}
		}

		private void BtnMinimize_Click(object sender, RoutedEventArgs e) => WindowState = WindowState.Minimized;
		private void BtnMaximize_Click(object sender, RoutedEventArgs e) => ToggleMaximizedState();
		private void BtnClose_Click(object sender, RoutedEventArgs e) => Close();

		private void ToggleMaximizedState()
		{
			if (WindowState == WindowState.Maximized)
				SystemCommands.RestoreWindow(this);
			else
				SystemCommands.MaximizeWindow(this);
		}

		protected override void OnStateChanged(EventArgs e)
		{
			base.OnStateChanged(e);
			UpdateWindowStateVisual();
		}

		private void UpdateWindowStateVisual()
		{
			if (iconMaximize == null || iconWindowed == null || btnMaximize == null)
				return;

			bool isMaximized = WindowState == WindowState.Maximized;
			iconMaximize.Visibility = isMaximized ? Visibility.Collapsed : Visibility.Visible;
			iconWindowed.Visibility = isMaximized ? Visibility.Visible : Visibility.Collapsed;
			btnMaximize.ToolTip = isMaximized ? "Restore window" : "Maximize";
		}

		protected override void OnKeyDown(KeyEventArgs e)
		{
			if (e.Key == Key.Escape && WindowState == WindowState.Maximized)
			{
				WindowState = WindowState.Normal;
				e.Handled = true;
				return;
			}
			base.OnKeyDown(e);
		}

		private bool _isReordering = false;

		// ─── Page Selection → Preview ───────────────────────────────────────
		private async void LstPages_SelectionChanged(object sender, SelectionChangedEventArgs e)
		{
			if (_isReordering) return;
			int requestId = ++_previewRequestId;

			if (lstPages.SelectedItem is PdfPageViewModel item)
			{
				try
				{
					byte[] previewData = item.PreviewData;
					if (previewData == null || previewData.Length == 0)
					{
						string sourceFile = item.SourceFile;
						int pageIndex = item.PageIndex;
						int rotationDelta = item.RotationDelta;
						previewData = await Task.Run(() => BuildPreviewData(sourceFile, pageIndex, rotationDelta));

						if (requestId != _previewRequestId || _isClosing || lstPages.SelectedItem != item)
							return;

						item.PreviewData = previewData;
					}

					if (requestId != _previewRequestId || _isClosing || lstPages.SelectedItem != item)
						return;

					var oldDoc = _pdfViewer.Document;
					var oldStream = _currentPreviewStream;

					var ms = new MemoryStream(previewData, writable: false);
					PdfiumViewer.PdfDocument pdfDoc;
					try
					{
						pdfDoc = PdfiumViewer.PdfDocument.Load(ms);
					}
					catch
					{
						ms.Dispose();
						throw;
					}

					_currentPreviewStream = ms;
					_pdfViewer.Document = pdfDoc;
					UpdateZoomControls();

					oldDoc?.Dispose();
					oldStream?.Dispose();
					txtNoPreview.Visibility = Visibility.Collapsed;
				}
				catch (Exception ex)
				{
					System.Diagnostics.Debug.WriteLine($"[PdfEditor] Preview error: {ex.Message}");
				}
			}
			else
			{
				// Không có trang nào được chọn → hiện placeholder
				txtNoPreview.Visibility = Visibility.Visible;
				UpdateZoomControls();
			}
		}

		private void BtnZoomOut_Click(object sender, RoutedEventArgs e)
		{
			if (_pdfViewer.Document != null)
				SetPreviewZoom(_pdfViewer.Renderer.Zoom / _pdfViewer.Renderer.ZoomFactor);
		}

		private void BtnZoomIn_Click(object sender, RoutedEventArgs e)
		{
			if (_pdfViewer.Document != null)
				SetPreviewZoom(_pdfViewer.Renderer.Zoom * _pdfViewer.Renderer.ZoomFactor);
		}

		private void CmbZoomPercent_SelectionChanged(object sender, SelectionChangedEventArgs e)
		{
			if (_isUpdatingZoomSelection || cmbZoomPercent.SelectedItem is not int zoomPercent)
				return;

			SetPreviewZoom(zoomPercent / 100d);
		}

		private void SetPreviewZoom(double requestedZoom)
		{
			PdfRenderer renderer = _pdfViewer.Renderer;
			if (_pdfViewer.Document == null || renderer.ClientSize.Width <= 0 || renderer.ClientSize.Height <= 0)
				return;

			double targetZoom = Math.Min(Math.Max(requestedZoom, renderer.ZoomMin), renderer.ZoomMax);
			if (Math.Abs(targetZoom - renderer.Zoom) < 0.0001)
				return;

			var viewportCenter = new System.Drawing.Point(
				renderer.ClientSize.Width / 2,
				renderer.ClientSize.Height / 2);
			PdfPoint pdfAnchor = renderer.PointToPdf(viewportCenter);
			System.Drawing.Rectangle oldDisplay = renderer.DisplayRectangle;
			double fallbackX = oldDisplay.Width > 0
				? (viewportCenter.X - oldDisplay.Left) / (double)oldDisplay.Width
				: 0.5;
			double fallbackY = oldDisplay.Height > 0
				? (viewportCenter.Y - oldDisplay.Top) / (double)oldDisplay.Height
				: 0.5;

			renderer.Zoom = targetZoom;

			System.Drawing.Rectangle newDisplay = renderer.DisplayRectangle;
			System.Drawing.Point targetDisplayLocation;
			if (pdfAnchor.IsValid)
			{
				System.Drawing.Point movedAnchor = renderer.PointFromPdf(pdfAnchor);
				targetDisplayLocation = new System.Drawing.Point(
					newDisplay.Left + viewportCenter.X - movedAnchor.X,
					newDisplay.Top + viewportCenter.Y - movedAnchor.Y);
			}
			else
			{
				targetDisplayLocation = new System.Drawing.Point(
					(int)Math.Round(viewportCenter.X - (fallbackX * newDisplay.Width)),
					(int)Math.Round(viewportCenter.Y - (fallbackY * newDisplay.Height)));
			}

			renderer.SetDisplayRectLocation(targetDisplayLocation, false);
		}

		private void PdfRenderer_ZoomChanged(object sender, EventArgs e)
		{
			UpdateZoomControls();
		}

		private void UpdateZoomControls()
		{
			if (!Dispatcher.CheckAccess())
			{
				Dispatcher.BeginInvoke(new Action(UpdateZoomControls));
				return;
			}

			double zoom = _pdfViewer.Renderer.Zoom;
			int zoomPercent = (int)Math.Round(zoom * 100, MidpointRounding.AwayFromZero);
			bool hasDocument = _pdfViewer.Document != null && lstPages.SelectedItem is PdfPageViewModel;

			UpdateZoomPercentageSelection(zoomPercent);
			cmbZoomPercent.IsEnabled = hasDocument;
			btnZoomOut.IsEnabled = hasDocument && zoom > _pdfViewer.Renderer.ZoomMin;
			btnZoomIn.IsEnabled = hasDocument && zoom < _pdfViewer.Renderer.ZoomMax;
		}

		private void UpdateZoomPercentageSelection(int zoomPercent)
		{
			_isUpdatingZoomSelection = true;
			try
			{
				bool isStandardZoom = Array.BinarySearch(StandardZoomPercentages, zoomPercent) >= 0;
				if (_customZoomPercentage.HasValue && _customZoomPercentage.Value != zoomPercent)
					_zoomPercentOptions.Remove(_customZoomPercentage.Value);

				if (!_zoomPercentOptions.Contains(zoomPercent))
				{
					int insertIndex = 0;
					while (insertIndex < _zoomPercentOptions.Count && _zoomPercentOptions[insertIndex] < zoomPercent)
						insertIndex++;

					_zoomPercentOptions.Insert(insertIndex, zoomPercent);
				}

				_customZoomPercentage = isStandardZoom ? null : zoomPercent;
				cmbZoomPercent.SelectedItem = zoomPercent;
			}
			finally
			{
				_isUpdatingZoomSelection = false;
			}
		}

		private static byte[] BuildPreviewData(string sourceFile, int pageIndex, int rotationDelta)
		{
			if (pageIndex == -1 && rotationDelta == 0)
				return File.ReadAllBytes(sourceFile);

			using var sourceDoc = PdfReader.Open(sourceFile, PdfDocumentOpenMode.Import);
			using var previewDoc = new PdfSharp.Pdf.PdfDocument();

			if (pageIndex == -1)
			{
				for (int i = 0; i < sourceDoc.PageCount; i++)
				{
					var page = previewDoc.AddPage(sourceDoc.Pages[i]);
					if (rotationDelta != 0)
						page.Rotate = (page.Rotate + rotationDelta) % 360;
				}
			}
			else
			{
				var page = previewDoc.AddPage(sourceDoc.Pages[pageIndex]);
				if (rotationDelta != 0)
					page.Rotate = (page.Rotate + rotationDelta) % 360;
			}

			using var output = new MemoryStream();
			previewDoc.Save(output);
			return output.ToArray();
		}

		// ─── Toolbar Actions ────────────────────────────────────────────────

		private async void BtnAdd_Click(object sender, RoutedEventArgs e)
		{
			var ofd = new Microsoft.Win32.OpenFileDialog
			{
				Filter = "PDF Files|*.pdf",
				Multiselect = true,
				Title = L10n.T("dlg_add_pdf")
			};

			if (ofd.ShowDialog() == true)
			{
				await AddPdfFilesAsync(ofd.FileNames.ToList(), false);
			}
		}

		private void BtnRemove_Click(object sender, RoutedEventArgs e)
		{
			var selected = lstPages.SelectedItems.Cast<PdfPageViewModel>().ToList();
			if (selected.Count == 0) return;

			// Ghi lại index trước khi xóa để chọn lại trang hợp lệ sau đó
			int firstSelectedIndex = lstPages.SelectedIndex;

			_isReordering = true;
			try
			{
				foreach (var item in selected)
					_pages.Remove(item);

				RefreshSequenceNumbers();

				// ═══ FIX: sau khi xoá, chọn trang gần nhất (tránh preview kẹt) ═══
				if (_pages.Count > 0)
				{
					int newIndex = Math.Min(firstSelectedIndex, _pages.Count - 1);
					lstPages.SelectedIndex = newIndex;
				}
				else
				{
					// Không còn trang nào → clear preview
					var oldDoc = _pdfViewer.Document;
					_pdfViewer.Document = null;
					oldDoc?.Dispose();
					txtNoPreview.Visibility = Visibility.Visible;
					UpdateZoomControls();
				}
			}
			finally
			{
				_isReordering = false;
				if (_pages.Count > 0)
					LstPages_SelectionChanged(lstPages, null);
			}
		}

		private void BtnUp_Click(object sender, RoutedEventArgs e) => MoveSelectedItems(-1);
		private void BtnDown_Click(object sender, RoutedEventArgs e) => MoveSelectedItems(1);

		private void BtnRotate_Click(object sender, RoutedEventArgs e)
		{
			var selected = lstPages.SelectedItems.Cast<PdfPageViewModel>().ToList();
			if (selected.Count == 0) return;

			foreach (var item in selected)
			{
				item.RotationDelta = (item.RotationDelta + 90) % 360;
				item.PreviewData = null;
			}

			// Force refresh preview if a rotated item is currently viewed
			LstPages_SelectionChanged(lstPages, null);
		}

		private void MoveSelectedItems(int direction)
		{
			var selectedIndices = new List<int>();
			foreach (var item in lstPages.SelectedItems)
			{
				int idx = _pages.IndexOf((PdfPageViewModel)item);
				if (idx >= 0) selectedIndices.Add(idx);
			}
			if (selectedIndices.Count == 0) return;

			selectedIndices.Sort();

			if (direction == -1 && selectedIndices[0] == 0) return;
			if (direction == 1 && selectedIndices[selectedIndices.Count - 1] == _pages.Count - 1) return;

			// Di chuyển theo thứ tự phù hợp
			if (direction == 1) selectedIndices.Reverse();

			_isReordering = true;
			try
			{
				var newIndices = new List<int>();
				foreach (int idx in selectedIndices)
				{
					int newIdx = idx + direction;
					_pages.Move(idx, newIdx);
					newIndices.Add(newIdx);
				}

				RefreshSequenceNumbers();

				// Giữ lại selection
				lstPages.SelectedItems.Clear();
				foreach (int idx in newIndices)
					lstPages.SelectedItems.Add(_pages[idx]);
			}
			finally
			{
				_isReordering = false;
				LstPages_SelectionChanged(lstPages, null);
			}
		}

		private void BtnPlusPlot_Click(object sender, RoutedEventArgs e)
		{
			this.Hide();
			if (Commands.MainFormInstance != null)
			{
				Commands.MainFormInstance.SetSubPlotMode(true);
				Commands.MainFormInstance.Show();
			}
		}

		// ─── Save with Progress Bar (async — không block UI) ────────────────
		private async void BtnSave_Click(object sender, RoutedEventArgs e)
		{
			if (_pages.Count == 0) return;

			var sfd = new Microsoft.Win32.SaveFileDialog
			{
				Filter = "PDF File|*.pdf",
				Title = L10n.T("dlg_save_pdf"),
				FileName = txtFileName.Text
			};

			if (sfd.ShowDialog() != true) return;

			string savePath = sfd.FileName;

			// Hiện progress bar và disable buttons
			pnlProgress.Visibility = Visibility.Visible;
			pnlProgress.Value = 0;
			pnlProgress.Label = L10n.T("prog_merging");
			pnlProgress.Percent = "0%";
			btnSave.IsEnabled = false;
			btnCancel.IsEnabled = false;

			// Snapshot dữ liệu cần thiết từ UI thread trước khi vào background
			var pageSnapshots = _pages
				.Select(p => new { p.SourceFile, p.PageIndex, p.RotationDelta })
				.ToList();

			try
			{
				int total = pageSnapshots.Count;

				// Heavy I/O chạy trên background thread
				await Task.Run(() =>
				{
					var inputDocs = new Dictionary<string, PdfSharp.Pdf.PdfDocument>(StringComparer.OrdinalIgnoreCase);
					var remainingSourceUses = pageSnapshots
						.GroupBy(item => item.SourceFile, StringComparer.OrdinalIgnoreCase)
						.ToDictionary(group => group.Key, group => group.Count(), StringComparer.OrdinalIgnoreCase);
					using var outDoc = new PdfSharp.Pdf.PdfDocument();
					try
					{
						int lastReportedPercent = -1;
						for (int i = 0; i < total; i++)
						{
							var item = pageSnapshots[i];
							if (!inputDocs.TryGetValue(item.SourceFile, out PdfSharp.Pdf.PdfDocument inDoc))
							{
								inDoc = PdfReader.Open(item.SourceFile, PdfDocumentOpenMode.Import);
								inputDocs[item.SourceFile] = inDoc;
							}

							if (item.PageIndex == -1)
							{
								for (int p = 0; p < inDoc.PageCount; p++)
								{
									var newPage = outDoc.AddPage(inDoc.Pages[p]);
									if (item.RotationDelta != 0) newPage.Rotate = (newPage.Rotate + item.RotationDelta) % 360;
								}
							}
							else
							{
								var newPage = outDoc.AddPage(inDoc.Pages[item.PageIndex]);
								if (item.RotationDelta != 0) newPage.Rotate = (newPage.Rotate + item.RotationDelta) % 360;
							}

							if (--remainingSourceUses[item.SourceFile] == 0)
							{
								inDoc.Dispose();
								inputDocs.Remove(item.SourceFile);
							}

							// Avoid flooding the UI dispatcher when saving hundreds of pages.
							int percent = (int)((double)(i + 1) / total * 100);
							if (percent != lastReportedPercent)
							{
								lastReportedPercent = percent;
								int currentIndex = i;
								Dispatcher.InvokeAsync(() =>
								{
									pnlProgress.Value = percent;
									pnlProgress.Percent = $"{percent}%";
									pnlProgress.Label = string.Format(L10n.T("prog_progress"), currentIndex + 1, total);
								});
							}
						}
					}
					finally
					{
						foreach (var inputDoc in inputDocs.Values)
							inputDoc.Dispose();
					}

					// Release all source file handles before overwriting a selected input path.
					outDoc.Save(savePath);
				});

				// Hoàn tất — trở lại UI thread
				pnlProgress.Value = 100;
				pnlProgress.Percent = "100%";
				pnlProgress.Label = "✅ " + L10n.T("msg_save_success");

				try { System.Diagnostics.Process.Start(savePath); } catch { }
			}
			catch (Exception ex)
			{
				MessageBox.Show(
					string.Format(L10n.T("msg_save_error"), ex.Message),
					L10n.T("err_title"),
					MessageBoxButton.OK, MessageBoxImage.Error);
			}
			finally
			{
				btnSave.IsEnabled = true;
				btnCancel.IsEnabled = true;
				// Ẩn progress bar sau 2 giây
				var timer = new System.Windows.Threading.DispatcherTimer { Interval = TimeSpan.FromSeconds(2) };
				timer.Tick += (s2, e2) =>
				{
					pnlProgress.Visibility = Visibility.Collapsed;
					timer.Stop();
				};
				timer.Start();
			}
		}

		private void BtnCancel_Click(object sender, RoutedEventArgs e) => Close();

		// ─── Multi-item Drag & Drop with Drop Indicator ────────────────────

		private void LstPages_PreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
		{
			_isDragging = false;
			_dragStartItem = null;
			_collapseSelectionOnMouseUp = false;

			DependencyObject source = e.OriginalSource as DependencyObject;
			if (FindVisualAncestor<System.Windows.Controls.Primitives.ScrollBar>(source) != null)
				return;

			ListViewItem sourceContainer = FindVisualAncestor<ListViewItem>(source);
			if (sourceContainer?.Content is not PdfPageViewModel sourceItem)
				return;

			_dragStartPoint = e.GetPosition(lstPages);
			_dragStartItem = sourceItem;

			// Giữ multi-selection khi bắt đầu kéo một hàng đang được chọn. Nếu chỉ click,
			// selection sẽ được thu về hàng đó trong PreviewMouseLeftButtonUp.
			if (sourceContainer.IsSelected &&
				lstPages.SelectedItems.Count > 1 &&
				Keyboard.Modifiers == ModifierKeys.None)
			{
				_collapseSelectionOnMouseUp = true;
				sourceContainer.Focus();
				e.Handled = true;
			}
		}

		private void LstPages_PreviewMouseLeftButtonUp(object sender, MouseButtonEventArgs e)
		{
			if (_collapseSelectionOnMouseUp && !_isDragging && _dragStartItem != null)
			{
				lstPages.SelectedItems.Clear();
				lstPages.SelectedItem = _dragStartItem;
			}

			_dragStartItem = null;
			_collapseSelectionOnMouseUp = false;
		}

		private void LstPages_PreviewMouseMove(object sender, MouseEventArgs e)
		{
			if (_isDragging || _dragStartItem == null || e.LeftButton != MouseButtonState.Pressed)
				return;

			Point currentPos = e.GetPosition(lstPages);
			Vector diff = _dragStartPoint - currentPos;

			if (Math.Abs(diff.X) <= SystemParameters.MinimumHorizontalDragDistance &&
				Math.Abs(diff.Y) <= SystemParameters.MinimumVerticalDragDistance)
				return;

			if (!lstPages.SelectedItems.Contains(_dragStartItem))
			{
				lstPages.SelectedItems.Clear();
				lstPages.SelectedItem = _dragStartItem;
			}

			var selectedSet = new HashSet<PdfPageViewModel>(lstPages.SelectedItems.Cast<PdfPageViewModel>());
			var selectedItems = _pages.Where(selectedSet.Contains).ToList();
			if (selectedItems.Count == 0)
				return;

			_isDragging = true;
			_collapseSelectionOnMouseUp = false;
			try
			{
				var dragData = new DataObject(PdfPagesDataFormat, selectedItems);
				DragDrop.DoDragDrop(lstPages, dragData, DragDropEffects.Move);
			}
			finally
			{
				ClearDropIndicator();
				_isDragging = false;
				_dragStartItem = null;
			}
		}

		private void LstPages_DragOver(object sender, DragEventArgs e)
		{
			if (!e.Data.GetDataPresent(PdfPagesDataFormat) ||
				e.Data.GetData(PdfPagesDataFormat) is not List<PdfPageViewModel>)
			{
				e.Effects = DragDropEffects.None;
				ClearDropIndicator();
				e.Handled = true;
				return;
			}

			DependencyObject source = e.OriginalSource as DependencyObject;
			if (FindVisualAncestor<System.Windows.Controls.Primitives.ScrollBar>(source) != null ||
				FindVisualAncestor<GridViewColumnHeader>(source) != null)
			{
				e.Effects = DragDropEffects.None;
				ClearDropIndicator();
				e.Handled = true;
				return;
			}

			AutoScrollPageList(e.GetPosition(lstPages));

			if (TryGetDropPosition(e, out int insertIndex, out double indicatorY))
			{
				e.Effects = DragDropEffects.Move;
				ShowDropIndicator(insertIndex, indicatorY);
			}
			else
			{
				e.Effects = DragDropEffects.None;
				ClearDropIndicator();
			}

			e.Handled = true;
		}

		private bool TryGetDropPosition(DragEventArgs e, out int insertIndex, out double indicatorY)
		{
			insertIndex = -1;
			indicatorY = 0;

			ListViewItem targetContainer = FindVisualAncestor<ListViewItem>(e.OriginalSource as DependencyObject);
			if (targetContainer?.Content is PdfPageViewModel targetItem)
			{
				int targetIndex = _pages.IndexOf(targetItem);
				if (targetIndex < 0)
					return false;

				bool insertBefore = e.GetPosition(targetContainer).Y < targetContainer.ActualHeight / 2;
				Point topLeft = targetContainer.TranslatePoint(new Point(0, 0), lstPages);
				insertIndex = insertBefore ? targetIndex : targetIndex + 1;
				indicatorY = insertBefore ? topLeft.Y : topLeft.Y + targetContainer.ActualHeight;
				return true;
			}

			if (_pages.Count == 0)
				return false;

			var lastContainer = lstPages.ItemContainerGenerator.ContainerFromIndex(_pages.Count - 1) as ListViewItem;
			if (lastContainer == null)
				return false;

			Point lastTopLeft = lastContainer.TranslatePoint(new Point(0, 0), lstPages);
			double lastBottom = lastTopLeft.Y + lastContainer.ActualHeight;
			if (e.GetPosition(lstPages).Y < lastBottom)
				return false;

			insertIndex = _pages.Count;
			indicatorY = lastBottom;
			return true;
		}

		private void ShowDropIndicator(int insertIndex, double indicatorY)
		{
			_dropInsertIndex = insertIndex;
			AdornerLayer adornerLayer = AdornerLayer.GetAdornerLayer(lstPages);
			if (adornerLayer == null)
				return;

			if (_dropInsertionAdorner == null)
			{
				_dropInsertionAdorner = new DropInsertionAdorner(lstPages);
				adornerLayer.Add(_dropInsertionAdorner);
			}

			_dropInsertionAdorner.UpdatePosition(indicatorY);
		}

		private void ClearDropIndicator()
		{
			_dropInsertIndex = -1;
			if (_dropInsertionAdorner == null)
				return;

			AdornerLayer.GetAdornerLayer(lstPages)?.Remove(_dropInsertionAdorner);
			_dropInsertionAdorner = null;
		}

		private void LstPages_DragLeave(object sender, DragEventArgs e)
		{
			ClearDropIndicator();
		}

		private void LstPages_SizeChanged(object sender, SizeChangedEventArgs e)
		{
			UpdatePageColumnWidth();
		}

		private void AutoScrollPageList(Point pointerPosition)
		{
			bool scrollUp = pointerPosition.Y < AutoScrollBoundary;
			bool scrollDown = pointerPosition.Y > lstPages.ActualHeight - AutoScrollBoundary;
			if (!scrollUp && !scrollDown)
				return;

			DateTime now = DateTime.UtcNow;
			if (now - _lastAutoScrollUtc < AutoScrollInterval)
				return;

			_pageListScrollViewer ??= FindVisualDescendant<ScrollViewer>(lstPages);
			if (_pageListScrollViewer == null)
				return;

			if (scrollUp)
				_pageListScrollViewer.LineUp();
			else
				_pageListScrollViewer.LineDown();

			_lastAutoScrollUtc = now;
		}

		private void LstPages_Drop(object sender, DragEventArgs e)
		{
			int requestedInsertIndex = _dropInsertIndex;
			ClearDropIndicator();
			e.Handled = true;

			if (requestedInsertIndex < 0 ||
				!e.Data.GetDataPresent(PdfPagesDataFormat) ||
				e.Data.GetData(PdfPagesDataFormat) is not List<PdfPageViewModel> droppedItems ||
				droppedItems.Count == 0)
				return;

			var currentItems = new HashSet<PdfPageViewModel>(_pages);
			var droppedSet = new HashSet<PdfPageViewModel>(droppedItems.Where(currentItems.Contains));
			var orderedDroppedItems = _pages.Where(droppedSet.Contains).ToList();
			if (orderedDroppedItems.Count == 0)
				return;

			requestedInsertIndex = Math.Max(0, Math.Min(requestedInsertIndex, _pages.Count));
			int removedBeforeInsert = _pages.Take(requestedInsertIndex).Count(droppedSet.Contains);
			int dropIndex = requestedInsertIndex - removedBeforeInsert;

			var reorderedItems = _pages.Where(item => !droppedSet.Contains(item)).ToList();
			dropIndex = Math.Max(0, Math.Min(dropIndex, reorderedItems.Count));
			reorderedItems.InsertRange(dropIndex, orderedDroppedItems);

			if (_pages.SequenceEqual(reorderedItems))
				return;

			_isReordering = true;
			try
			{
				foreach (var item in orderedDroppedItems)
					_pages.Remove(item);

				for (int i = 0; i < orderedDroppedItems.Count; i++)
					_pages.Insert(dropIndex + i, orderedDroppedItems[i]);

				RefreshSequenceNumbers();

				lstPages.SelectedItems.Clear();
				foreach (var item in orderedDroppedItems)
					lstPages.SelectedItems.Add(item);

				lstPages.ScrollIntoView(orderedDroppedItems[0]);
			}
			finally
			{
				_isReordering = false;
				LstPages_SelectionChanged(lstPages, null);
			}
		}

		private static T FindVisualAncestor<T>(DependencyObject element) where T : DependencyObject
		{
			while (element != null)
			{
				if (element is T match)
					return match;

				element = VisualTreeHelper.GetParent(element);
			}

			return null;
		}

		private static T FindVisualDescendant<T>(DependencyObject element) where T : DependencyObject
		{
			if (element == null)
				return null;

			int childCount = VisualTreeHelper.GetChildrenCount(element);
			for (int i = 0; i < childCount; i++)
			{
				DependencyObject child = VisualTreeHelper.GetChild(element, i);
				if (child is T match)
					return match;

				T descendant = FindVisualDescendant<T>(child);
				if (descendant != null)
					return descendant;
			}

			return null;
		}

		private sealed class DropInsertionAdorner : Adorner
		{
			private static readonly Pen IndicatorPen = CreateIndicatorPen();
			private double _indicatorY;

			public DropInsertionAdorner(UIElement adornedElement)
				: base(adornedElement)
			{
				IsHitTestVisible = false;
			}

			public void UpdatePosition(double indicatorY)
			{
				_indicatorY = indicatorY;
				InvalidateVisual();
			}

			protected override void OnRender(DrawingContext drawingContext)
			{
				double width = Math.Max(0, AdornedElement.RenderSize.Width - 12);
				double y = Math.Max(0, Math.Min(_indicatorY, AdornedElement.RenderSize.Height));
				drawingContext.DrawLine(IndicatorPen, new Point(6, y), new Point(6 + width, y));
			}

			private static Pen CreateIndicatorPen()
			{
				var brush = new SolidColorBrush(Color.FromRgb(0x60, 0xA5, 0xFA));
				brush.Freeze();

				var pen = new Pen(brush, 3)
				{
					StartLineCap = PenLineCap.Triangle,
					EndLineCap = PenLineCap.Triangle
				};
				pen.Freeze();
				return pen;
			}
		}

		// ─── Helpers ────────────────────────────────────────────────────────

		/// <summary>Cập nhật cột STT cho toàn bộ danh sách.</summary>
		private void RefreshSequenceNumbers()
		{
			for (int i = 0; i < _pages.Count; i++)
				_pages[i].SequenceNumber = i + 1;
			AutoResizeSequenceColumn();
		}

		/// <summary>Tự động điều chỉnh chiều rộng các cột cho phù hợp với nội dung.</summary>
		private void AutoResizeSequenceColumn()
		{
			if (_pages.Count == 0) return;

			// Tính chiều rộng cần thiết dựa trên số chữ số lớn nhất (cột STT)
			int maxDigits = _pages.Count.ToString().Length;
			double needed = Math.Max(35, maxDigits * 8 + 10);

			if (lstPages.View is GridView gridView && gridView.Columns.Count > 0)
			{
				// Thay đổi chiều rộng cột #
				gridView.Columns[0].Width = needed;
			}

			UpdatePageColumnWidth();
		}

		private void UpdatePageColumnWidth()
		{
			if (lstPages.ActualWidth <= 0 ||
				lstPages.View is not GridView gridView ||
				gridView.Columns.Count < 4)
				return;

			double fixedColumnsWidth = 0;
			for (int i = 0; i < 3; i++)
				fixedColumnsWidth += gridView.Columns[i].ActualWidth;

			double reservedWidth = SystemParameters.VerticalScrollBarWidth + 8;
			double availableWidth = lstPages.ActualWidth - fixedColumnsWidth - reservedWidth;
			gridView.Columns[3].Width = Math.Max(90, availableWidth);
		}

		/// <summary>Tạo màu pastel theo golden angle để phân biệt nhóm PDF.</summary>
		private System.Drawing.Color GetNextColor()
		{
			double hue = (_colorIndex * 137.508) % 360.0;
			_colorIndex++;
			return HslToRgb(hue, 0.4, 0.85);
		}

		private System.Drawing.Color HslToRgb(double h, double s, double l)
		{
			double c = (1.0 - Math.Abs(2.0 * l - 1.0)) * s;
			double x = c * (1.0 - Math.Abs((h / 60.0) % 2.0 - 1.0));
			double m = l - c / 2.0;

			double r = 0, g = 0, b = 0;
			if (h < 60) { r = c; g = x; }
			else if (h < 120) { r = x; g = c; }
			else if (h < 180) { g = c; b = x; }
			else if (h < 240) { g = x; b = c; }
			else if (h < 300) { r = x; b = c; }
			else { r = c; b = x; }

			return System.Drawing.Color.FromArgb(
				(int)((r + m) * 255),
				(int)((g + m) * 255),
				(int)((b + m) * 255));
		}

		// ─── Window Lifecycle ───────────────────────────────────────────────

		protected override void OnClosing(CancelEventArgs e)
		{
			// Đánh dấu đang đóng — ngăn Instance getter tạo lại trong lúc cleanup
			_isClosing = true;
			ClearDropIndicator();
			_previewRequestId++;
			_loadCancellation.Cancel();
			base.OnClosing(e);
		}

		protected override void OnClosed(EventArgs e)
		{
			// Cleanup PDF viewer
			try
			{
				if (_hwndSource != null)
				{
					_hwndSource.RemoveHook(HwndHook);
					_hwndSource = null;
				}
				_pdfViewer.Renderer.HandleCreated -= PdfRenderer_HandleCreated;
				_pdfViewer.Renderer.ZoomChanged -= PdfRenderer_ZoomChanged;
				var oldDoc = _pdfViewer?.Document;
				if (_pdfViewer != null) _pdfViewer.Document = null;
				oldDoc?.Dispose();
				_currentPreviewStream?.Dispose();
				_currentPreviewStream = null;
			}
			catch (Exception ex)
			{
				System.Diagnostics.Debug.WriteLine($"[PdfEditor] Preview cleanup error: {ex.Message}");
			}

			// Xoá file tạm
			foreach (string file in _autoGeneratedFiles)
			{
				try { if (File.Exists(file)) File.Delete(file); } catch { }
			}
			_autoGeneratedFiles.Clear();
			_colorIndex = 0;
			_groupIdCounter = 0;
			_pages.Clear();
			_instance = null;

			// Trở về MainForm
			if (Commands.MainFormInstance != null)
			{
				Commands.MainFormInstance.SetSubPlotMode(false);
				Commands.MainFormInstance.Show();
			}

			base.OnClosed(e);
		}

		[DllImport("user32.dll")]
		private static extern IntPtr MonitorFromWindow(IntPtr windowHandle, uint flags);

		[DllImport("user32.dll", CharSet = CharSet.Auto)]
		[return: MarshalAs(UnmanagedType.Bool)]
		private static extern bool GetMonitorInfo(IntPtr monitorHandle, ref MonitorInfo monitorInfo);

		[DllImport("uxtheme.dll", CharSet = CharSet.Unicode)]
		private static extern int SetWindowTheme(IntPtr windowHandle, string subAppName, string subIdList);

		[StructLayout(LayoutKind.Sequential)]
		private struct NativePoint
		{
			public int X;
			public int Y;
		}

		[StructLayout(LayoutKind.Sequential)]
		private struct MinMaxInfo
		{
			public NativePoint Reserved;
			public NativePoint MaxSize;
			public NativePoint MaxPosition;
			public NativePoint MinTrackSize;
			public NativePoint MaxTrackSize;
		}

		[StructLayout(LayoutKind.Sequential)]
		private struct NativeRectangle
		{
			public int Left;
			public int Top;
			public int Right;
			public int Bottom;
		}

		[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Auto)]
		private struct MonitorInfo
		{
			public int Size;
			public NativeRectangle MonitorArea;
			public NativeRectangle WorkArea;
			public uint Flags;
		}
	}

}

