using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Interop;
using System.Windows.Media;
using PdfiumViewer;
using Point = System.Windows.Point;

namespace TPL
{
	/// <summary>
	/// Model cho mỗi trang PDF trong danh sách.
	/// Implements INotifyPropertyChanged để cập nhật STT khi thay đổi vị trí.
	/// </summary>
	public class PdfPageViewModel : INotifyPropertyChanged
	{
		private int _sequenceNumber;

		public string SourceFile { get; set; }
		public int PageIndex { get; set; }
		public int RotationDelta { get; set; } = 0;
		public System.Drawing.Color GroupColor { get; set; }
		public string DisplayName { get; set; }

		/// <summary>Lazy preview cache. Populated only after the page is selected.</summary>
		public byte[] PreviewData { get; set; }

		/// <summary>Nhãn nguồn gốc: "Plot" cho xuất từ AutoCAD, "File" cho thêm từ file.</summary>
		public string SourceLabel { get; set; } = "Plot";

		/// <summary>Mã nhóm để nhận diện batch (mỗi lần Plot hoặc Add file là 1 group).</summary>
		public int GroupId { get; set; }

		public int SequenceNumber
		{
			get => _sequenceNumber;
			set { _sequenceNumber = value; OnPropertyChanged(nameof(SequenceNumber)); }
		}

		/// <summary>Brush WPF dùng để hiển thị color indicator trong ListView.</summary>
		private SolidColorBrush _groupColorBrush;
		public SolidColorBrush GroupColorBrush =>
			_groupColorBrush ??= new(Color.FromArgb(GroupColor.A, GroupColor.R, GroupColor.G, GroupColor.B));

		/// <summary>Màu nền nhạt (~18% opacity) để phân biệt rõ các nhóm PDF khác nhau.</summary>
		private SolidColorBrush _rowBackgroundColorBrush;
		public SolidColorBrush RowBackgroundColorBrush =>
			_rowBackgroundColorBrush ??= new(Color.FromArgb(45, GroupColor.R, GroupColor.G, GroupColor.B));

		/// <summary>Màu nền khi hover — giữ tint nhóm + tăng sáng nhẹ.</summary>
		private SolidColorBrush _hoverBackgroundBrush;
		public SolidColorBrush HoverBackgroundBrush =>
			_hoverBackgroundBrush ??= new(Color.FromArgb(70, GroupColor.R, GroupColor.G, GroupColor.B));

		/// <summary>Màu nền khi selected — blend accent blue + tint nhóm.</summary>
		private SolidColorBrush _selectedBackgroundBrush;
		public SolidColorBrush SelectedBackgroundBrush
		{
			get
			{
				if (_selectedBackgroundBrush != null) return _selectedBackgroundBrush;
				// Blend group color với accent blue (#2563EB), ratio 40/60
				byte r = (byte)((GroupColor.R * 0.4) + (0x25 * 0.6));
				byte g = (byte)((GroupColor.G * 0.4) + (0x63 * 0.6));
				byte b = (byte)((GroupColor.B * 0.4) + (0xEB * 0.6));
				_selectedBackgroundBrush = new SolidColorBrush(Color.FromArgb(50, r, g, b));
				return _selectedBackgroundBrush;
			}
		}

		public event PropertyChangedEventHandler PropertyChanged;
		protected void OnPropertyChanged(string name) =>
			PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
	}

	/// <summary>
	/// PDF Editor WPF Window — thay thế PdfEditorForm (WinForms).
	/// Tính năng: STT column, multi-drag-drop reorder, progress bar khi save,
	/// fix preview kẹt khi remove, dark theme #181A1F, custom scrollbar.
	/// </summary>
	public partial class PdfEditorWindow : Window
	{
		// ─── Singleton ──────────────────────────────────────────────────────
		private static PdfEditorWindow _instance;
		private bool _isClosing = false;
		public static PdfEditorWindow Instance
		{
			get
			{
				if (_instance == null || _instance._isClosing || !_instance.IsLoaded)
					_instance = new PdfEditorWindow();
				return _instance;
			}
		}

		// ─── Data ───────────────────────────────────────────────────────────
		private readonly ObservableCollection<PdfPageViewModel> _pages = new();
		private int _colorIndex = 0;
		private int _groupIdCounter = 0;
		private readonly List<string> _autoGeneratedFiles = new();
		private readonly SemaphoreSlim _pdfLoadGate = new(1, 1);
		private readonly CancellationTokenSource _loadCancellation = new();
		private readonly Stack<List<PdfPageViewModel>> _undoStack = new();
		private readonly Stack<List<PdfPageViewModel>> _redoStack = new();
		private string _currentFilePath;
		private bool _isDirty;
		private bool _forceClose;
		private bool _isBusy;
		private bool _isLoading;
		private bool _isDashboardVisible = true;
		private bool _isSpecializedToolVisible;
		private string _activeToolName = "Edit PDF";

		// Drag-drop state
		private const string PdfPagesDataFormat = "TPL.PdfPages";
		private const double AutoScrollBoundary = 28;
		private static readonly TimeSpan AutoScrollInterval = TimeSpan.FromMilliseconds(50);
		private Point _dragStartPoint;
		private PdfPageViewModel _dragStartItem;
		private bool _collapseSelectionOnMouseUp;
		private bool _isDragging;
		private int _dropInsertIndex = -1;
		private DateTime _lastAutoScrollUtc = DateTime.MinValue;
		private ScrollViewer _pageListScrollViewer;
		private DropInsertionAdorner _dropInsertionAdorner;

		// PDF Viewer (WinForms control hosted via WindowsFormsHost)
		private static readonly int[] StandardZoomPercentages =
		{
			10, 25, 50, 75, 100, 125, 150, 200, 250, 300, 400, 500
		};
		private readonly ObservableCollection<int> _zoomPercentOptions = new(StandardZoomPercentages);
		private readonly PdfViewer _pdfViewer;
		private MemoryStream _currentPreviewStream;
		private int _previewRequestId;
		private int? _customZoomPercentage;
		private bool _isUpdatingZoomSelection;
		private HwndSource _hwndSource;

		// ─── Constructor ────────────────────────────────────────────────────
		private PdfEditorWindow()
		{
			InitializeComponent();

			// Tạo PdfViewer (WinForms) và host trong WPF
			_pdfViewer = new PdfViewer
			{
				ShowToolbar = false,
				ShowBookmarks = false,
				Dock = System.Windows.Forms.DockStyle.Fill,
				BackColor = System.Drawing.Color.FromArgb(0x18, 0x1A, 0x1F)
			};
			_pdfViewer.Renderer.BackColor = System.Drawing.Color.FromArgb(0x18, 0x1A, 0x1F);
			_pdfViewer.Renderer.MouseWheelMode = MouseWheelMode.Zoom;
			_pdfViewer.Renderer.ZoomChanged += PdfRenderer_ZoomChanged;
			_pdfViewer.Renderer.HandleCreated += PdfRenderer_HandleCreated;
			cmbZoomPercent.ItemsSource = _zoomPercentOptions;
			pdfHost.Child = _pdfViewer;
			UpdateZoomControls();
			UpdateWindowStateVisual();

			lstPages.ItemsSource = _pages;

			this.SourceInitialized += PdfEditorWindow_SourceInitialized;
		}

		// ─── Resize Flicker Fix ─────────────────────────────────────────────
		private void PdfEditorWindow_SourceInitialized(object sender, EventArgs e)
		{
			_hwndSource = PresentationSource.FromVisual(this) as HwndSource;
			_hwndSource?.AddHook(HwndHook);
		}

		private const int WM_GETMINMAXINFO = 0x0024;
		private const int WM_ENTERSIZEMOVE = 0x0231;
		private const int WM_EXITSIZEMOVE = 0x0232;
		private const uint MONITOR_DEFAULTTONEAREST = 0x00000002;

		private IntPtr HwndHook(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
		{
			try
			{
				if (msg == WM_GETMINMAXINFO)
				{
					ApplyWindowSizeConstraints(hwnd, lParam);
					handled = true;
				}
				else if (msg == WM_ENTERSIZEMOVE)
				{
					// Ẩn WinFormsHost khi bắt đầu co kéo để chống nhấp nháy (airspace flicker)
					pdfHost.Visibility = Visibility.Hidden;
				}
				else if (msg == WM_EXITSIZEMOVE)
				{
					// Hiện lại khi thả chuột hoàn tất co kéo
					pdfHost.Visibility = _pdfViewer.Document != null
						? Visibility.Visible
						: Visibility.Collapsed;
				}
			}
			catch (Exception ex)
			{
				System.Diagnostics.Debug.WriteLine($"[PdfEditor] Window message error: {ex.Message}");
			}

			return IntPtr.Zero;
		}

		private void ApplyWindowSizeConstraints(IntPtr hwnd, IntPtr minMaxInfoPointer)
		{
			if (minMaxInfoPointer == IntPtr.Zero)
				return;

			IntPtr monitor = MonitorFromWindow(hwnd, MONITOR_DEFAULTTONEAREST);
			if (monitor == IntPtr.Zero)
				return;

			var monitorInfo = new MonitorInfo
			{
				Size = Marshal.SizeOf<MonitorInfo>()
			};
			if (!GetMonitorInfo(monitor, ref monitorInfo))
				return;

			MinMaxInfo minMaxInfo = Marshal.PtrToStructure<MinMaxInfo>(minMaxInfoPointer);
			minMaxInfo.MaxPosition.X = monitorInfo.WorkArea.Left - monitorInfo.MonitorArea.Left;
			minMaxInfo.MaxPosition.Y = monitorInfo.WorkArea.Top - monitorInfo.MonitorArea.Top;
			minMaxInfo.MaxSize.X = monitorInfo.WorkArea.Right - monitorInfo.WorkArea.Left;
			minMaxInfo.MaxSize.Y = monitorInfo.WorkArea.Bottom - monitorInfo.WorkArea.Top;

			// WM_GETMINMAXINFO uses physical pixels, while WPF MinWidth/MinHeight use DIPs.
			// Preserve the XAML minimum size on the current monitor so the preview toolbar
			// and footer buttons cannot be clipped by native window resizing.
			double scaleX = 1.0;
			double scaleY = 1.0;
			if (_hwndSource?.CompositionTarget != null)
			{
				Matrix transformToDevice = _hwndSource.CompositionTarget.TransformToDevice;
				scaleX = transformToDevice.M11;
				scaleY = transformToDevice.M22;
			}

			minMaxInfo.MinTrackSize.X = Math.Max(
				minMaxInfo.MinTrackSize.X,
				(int)Math.Ceiling(MinWidth * scaleX));
			minMaxInfo.MinTrackSize.Y = Math.Max(
				minMaxInfo.MinTrackSize.Y,
				(int)Math.Ceiling(MinHeight * scaleY));
			Marshal.StructureToPtr(minMaxInfo, minMaxInfoPointer, false);
		}

		private void PdfRenderer_HandleCreated(object sender, EventArgs e)
		{
			ApplyPdfPreviewTheme();
		}

		private void ApplyPdfPreviewTheme()
		{
			try
			{
				PdfRenderer renderer = _pdfViewer.Renderer;
				if (!renderer.IsHandleCreated)
					return;

				int result = SetWindowTheme(renderer.Handle, "DarkMode_Explorer", null);
				if (result < 0)
					System.Diagnostics.Debug.WriteLine($"[PdfEditor] Native scrollbar theme returned 0x{result:X8}.");
			}
			catch (Exception ex)
			{
				System.Diagnostics.Debug.WriteLine($"[PdfEditor] Preview theme error: {ex.Message}");
			}
		}

		// ─── Public API ─────────────────────────────────────────────────────

		public async Task InitializeAsync(
			IReadOnlyList<string> files,
			string defaultFileName,
			bool deleteSourcesOnExit)
		{
			SetDefaultFileName(defaultFileName);
			chkSeparatePdfs.IsChecked = true;

			if (files != null && files.Count > 0)
			{
				await AddPdfFilesAsync(files, deleteSourcesOnExit, trackHistory: false);
				if (_pages.Count == 0)
					throw new InvalidDataException("None of the requested PDF files could be opened.");
				if (!deleteSourcesOnExit && files.Count == 1)
				{
					_currentFilePath = Path.GetFullPath(files[0]);
					_isDirty = false;
				}
				else
				{
					_isDirty = _pages.Count > 0;
				}

				ShowEditorWorkspace("Edit PDF");
			}
			else
			{
				ShowToolsDashboard();
			}

			UpdateDocumentState();
		}

		private void ShowToolsDashboard()
		{
			_isDashboardVisible = true;
			_isSpecializedToolVisible = false;
			documentCommandBar.Visibility = Visibility.Collapsed;
			editorWorkspace.Visibility = Visibility.Collapsed;
			editorFooter.Visibility = Visibility.Collapsed;
			specializedToolWorkspace.Visibility = Visibility.Collapsed;
			toolsDashboard.Visibility = Visibility.Visible;
			txtTitle.Text = "TPL PDF Editor";
		}

		private void ShowEditorWorkspace(string toolName)
		{
			_isDashboardVisible = false;
			_isSpecializedToolVisible = false;
			_activeToolName = string.IsNullOrWhiteSpace(toolName) ? "Edit PDF" : toolName;
			toolsDashboard.Visibility = Visibility.Collapsed;
			specializedToolWorkspace.Visibility = Visibility.Collapsed;
			documentCommandBar.Visibility = Visibility.Visible;
			editorWorkspace.Visibility = Visibility.Visible;
			editorFooter.Visibility = Visibility.Visible;
			UpdateDocumentState();
		}

		private void ShowSpecializedToolWorkspace(PdfToolAction action, string toolName)
		{
			_isDashboardVisible = false;
			_isSpecializedToolVisible = true;
			_activeToolName = toolName;
			toolsDashboard.Visibility = Visibility.Collapsed;
			documentCommandBar.Visibility = Visibility.Collapsed;
			editorWorkspace.Visibility = Visibility.Collapsed;
			editorFooter.Visibility = Visibility.Collapsed;
			specializedToolWorkspace.Visibility = Visibility.Visible;
			specializedToolWorkspace.OpenTool(action);
			txtTitle.Text = $"TPL PDF Editor - {toolName}";
		}

		/// <summary>Thêm danh sách file PDF vào editor (async — không block UI).</summary>
		public async Task AddPdfFilesAsync(
			IReadOnlyList<string> files,
			bool isAutoGenerated = true,
			bool trackHistory = true)
		{
			if (files == null || files.Count == 0) return;
			try
			{
				await _pdfLoadGate.WaitAsync(_loadCancellation.Token);
			}
			catch (OperationCanceledException)
			{
				return;
			}

			try
			{
				if (_isClosing || _loadCancellation.IsCancellationRequested) return;
				List<PdfPageViewModel> undoSnapshot = trackHistory ? CapturePages() : null;
				int originalPageCount = _pages.Count;
				if (isAutoGenerated) _autoGeneratedFiles.AddRange(files);

				System.Drawing.Color groupColor = GetNextColor();
				int currentGroupId = _groupIdCounter++;
				string sourceLabel = isAutoGenerated ? "Plot" : "File";
				bool firstAdd = _pages.Count == 0;
				bool separate = chkSeparatePdfs.IsChecked == true;
				CancellationToken cancellationToken = _loadCancellation.Token;

				SetLoading(true);

				try
				{
					// Heavy I/O chạy trên background thread
					var loadedPages = await Task.Run(() =>
					{
						var results = new List<PdfPageViewModel>();
						foreach (string file in files)
						{
							cancellationToken.ThrowIfCancellationRequested();
							if (!File.Exists(file)) continue;
							try
							{
								int pageCount = PdfDocumentService.GetPageCount(file);

								if (separate || isAutoGenerated)
								{
									for (int i = 0; i < pageCount; i++)
									{
										cancellationToken.ThrowIfCancellationRequested();
										results.Add(new PdfPageViewModel
										{
											SourceFile = file,
											PageIndex = i,
											GroupColor = groupColor,
											GroupId = currentGroupId,
											SourceLabel = sourceLabel,
											DisplayName = isAutoGenerated
												? Path.GetFileName(file)
												: string.Format(L10n.T("page_name"), Path.GetFileName(file), i + 1)
										});
									}
								}
								else
								{
									results.Add(new PdfPageViewModel
									{
										SourceFile = file,
										PageIndex = -1,
										GroupColor = groupColor,
										GroupId = currentGroupId,
										SourceLabel = sourceLabel,
										DisplayName = Path.GetFileName(file)
									});
								}
							}
							catch (OperationCanceledException)
							{
								throw;
							}
							catch (Exception ex)
							{
								System.Diagnostics.Debug.WriteLine($"[PdfEditor] Error loading {file}: {ex.Message}");
							}
						}
						return results;
					}, cancellationToken);

					if (_isClosing || cancellationToken.IsCancellationRequested) return;
					if (trackHistory && loadedPages.Count == 0)
					{
						MessageBox.Show(
							"No PDF pages were added. The selected files may be missing, encrypted, or invalid.",
							"TPL PDF Editor",
							MessageBoxButton.OK,
							MessageBoxImage.Warning);
					}

					// Add vào ObservableCollection trên UI thread
					foreach (var page in loadedPages)
					{
						page.SequenceNumber = _pages.Count + 1;
						_pages.Add(page);
					}

					AutoResizeSequenceColumn();

					if (firstAdd && _pages.Count > 0)
						lstPages.SelectedIndex = 0;

					if (trackHistory && _pages.Count > originalPageCount)
					{
						PushUndoSnapshot(undoSnapshot);
						MarkDirty();
					}
					UpdateDocumentState();
				}
				catch (OperationCanceledException) when (_loadCancellation.IsCancellationRequested)
				{
					// Expected when the window is closing.
				}
				catch (Exception ex)
				{
					System.Diagnostics.Debug.WriteLine($"[PdfEditor] AddPdfFiles error: {ex.Message}");
				}
				finally
				{
					if (!_isClosing)
						SetLoading(false);
				}
			}
			finally
			{
				_pdfLoadGate.Release();
				if (_isClosing && isAutoGenerated)
				{
					foreach (string file in files)
					{
						if (!string.Equals(Path.GetExtension(file), ".pdf", StringComparison.OrdinalIgnoreCase))
						{
							System.Diagnostics.Debug.WriteLine($"[PdfEditor] Refusing closing cleanup for non-PDF path '{file}'.");
							continue;
						}
						try
						{
							if (File.Exists(file)) File.Delete(file);
						}
						catch (IOException ex)
						{
							System.Diagnostics.Debug.WriteLine($"[PdfEditor] Closing cleanup failed for '{file}': {ex.Message}");
						}
						catch (UnauthorizedAccessException ex)
						{
							System.Diagnostics.Debug.WriteLine($"[PdfEditor] Closing cleanup failed for '{file}': {ex.Message}");
						}
					}
				}
			}
		}

		/// <summary>Đặt tên file mặc định (chỉ khi trống).</summary>
		public void SetDefaultFileName(string name)
		{
			if (string.IsNullOrEmpty(txtFileName.Text))
				txtFileName.Text = name;
		}

		private List<PdfPageViewModel> CapturePages() =>
			_pages.Select(ClonePage).ToList();

		private static PdfPageViewModel ClonePage(PdfPageViewModel source)
		{
			return new PdfPageViewModel
			{
				SourceFile = source.SourceFile,
				PageIndex = source.PageIndex,
				RotationDelta = source.RotationDelta,
				GroupColor = source.GroupColor,
				DisplayName = source.DisplayName,
				PreviewData = source.PreviewData,
				SourceLabel = source.SourceLabel,
				GroupId = source.GroupId,
				SequenceNumber = source.SequenceNumber
			};
		}

		private void PushUndoSnapshot(List<PdfPageViewModel> snapshot)
		{
			if (snapshot == null) return;
			const int maximumHistoryStates = 50;
			if (_undoStack.Count >= maximumHistoryStates)
			{
				List<PdfPageViewModel>[] retainedStates = _undoStack.Take(maximumHistoryStates - 1).Reverse().ToArray();
				_undoStack.Clear();
				foreach (List<PdfPageViewModel> retainedState in retainedStates)
					_undoStack.Push(retainedState);
			}

			_undoStack.Push(snapshot);
			_redoStack.Clear();
			UpdateDocumentState();
		}

		private void Undo()
		{
			if (_undoStack.Count == 0 || _isBusy || _isLoading) return;
			_redoStack.Push(CapturePages());
			RestorePages(_undoStack.Pop());
			MarkDirty();
		}

		private void Redo()
		{
			if (_redoStack.Count == 0 || _isBusy || _isLoading) return;
			_undoStack.Push(CapturePages());
			RestorePages(_redoStack.Pop());
			MarkDirty();
		}

		private void RestorePages(IReadOnlyList<PdfPageViewModel> pages)
		{
			_isReordering = true;
			try
			{
				ClearPreview();
				_pages.Clear();
				foreach (PdfPageViewModel page in pages)
					_pages.Add(ClonePage(page));
				RefreshSequenceNumbers();
				if (_pages.Count > 0) lstPages.SelectedIndex = 0;
			}
			finally
			{
				_isReordering = false;
				if (_pages.Count > 0) LstPages_SelectionChanged(lstPages, null);
				UpdateDocumentState();
			}
		}

		private void MarkDirty()
		{
			_isDirty = true;
			UpdateDocumentState();
		}

		private void UpdateDocumentState()
		{
			if (txtTitle == null) return;
			if (_isDashboardVisible)
			{
				txtTitle.Text = "TPL PDF Editor";
				return;
			}
			if (_isSpecializedToolVisible)
			{
				txtTitle.Text = $"TPL PDF Editor - {_activeToolName}";
				return;
			}

			string documentName = !string.IsNullOrEmpty(_currentFilePath)
				? Path.GetFileName(_currentFilePath)
				: string.IsNullOrWhiteSpace(txtFileName?.Text) ? "Untitled" : txtFileName.Text;
			txtTitle.Text = $"TPL PDF Editor - {_activeToolName} - {documentName}{(_isDirty ? " *" : string.Empty)}";

			int selectedCount = lstPages?.SelectedItems.Count ?? 0;
			if (txtDocumentStatus != null)
			{
				string selectionText = selectedCount > 0 ? $" - {selectedCount} selected" : string.Empty;
				string fileText = !string.IsNullOrEmpty(_currentFilePath) ? $" - {_currentFilePath}" : string.Empty;
				txtDocumentStatus.Text = $"{_pages.Count} pages{selectionText}{fileText}";
			}

			bool canInteract = !_isBusy && !_isLoading;
			if (btnUndo != null) btnUndo.IsEnabled = canInteract && _undoStack.Count > 0;
			if (btnRedo != null) btnRedo.IsEnabled = canInteract && _redoStack.Count > 0;
			if (btnSaveCommand != null) btnSaveCommand.IsEnabled = canInteract && _pages.Count > 0;
			if (btnSaveAs != null) btnSaveAs.IsEnabled = canInteract && _pages.Count > 0;
			if (btnSave != null) btnSave.IsEnabled = canInteract && _pages.Count > 0;
			if (btnExtract != null) btnExtract.IsEnabled = canInteract && selectedCount > 0;
			if (btnDuplicate != null) btnDuplicate.IsEnabled = canInteract && selectedCount > 0;
			if (btnRotateLeft != null) btnRotateLeft.IsEnabled = canInteract && selectedCount > 0;
			if (btnRotateRight != null) btnRotateRight.IsEnabled = canInteract && selectedCount > 0;
			if (btnRemove != null) btnRemove.IsEnabled = canInteract && selectedCount > 0;
			if (btnUp != null) btnUp.IsEnabled = canInteract && selectedCount > 0;
			if (btnDown != null) btnDown.IsEnabled = canInteract && selectedCount > 0;
			if (btnRotate != null) btnRotate.IsEnabled = canInteract && selectedCount > 0;
			if (btnAdd != null) btnAdd.IsEnabled = canInteract;
			if (btnOpen != null) btnOpen.IsEnabled = canInteract;
			if (btnNew != null) btnNew.IsEnabled = canInteract;
			if (btnHome != null) btnHome.IsEnabled = canInteract;
		}

		private void ClearPreview()
		{
			_previewRequestId++;
			IPdfDocument oldDocument = _pdfViewer.Document;
			_pdfViewer.Document = null;
			oldDocument?.Dispose();
			_currentPreviewStream?.Dispose();
			_currentPreviewStream = null;
			pdfHost.Visibility = Visibility.Collapsed;
			txtNoPreview.Visibility = Visibility.Visible;
			UpdateZoomControls();
		}

		private async void BtnNew_Click(object sender, RoutedEventArgs e) =>
			await NewDocumentAsync();

		private async void BtnHome_Click(object sender, RoutedEventArgs e) =>
			await NewDocumentAsync();

		private async void BtnOpen_Click(object sender, RoutedEventArgs e) =>
			await OpenDocumentAsync();

		private async void BtnSaveCommand_Click(object sender, RoutedEventArgs e) =>
			await SaveDocumentAsync(saveAs: false);

		private async void BtnSaveAs_Click(object sender, RoutedEventArgs e) =>
			await SaveDocumentAsync(saveAs: true);

		private void BtnUndo_Click(object sender, RoutedEventArgs e) => Undo();
		private void BtnRedo_Click(object sender, RoutedEventArgs e) => Redo();
		private void BtnDuplicate_Click(object sender, RoutedEventArgs e) => DuplicateSelectedPages();
		private void BtnRotateLeft_Click(object sender, RoutedEventArgs e) => RotateSelectedPages(-90);
		private void BtnRotateRight_Click(object sender, RoutedEventArgs e) => RotateSelectedPages(90);

		private async void BtnExtract_Click(object sender, RoutedEventArgs e) =>
			await ExtractSelectedPagesAsync();

		private void ToolsDashboard_ToolSelected(object sender, PdfToolSelectedEventArgs e)
		{
			try
			{
				if (e.Action == PdfToolAction.Edit)
					ShowEditorWorkspace(e.Title);
				else
					ShowSpecializedToolWorkspace(e.Action, e.Title);
			}
			catch (Exception ex)
			{
				MessageBox.Show(
					"The selected PDF tool could not be opened.\n\n" + ex.Message,
					"TPL PDF Editor",
					MessageBoxButton.OK,
					MessageBoxImage.Error);
			}
		}

		private void SpecializedToolWorkspace_BackRequested(object sender, EventArgs e)
		{
			ShowToolsDashboard();
		}

		private async Task NewDocumentAsync()
		{
			if (_isLoading || _isBusy) return;
			if (!await ConfirmDiscardChangesAsync()) return;
			ResetDocument(deleteOwnedSourceFiles: true);
			txtFileName.Text = string.Empty;
			ShowToolsDashboard();
		}

		private async Task<bool> OpenDocumentAsync()
		{
			if (_isLoading || _isBusy) return false;
			var dialog = new Microsoft.Win32.OpenFileDialog
			{
				Filter = "PDF Files|*.pdf",
				Multiselect = false,
				Title = "Open PDF"
			};
			if (dialog.ShowDialog() != true) return false;
			if (!await ConfirmDiscardChangesAsync()) return false;

			ResetDocument(deleteOwnedSourceFiles: true);
			string filePath = Path.GetFullPath(dialog.FileName);
			txtFileName.Text = Path.GetFileNameWithoutExtension(filePath);
			await AddPdfFilesAsync(new[] { filePath }, isAutoGenerated: false, trackHistory: false);
			if (_pages.Count == 0)
			{
				MessageBox.Show(
					"The selected PDF could not be opened.",
					"TPL PDF Editor",
					MessageBoxButton.OK,
					MessageBoxImage.Error);
				ShowToolsDashboard();
				return false;
			}

			_currentFilePath = filePath;
			_isDirty = false;
			_undoStack.Clear();
			_redoStack.Clear();
			ShowEditorWorkspace("Edit PDF");
			return true;
		}

		private async Task<bool> ConfirmDiscardChangesAsync()
		{
			if (!_isDirty || _pages.Count == 0) return true;

			MessageBoxResult result = MessageBox.Show(
				"Save changes to the current PDF before continuing?",
				"TPL PDF Editor",
				MessageBoxButton.YesNoCancel,
				MessageBoxImage.Warning);
			if (result == MessageBoxResult.Cancel) return false;
			if (result == MessageBoxResult.Yes)
				return await SaveDocumentAsync(saveAs: false);
			return true;
		}

		private void ResetDocument(bool deleteOwnedSourceFiles)
		{
			ClearPreview();
			_pages.Clear();
			_undoStack.Clear();
			_redoStack.Clear();
			_currentFilePath = null;
			_isDirty = false;
			_colorIndex = 0;
			_groupIdCounter = 0;
			if (deleteOwnedSourceFiles) DeleteOwnedSourceFiles();
			else _autoGeneratedFiles.Clear();
			UpdateDocumentState();
		}

		private void DeleteOwnedSourceFiles()
		{
			foreach (string file in _autoGeneratedFiles.Distinct(StringComparer.OrdinalIgnoreCase))
			{
				if (!string.Equals(Path.GetExtension(file), ".pdf", StringComparison.OrdinalIgnoreCase))
				{
					System.Diagnostics.Debug.WriteLine($"[PdfEditor] Refusing to delete a non-PDF owned path: '{file}'.");
					continue;
				}
				try
				{
					if (File.Exists(file)) File.Delete(file);
				}
				catch (IOException ex)
				{
					System.Diagnostics.Debug.WriteLine($"[PdfEditor] Could not delete temporary file '{file}': {ex.Message}");
				}
				catch (UnauthorizedAccessException ex)
				{
					System.Diagnostics.Debug.WriteLine($"[PdfEditor] Could not delete temporary file '{file}': {ex.Message}");
				}
			}
			_autoGeneratedFiles.Clear();
		}

		private async Task<bool> SaveDocumentAsync(bool saveAs)
		{
			if (_pages.Count == 0 || _isBusy || _isLoading) return false;

			string savePath = !saveAs ? _currentFilePath : null;
			if (string.IsNullOrEmpty(savePath))
			{
				var dialog = new Microsoft.Win32.SaveFileDialog
				{
					Filter = "PDF File|*.pdf",
					Title = L10n.T("dlg_save_pdf"),
					FileName = string.IsNullOrWhiteSpace(txtFileName.Text) ? "document.pdf" : txtFileName.Text,
					AddExtension = true,
					DefaultExt = ".pdf"
				};
				if (dialog.ShowDialog() != true) return false;
				savePath = dialog.FileName;
			}

			List<PdfPageReference> pages = _pages.Select(ToPageReference).ToList();
			if (!await SavePageReferencesAsync(pages, savePath, "Saving PDF...")) return false;

			_currentFilePath = Path.GetFullPath(savePath);
			txtFileName.Text = Path.GetFileNameWithoutExtension(_currentFilePath);
			_autoGeneratedFiles.RemoveAll(file =>
				string.Equals(Path.GetFullPath(file), _currentFilePath, StringComparison.OrdinalIgnoreCase));
			try
			{
				await RebaseToSavedDocumentAsync(_currentFilePath);
			}
			catch (Exception ex)
			{
				MessageBox.Show(
					"The PDF was saved, but the editor could not reload it.\n\n" + ex.Message,
					"TPL PDF Editor",
					MessageBoxButton.OK,
					MessageBoxImage.Warning);
				MarkDirty();
				return false;
			}
			_undoStack.Clear();
			_redoStack.Clear();
			_isDirty = false;
			UpdateDocumentState();
			return true;
		}

		private async Task RebaseToSavedDocumentAsync(string savedFilePath)
		{
			int pageCount = await Task.Run(() => PdfDocumentService.GetPageCount(savedFilePath));
			System.Drawing.Color groupColor = _pages.Count > 0 ? _pages[0].GroupColor : GetNextColor();
			int groupId = _groupIdCounter++;

			_isReordering = true;
			try
			{
				ClearPreview();
				_pages.Clear();
				for (int pageIndex = 0; pageIndex < pageCount; pageIndex++)
				{
					_pages.Add(new PdfPageViewModel
					{
						SourceFile = savedFilePath,
						PageIndex = pageIndex,
						RotationDelta = 0,
						GroupColor = groupColor,
						GroupId = groupId,
						SourceLabel = "File",
						DisplayName = string.Format(L10n.T("page_name"), Path.GetFileName(savedFilePath), pageIndex + 1),
						SequenceNumber = pageIndex + 1
					});
				}
				RefreshSequenceNumbers();
				if (_pages.Count > 0) lstPages.SelectedIndex = 0;
			}
			finally
			{
				_isReordering = false;
				if (_pages.Count > 0) LstPages_SelectionChanged(lstPages, null);
			}
		}

		private async Task ExtractSelectedPagesAsync()
		{
			var selectedPages = new HashSet<PdfPageViewModel>(lstPages.SelectedItems.Cast<PdfPageViewModel>());
			if (selectedPages.Count == 0 || _isBusy || _isLoading) return;

			string baseName = string.IsNullOrWhiteSpace(txtFileName.Text) ? "document" : txtFileName.Text;
			var dialog = new Microsoft.Win32.SaveFileDialog
			{
				Filter = "PDF File|*.pdf",
				Title = "Extract selected pages",
				FileName = baseName + "_selected.pdf",
				AddExtension = true,
				DefaultExt = ".pdf"
			};
			if (dialog.ShowDialog() != true) return;

			List<PdfPageReference> pages = _pages
				.Where(selectedPages.Contains)
				.Select(ToPageReference)
				.ToList();
			await SavePageReferencesAsync(pages, dialog.FileName, "Extracting pages...");
		}

		private async Task<bool> SavePageReferencesAsync(
			IReadOnlyList<PdfPageReference> pages,
			string outputPath,
			string progressLabel)
		{
			SetBusy(true);
			pnlProgress.Visibility = Visibility.Visible;
			pnlProgress.Value = 0;
			pnlProgress.Label = progressLabel;
			pnlProgress.Percent = "0%";

			try
			{
				await Task.Run(() => PdfDocumentService.Save(
					pages,
					outputPath,
					(current, total) =>
					{
						int percent = (int)Math.Round(current * 100d / total);
						Dispatcher.InvokeAsync(() =>
						{
							pnlProgress.Value = percent;
							pnlProgress.Percent = $"{percent}%";
							pnlProgress.Label = $"{progressLabel} {current} / {total}";
						});
					},
					CancellationToken.None));

				pnlProgress.Value = 100;
				pnlProgress.Percent = "100%";
				pnlProgress.Label = L10n.T("msg_save_success");
				return true;
			}
			catch (Exception ex)
			{
				MessageBox.Show(
					string.Format(L10n.T("msg_save_error"), ex.Message),
					L10n.T("err_title"),
					MessageBoxButton.OK,
					MessageBoxImage.Error);
				return false;
			}
			finally
			{
				SetBusy(false);
				var timer = new System.Windows.Threading.DispatcherTimer { Interval = TimeSpan.FromSeconds(2) };
				timer.Tick += (timerSender, timerArgs) =>
				{
					pnlProgress.Visibility = Visibility.Collapsed;
					timer.Stop();
				};
				timer.Start();
			}
		}

		private void SetBusy(bool isBusy)
		{
			_isBusy = isBusy;
			btnSave.IsEnabled = !isBusy && _pages.Count > 0;
			btnCancel.IsEnabled = !isBusy;
			btnAdd.IsEnabled = !isBusy;
			btnOpen.IsEnabled = !isBusy;
			btnNew.IsEnabled = !isBusy;
			UpdateDocumentState();
		}

		private void SetLoading(bool isLoading)
		{
			_isLoading = isLoading;
			lstPages.IsEnabled = !isLoading;
			UpdateDocumentState();
		}

		private static PdfPageReference ToPageReference(PdfPageViewModel page) =>
			new(page.SourceFile, page.PageIndex, page.RotationDelta);

		private void DuplicateSelectedPages()
		{
			var selectedItems = new HashSet<PdfPageViewModel>(lstPages.SelectedItems.Cast<PdfPageViewModel>());
			if (selectedItems.Count == 0 || _isBusy || _isLoading) return;

			List<PdfPageViewModel> undoSnapshot = CapturePages();
			var duplicates = new List<PdfPageViewModel>();
			foreach (PdfPageViewModel item in _pages.Where(selectedItems.Contains).ToList())
			{
				int sourceIndex = _pages.IndexOf(item);
				PdfPageViewModel duplicate = ClonePage(item);
				_pages.Insert(sourceIndex + 1, duplicate);
				duplicates.Add(duplicate);
			}

			RefreshSequenceNumbers();
			lstPages.SelectedItems.Clear();
			foreach (PdfPageViewModel duplicate in duplicates)
				lstPages.SelectedItems.Add(duplicate);
			PushUndoSnapshot(undoSnapshot);
			MarkDirty();
		}

		private void RotateSelectedPages(int rotationDelta)
		{
			List<PdfPageViewModel> selected = lstPages.SelectedItems.Cast<PdfPageViewModel>().ToList();
			if (selected.Count == 0 || _isBusy || _isLoading) return;

			List<PdfPageViewModel> undoSnapshot = CapturePages();
			foreach (PdfPageViewModel item in selected)
			{
				int rotation = (item.RotationDelta + rotationDelta) % 360;
				if (rotation < 0) rotation += 360;
				item.RotationDelta = rotation;
				item.PreviewData = null;
			}

			PushUndoSnapshot(undoSnapshot);
			MarkDirty();
			LstPages_SelectionChanged(lstPages, null);
		}

		// ─── Title bar (drag window) ────────────────────────────────────────
		private void TitleBar_MouseLeftButtonDown(object sender, MouseButtonEventArgs e)
		{
			if (e.ClickCount == 2)
			{
				ToggleMaximizedState();
			}
			else
			{
				DragMove();
			}
		}

		private void BtnMinimize_Click(object sender, RoutedEventArgs e) => WindowState = WindowState.Minimized;
		private void BtnMaximize_Click(object sender, RoutedEventArgs e) => ToggleMaximizedState();
		private void BtnClose_Click(object sender, RoutedEventArgs e) => Close();

		private void ToggleMaximizedState()
		{
			if (WindowState == WindowState.Maximized)
				SystemCommands.RestoreWindow(this);
			else
				SystemCommands.MaximizeWindow(this);
		}

		protected override void OnStateChanged(EventArgs e)
		{
			base.OnStateChanged(e);
			UpdateWindowStateVisual();
		}

		private void UpdateWindowStateVisual()
		{
			if (iconMaximize == null || iconWindowed == null || btnMaximize == null)
				return;

			bool isMaximized = WindowState == WindowState.Maximized;
			iconMaximize.Visibility = isMaximized ? Visibility.Collapsed : Visibility.Visible;
			iconWindowed.Visibility = isMaximized ? Visibility.Visible : Visibility.Collapsed;
			btnMaximize.ToolTip = isMaximized ? "Restore window" : "Maximize";
		}

		protected override void OnKeyDown(KeyEventArgs e)
		{
			if (e.Key == Key.Escape && WindowState == WindowState.Maximized)
			{
				WindowState = WindowState.Normal;
				e.Handled = true;
				return;
			}

			bool controlPressed = (Keyboard.Modifiers & ModifierKeys.Control) == ModifierKeys.Control;
			bool shiftPressed = (Keyboard.Modifiers & ModifierKeys.Shift) == ModifierKeys.Shift;
			bool isEditingText = Keyboard.FocusedElement is System.Windows.Controls.Primitives.TextBoxBase;

			if (controlPressed && e.Key == Key.N)
			{
				_ = NewDocumentAsync();
				e.Handled = true;
			}
			else if (controlPressed && e.Key == Key.O)
			{
				_ = OpenDocumentAsync();
				e.Handled = true;
			}
			else if (controlPressed && shiftPressed && e.Key == Key.S)
			{
				_ = SaveDocumentAsync(saveAs: true);
				e.Handled = true;
			}
			else if (controlPressed && e.Key == Key.S)
			{
				_ = SaveDocumentAsync(saveAs: false);
				e.Handled = true;
			}
			else if (!isEditingText && controlPressed && e.Key == Key.Z)
			{
				Undo();
				e.Handled = true;
			}
			else if (!isEditingText && controlPressed && e.Key == Key.Y)
			{
				Redo();
				e.Handled = true;
			}
			else if (!isEditingText && controlPressed && e.Key == Key.A)
			{
				lstPages.SelectAll();
				e.Handled = true;
			}
			else if (!isEditingText && controlPressed && e.Key == Key.D)
			{
				DuplicateSelectedPages();
				e.Handled = true;
			}
			else if (!isEditingText && controlPressed && e.Key == Key.E)
			{
				_ = ExtractSelectedPagesAsync();
				e.Handled = true;
			}
			else if (!isEditingText && e.Key == Key.Delete)
			{
				BtnRemove_Click(this, new RoutedEventArgs());
				e.Handled = true;
			}

			if (!e.Handled) base.OnKeyDown(e);
		}

		private bool _isReordering = false;

		// ─── Page Selection → Preview ───────────────────────────────────────
		private async void LstPages_SelectionChanged(object sender, SelectionChangedEventArgs e)
		{
			if (_isReordering) return;
			UpdateDocumentState();
			int requestId = ++_previewRequestId;

			if (lstPages.SelectedItem is PdfPageViewModel item)
			{
				try
				{
					byte[] previewData = item.PreviewData;
					if (previewData == null || previewData.Length == 0)
					{
						string sourceFile = item.SourceFile;
						int pageIndex = item.PageIndex;
						int rotationDelta = item.RotationDelta;
						previewData = await Task.Run(() => PdfDocumentService.BuildPreviewData(
							new PdfPageReference(sourceFile, pageIndex, rotationDelta)));

						if (requestId != _previewRequestId || _isClosing || lstPages.SelectedItem != item)
							return;

						item.PreviewData = previewData;
					}

					if (requestId != _previewRequestId || _isClosing || lstPages.SelectedItem != item)
						return;

					var oldDoc = _pdfViewer.Document;
					var oldStream = _currentPreviewStream;

					var ms = new MemoryStream(previewData, writable: false);
					PdfiumViewer.PdfDocument pdfDoc;
					try
					{
						pdfDoc = PdfiumViewer.PdfDocument.Load(ms);
					}
					catch
					{
						ms.Dispose();
						throw;
					}

					_currentPreviewStream = ms;
					_pdfViewer.Document = pdfDoc;
					pdfHost.Visibility = Visibility.Visible;
					UpdateZoomControls();

					oldDoc?.Dispose();
					oldStream?.Dispose();
					txtNoPreview.Visibility = Visibility.Collapsed;
				}
				catch (Exception ex)
				{
					System.Diagnostics.Debug.WriteLine($"[PdfEditor] Preview error: {ex.Message}");
				}
			}
			else
			{
				// Không có trang nào được chọn → hiện placeholder
				pdfHost.Visibility = Visibility.Collapsed;
				txtNoPreview.Visibility = Visibility.Visible;
				UpdateZoomControls();
			}
		}

		private void BtnZoomOut_Click(object sender, RoutedEventArgs e)
		{
			if (_pdfViewer.Document != null)
				SetPreviewZoom(_pdfViewer.Renderer.Zoom / _pdfViewer.Renderer.ZoomFactor);
		}

		private void BtnZoomIn_Click(object sender, RoutedEventArgs e)
		{
			if (_pdfViewer.Document != null)
				SetPreviewZoom(_pdfViewer.Renderer.Zoom * _pdfViewer.Renderer.ZoomFactor);
		}

		private void CmbZoomPercent_SelectionChanged(object sender, SelectionChangedEventArgs e)
		{
			if (_isUpdatingZoomSelection || cmbZoomPercent.SelectedItem is not int zoomPercent)
				return;

			SetPreviewZoom(zoomPercent / 100d);
		}

		private void SetPreviewZoom(double requestedZoom)
		{
			PdfRenderer renderer = _pdfViewer.Renderer;
			if (_pdfViewer.Document == null || renderer.ClientSize.Width <= 0 || renderer.ClientSize.Height <= 0)
				return;

			double targetZoom = Math.Min(Math.Max(requestedZoom, renderer.ZoomMin), renderer.ZoomMax);
			if (Math.Abs(targetZoom - renderer.Zoom) < 0.0001)
				return;

			var viewportCenter = new System.Drawing.Point(
				renderer.ClientSize.Width / 2,
				renderer.ClientSize.Height / 2);
			PdfPoint pdfAnchor = renderer.PointToPdf(viewportCenter);
			System.Drawing.Rectangle oldDisplay = renderer.DisplayRectangle;
			double fallbackX = oldDisplay.Width > 0
				? (viewportCenter.X - oldDisplay.Left) / (double)oldDisplay.Width
				: 0.5;
			double fallbackY = oldDisplay.Height > 0
				? (viewportCenter.Y - oldDisplay.Top) / (double)oldDisplay.Height
				: 0.5;

			renderer.Zoom = targetZoom;

			System.Drawing.Rectangle newDisplay = renderer.DisplayRectangle;
			System.Drawing.Point targetDisplayLocation;
			if (pdfAnchor.IsValid)
			{
				System.Drawing.Point movedAnchor = renderer.PointFromPdf(pdfAnchor);
				targetDisplayLocation = new System.Drawing.Point(
					newDisplay.Left + viewportCenter.X - movedAnchor.X,
					newDisplay.Top + viewportCenter.Y - movedAnchor.Y);
			}
			else
			{
				targetDisplayLocation = new System.Drawing.Point(
					(int)Math.Round(viewportCenter.X - (fallbackX * newDisplay.Width)),
					(int)Math.Round(viewportCenter.Y - (fallbackY * newDisplay.Height)));
			}

			renderer.SetDisplayRectLocation(targetDisplayLocation, false);
		}

		private void PdfRenderer_ZoomChanged(object sender, EventArgs e)
		{
			UpdateZoomControls();
		}

		private void UpdateZoomControls()
		{
			if (!Dispatcher.CheckAccess())
			{
				Dispatcher.BeginInvoke(new Action(UpdateZoomControls));
				return;
			}

			double zoom = _pdfViewer.Renderer.Zoom;
			int zoomPercent = (int)Math.Round(zoom * 100, MidpointRounding.AwayFromZero);
			bool hasDocument = _pdfViewer.Document != null && lstPages.SelectedItem is PdfPageViewModel;

			UpdateZoomPercentageSelection(zoomPercent);
			cmbZoomPercent.IsEnabled = hasDocument;
			btnZoomOut.IsEnabled = hasDocument && zoom > _pdfViewer.Renderer.ZoomMin;
			btnZoomIn.IsEnabled = hasDocument && zoom < _pdfViewer.Renderer.ZoomMax;
		}

		private void UpdateZoomPercentageSelection(int zoomPercent)
		{
			_isUpdatingZoomSelection = true;
			try
			{
				bool isStandardZoom = Array.BinarySearch(StandardZoomPercentages, zoomPercent) >= 0;
				if (_customZoomPercentage.HasValue && _customZoomPercentage.Value != zoomPercent)
					_zoomPercentOptions.Remove(_customZoomPercentage.Value);

				if (!_zoomPercentOptions.Contains(zoomPercent))
				{
					int insertIndex = 0;
					while (insertIndex < _zoomPercentOptions.Count && _zoomPercentOptions[insertIndex] < zoomPercent)
						insertIndex++;

					_zoomPercentOptions.Insert(insertIndex, zoomPercent);
				}

				_customZoomPercentage = isStandardZoom ? null : zoomPercent;
				cmbZoomPercent.SelectedItem = zoomPercent;
			}
			finally
			{
				_isUpdatingZoomSelection = false;
			}
		}

		// ─── Toolbar Actions ────────────────────────────────────────────────

		private async void BtnAdd_Click(object sender, RoutedEventArgs e)
		{
			var ofd = new Microsoft.Win32.OpenFileDialog
			{
				Filter = "PDF Files|*.pdf",
				Multiselect = true,
				Title = L10n.T("dlg_add_pdf")
			};

			if (ofd.ShowDialog() == true)
			{
				await AddPdfFilesAsync(ofd.FileNames.ToList(), false);
			}
		}

		private void BtnRemove_Click(object sender, RoutedEventArgs e)
		{
			if (_isBusy || _isLoading) return;
			var selected = lstPages.SelectedItems.Cast<PdfPageViewModel>().ToList();
			if (selected.Count == 0) return;
			List<PdfPageViewModel> undoSnapshot = CapturePages();

			// Ghi lại index trước khi xóa để chọn lại trang hợp lệ sau đó
			int firstSelectedIndex = lstPages.SelectedIndex;

			_isReordering = true;
			try
			{
				foreach (var item in selected)
					_pages.Remove(item);

				RefreshSequenceNumbers();

				// ═══ FIX: sau khi xoá, chọn trang gần nhất (tránh preview kẹt) ═══
				if (_pages.Count > 0)
				{
					int newIndex = Math.Min(firstSelectedIndex, _pages.Count - 1);
					lstPages.SelectedIndex = newIndex;
				}
				else
				{
					ClearPreview();
				}
			}
			finally
			{
				_isReordering = false;
				if (_pages.Count > 0)
					LstPages_SelectionChanged(lstPages, null);
			}

			PushUndoSnapshot(undoSnapshot);
			MarkDirty();
		}

		private void BtnUp_Click(object sender, RoutedEventArgs e) => MoveSelectedItems(-1);
		private void BtnDown_Click(object sender, RoutedEventArgs e) => MoveSelectedItems(1);

		private void BtnRotate_Click(object sender, RoutedEventArgs e)
		{
			RotateSelectedPages(90);
		}

		private void MoveSelectedItems(int direction)
		{
			if (_isBusy || _isLoading) return;
			var selectedIndices = new List<int>();
			foreach (var item in lstPages.SelectedItems)
			{
				int idx = _pages.IndexOf((PdfPageViewModel)item);
				if (idx >= 0) selectedIndices.Add(idx);
			}
			if (selectedIndices.Count == 0) return;

			selectedIndices.Sort();

			if (direction == -1 && selectedIndices[0] == 0) return;
			if (direction == 1 && selectedIndices[selectedIndices.Count - 1] == _pages.Count - 1) return;
			List<PdfPageViewModel> undoSnapshot = CapturePages();

			// Di chuyển theo thứ tự phù hợp
			if (direction == 1) selectedIndices.Reverse();

			_isReordering = true;
			try
			{
				var newIndices = new List<int>();
				foreach (int idx in selectedIndices)
				{
					int newIdx = idx + direction;
					_pages.Move(idx, newIdx);
					newIndices.Add(newIdx);
				}

				RefreshSequenceNumbers();

				// Giữ lại selection
				lstPages.SelectedItems.Clear();
				foreach (int idx in newIndices)
					lstPages.SelectedItems.Add(_pages[idx]);
			}
			finally
			{
				_isReordering = false;
				LstPages_SelectionChanged(lstPages, null);
			}

			PushUndoSnapshot(undoSnapshot);
			MarkDirty();
		}

		// ─── Save with Progress Bar (async — không block UI) ────────────────
		private async void BtnSave_Click(object sender, RoutedEventArgs e)
		{
			await SaveDocumentAsync(saveAs: true);
		}

		private void BtnCancel_Click(object sender, RoutedEventArgs e) => Close();

		// ─── Multi-item Drag & Drop with Drop Indicator ────────────────────

		private void LstPages_PreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
		{
			_isDragging = false;
			_dragStartItem = null;
			_collapseSelectionOnMouseUp = false;

			DependencyObject source = e.OriginalSource as DependencyObject;
			if (FindVisualAncestor<System.Windows.Controls.Primitives.ScrollBar>(source) != null)
				return;

			ListViewItem sourceContainer = FindVisualAncestor<ListViewItem>(source);
			if (sourceContainer?.Content is not PdfPageViewModel sourceItem)
				return;

			_dragStartPoint = e.GetPosition(lstPages);
			_dragStartItem = sourceItem;

			// Giữ multi-selection khi bắt đầu kéo một hàng đang được chọn. Nếu chỉ click,
			// selection sẽ được thu về hàng đó trong PreviewMouseLeftButtonUp.
			if (sourceContainer.IsSelected &&
				lstPages.SelectedItems.Count > 1 &&
				Keyboard.Modifiers == ModifierKeys.None)
			{
				_collapseSelectionOnMouseUp = true;
				sourceContainer.Focus();
				e.Handled = true;
			}
		}

		private void LstPages_PreviewMouseLeftButtonUp(object sender, MouseButtonEventArgs e)
		{
			if (_collapseSelectionOnMouseUp && !_isDragging && _dragStartItem != null)
			{
				lstPages.SelectedItems.Clear();
				lstPages.SelectedItem = _dragStartItem;
			}

			_dragStartItem = null;
			_collapseSelectionOnMouseUp = false;
		}

		private void LstPages_PreviewMouseMove(object sender, MouseEventArgs e)
		{
			if (_isBusy || _isLoading) return;
			if (_isDragging || _dragStartItem == null || e.LeftButton != MouseButtonState.Pressed)
				return;

			Point currentPos = e.GetPosition(lstPages);
			Vector diff = _dragStartPoint - currentPos;

			if (Math.Abs(diff.X) <= SystemParameters.MinimumHorizontalDragDistance &&
				Math.Abs(diff.Y) <= SystemParameters.MinimumVerticalDragDistance)
				return;

			if (!lstPages.SelectedItems.Contains(_dragStartItem))
			{
				lstPages.SelectedItems.Clear();
				lstPages.SelectedItem = _dragStartItem;
			}

			var selectedSet = new HashSet<PdfPageViewModel>(lstPages.SelectedItems.Cast<PdfPageViewModel>());
			var selectedItems = _pages.Where(selectedSet.Contains).ToList();
			if (selectedItems.Count == 0)
				return;

			_isDragging = true;
			_collapseSelectionOnMouseUp = false;
			try
			{
				var dragData = new DataObject(PdfPagesDataFormat, selectedItems);
				DragDrop.DoDragDrop(lstPages, dragData, DragDropEffects.Move);
			}
			finally
			{
				ClearDropIndicator();
				_isDragging = false;
				_dragStartItem = null;
			}
		}

		private void Window_DragOver(object sender, DragEventArgs e)
		{
			if (TryGetDroppedPdfFiles(e.Data, out _))
			{
				e.Effects = DragDropEffects.Copy;
				e.Handled = true;
			}
		}

		private async void Window_Drop(object sender, DragEventArgs e)
		{
			if (!TryGetDroppedPdfFiles(e.Data, out List<string> pdfFiles)) return;
			e.Handled = true;
			try
			{
				if (_isSpecializedToolVisible)
				{
					await specializedToolWorkspace.HandleDroppedFilesAsync(pdfFiles);
					return;
				}

				if (_isDashboardVisible && pdfFiles.Count > 1)
				{
					ShowSpecializedToolWorkspace(PdfToolAction.Merge, "Merge PDF");
					await specializedToolWorkspace.HandleDroppedFilesAsync(pdfFiles);
					return;
				}

				await AddPdfFilesAsync(pdfFiles, isAutoGenerated: false);
				if (_pages.Count > 0) ShowEditorWorkspace("Edit PDF");
			}
			catch (Exception ex)
			{
				MessageBox.Show(
					"The dropped PDF files could not be opened.\n\n" + ex.Message,
					"TPL PDF Editor",
					MessageBoxButton.OK,
					MessageBoxImage.Error);
			}
		}

		private static bool TryGetDroppedPdfFiles(IDataObject data, out List<string> pdfFiles)
		{
			pdfFiles = new List<string>();
			if (!data.GetDataPresent(DataFormats.FileDrop) || data.GetData(DataFormats.FileDrop) is not string[] files)
				return false;

			pdfFiles.AddRange(files.Where(file =>
				string.Equals(Path.GetExtension(file), ".pdf", StringComparison.OrdinalIgnoreCase)));
			return pdfFiles.Count > 0;
		}

		private void LstPages_DragOver(object sender, DragEventArgs e)
		{
			if (TryGetDroppedPdfFiles(e.Data, out _))
			{
				e.Effects = DragDropEffects.Copy;
				ClearDropIndicator();
				e.Handled = true;
				return;
			}

			if (!e.Data.GetDataPresent(PdfPagesDataFormat) ||
				e.Data.GetData(PdfPagesDataFormat) is not List<PdfPageViewModel>)
			{
				e.Effects = DragDropEffects.None;
				ClearDropIndicator();
				e.Handled = true;
				return;
			}

			DependencyObject source = e.OriginalSource as DependencyObject;
			if (FindVisualAncestor<System.Windows.Controls.Primitives.ScrollBar>(source) != null ||
				FindVisualAncestor<GridViewColumnHeader>(source) != null)
			{
				e.Effects = DragDropEffects.None;
				ClearDropIndicator();
				e.Handled = true;
				return;
			}

			AutoScrollPageList(e.GetPosition(lstPages));

			if (TryGetDropPosition(e, out int insertIndex, out double indicatorY))
			{
				e.Effects = DragDropEffects.Move;
				ShowDropIndicator(insertIndex, indicatorY);
			}
			else
			{
				e.Effects = DragDropEffects.None;
				ClearDropIndicator();
			}

			e.Handled = true;
		}

		private bool TryGetDropPosition(DragEventArgs e, out int insertIndex, out double indicatorY)
		{
			insertIndex = -1;
			indicatorY = 0;

			ListViewItem targetContainer = FindVisualAncestor<ListViewItem>(e.OriginalSource as DependencyObject);
			if (targetContainer?.Content is PdfPageViewModel targetItem)
			{
				int targetIndex = _pages.IndexOf(targetItem);
				if (targetIndex < 0)
					return false;

				bool insertBefore = e.GetPosition(targetContainer).Y < targetContainer.ActualHeight / 2;
				Point topLeft = targetContainer.TranslatePoint(new Point(0, 0), lstPages);
				insertIndex = insertBefore ? targetIndex : targetIndex + 1;
				indicatorY = insertBefore ? topLeft.Y : topLeft.Y + targetContainer.ActualHeight;
				return true;
			}

			if (_pages.Count == 0)
				return false;

			var lastContainer = lstPages.ItemContainerGenerator.ContainerFromIndex(_pages.Count - 1) as ListViewItem;
			if (lastContainer == null)
				return false;

			Point lastTopLeft = lastContainer.TranslatePoint(new Point(0, 0), lstPages);
			double lastBottom = lastTopLeft.Y + lastContainer.ActualHeight;
			if (e.GetPosition(lstPages).Y < lastBottom)
				return false;

			insertIndex = _pages.Count;
			indicatorY = lastBottom;
			return true;
		}

		private void ShowDropIndicator(int insertIndex, double indicatorY)
		{
			_dropInsertIndex = insertIndex;
			AdornerLayer adornerLayer = AdornerLayer.GetAdornerLayer(lstPages);
			if (adornerLayer == null)
				return;

			if (_dropInsertionAdorner == null)
			{
				_dropInsertionAdorner = new DropInsertionAdorner(lstPages);
				adornerLayer.Add(_dropInsertionAdorner);
			}

			_dropInsertionAdorner.UpdatePosition(indicatorY);
		}

		private void ClearDropIndicator()
		{
			_dropInsertIndex = -1;
			if (_dropInsertionAdorner == null)
				return;

			AdornerLayer.GetAdornerLayer(lstPages)?.Remove(_dropInsertionAdorner);
			_dropInsertionAdorner = null;
		}

		private void LstPages_DragLeave(object sender, DragEventArgs e)
		{
			ClearDropIndicator();
		}

		private void LstPages_SizeChanged(object sender, SizeChangedEventArgs e)
		{
			UpdatePageColumnWidth();
		}

		private void AutoScrollPageList(Point pointerPosition)
		{
			bool scrollUp = pointerPosition.Y < AutoScrollBoundary;
			bool scrollDown = pointerPosition.Y > lstPages.ActualHeight - AutoScrollBoundary;
			if (!scrollUp && !scrollDown)
				return;

			DateTime now = DateTime.UtcNow;
			if (now - _lastAutoScrollUtc < AutoScrollInterval)
				return;

			_pageListScrollViewer ??= FindVisualDescendant<ScrollViewer>(lstPages);
			if (_pageListScrollViewer == null)
				return;

			if (scrollUp)
				_pageListScrollViewer.LineUp();
			else
				_pageListScrollViewer.LineDown();

			_lastAutoScrollUtc = now;
		}

		private async void LstPages_Drop(object sender, DragEventArgs e)
		{
			if (TryGetDroppedPdfFiles(e.Data, out List<string> pdfFiles))
			{
				ClearDropIndicator();
				e.Handled = true;
				await AddPdfFilesAsync(pdfFiles, isAutoGenerated: false);
				return;
			}

			int requestedInsertIndex = _dropInsertIndex;
			ClearDropIndicator();
			e.Handled = true;

			if (requestedInsertIndex < 0 ||
				!e.Data.GetDataPresent(PdfPagesDataFormat) ||
				e.Data.GetData(PdfPagesDataFormat) is not List<PdfPageViewModel> droppedItems ||
				droppedItems.Count == 0)
				return;

			var currentItems = new HashSet<PdfPageViewModel>(_pages);
			var droppedSet = new HashSet<PdfPageViewModel>(droppedItems.Where(currentItems.Contains));
			var orderedDroppedItems = _pages.Where(droppedSet.Contains).ToList();
			if (orderedDroppedItems.Count == 0)
				return;

			requestedInsertIndex = Math.Max(0, Math.Min(requestedInsertIndex, _pages.Count));
			int removedBeforeInsert = _pages.Take(requestedInsertIndex).Count(droppedSet.Contains);
			int dropIndex = requestedInsertIndex - removedBeforeInsert;

			var reorderedItems = _pages.Where(item => !droppedSet.Contains(item)).ToList();
			dropIndex = Math.Max(0, Math.Min(dropIndex, reorderedItems.Count));
			reorderedItems.InsertRange(dropIndex, orderedDroppedItems);

			if (_pages.SequenceEqual(reorderedItems))
				return;
			List<PdfPageViewModel> undoSnapshot = CapturePages();

			_isReordering = true;
			try
			{
				foreach (var item in orderedDroppedItems)
					_pages.Remove(item);

				for (int i = 0; i < orderedDroppedItems.Count; i++)
					_pages.Insert(dropIndex + i, orderedDroppedItems[i]);

				RefreshSequenceNumbers();

				lstPages.SelectedItems.Clear();
				foreach (var item in orderedDroppedItems)
					lstPages.SelectedItems.Add(item);

				lstPages.ScrollIntoView(orderedDroppedItems[0]);
			}
			finally
			{
				_isReordering = false;
				LstPages_SelectionChanged(lstPages, null);
			}

			PushUndoSnapshot(undoSnapshot);
			MarkDirty();
		}

		private static T FindVisualAncestor<T>(DependencyObject element) where T : DependencyObject
		{
			while (element != null)
			{
				if (element is T match)
					return match;

				element = VisualTreeHelper.GetParent(element);
			}

			return null;
		}

		private static T FindVisualDescendant<T>(DependencyObject element) where T : DependencyObject
		{
			if (element == null)
				return null;

			int childCount = VisualTreeHelper.GetChildrenCount(element);
			for (int i = 0; i < childCount; i++)
			{
				DependencyObject child = VisualTreeHelper.GetChild(element, i);
				if (child is T match)
					return match;

				T descendant = FindVisualDescendant<T>(child);
				if (descendant != null)
					return descendant;
			}

			return null;
		}

		private sealed class DropInsertionAdorner : Adorner
		{
			private static readonly Pen IndicatorPen = CreateIndicatorPen();
			private double _indicatorY;

			public DropInsertionAdorner(UIElement adornedElement)
				: base(adornedElement)
			{
				IsHitTestVisible = false;
			}

			public void UpdatePosition(double indicatorY)
			{
				_indicatorY = indicatorY;
				InvalidateVisual();
			}

			protected override void OnRender(DrawingContext drawingContext)
			{
				double width = Math.Max(0, AdornedElement.RenderSize.Width - 12);
				double y = Math.Max(0, Math.Min(_indicatorY, AdornedElement.RenderSize.Height));
				drawingContext.DrawLine(IndicatorPen, new Point(6, y), new Point(6 + width, y));
			}

			private static Pen CreateIndicatorPen()
			{
				var brush = new SolidColorBrush(Color.FromRgb(0x60, 0xA5, 0xFA));
				brush.Freeze();

				var pen = new Pen(brush, 3)
				{
					StartLineCap = PenLineCap.Triangle,
					EndLineCap = PenLineCap.Triangle
				};
				pen.Freeze();
				return pen;
			}
		}

		// ─── Helpers ────────────────────────────────────────────────────────

		/// <summary>Cập nhật cột STT cho toàn bộ danh sách.</summary>
		private void RefreshSequenceNumbers()
		{
			for (int i = 0; i < _pages.Count; i++)
				_pages[i].SequenceNumber = i + 1;
			AutoResizeSequenceColumn();
		}

		/// <summary>Tự động điều chỉnh chiều rộng các cột cho phù hợp với nội dung.</summary>
		private void AutoResizeSequenceColumn()
		{
			if (_pages.Count == 0) return;

			// Tính chiều rộng cần thiết dựa trên số chữ số lớn nhất (cột STT)
			int maxDigits = _pages.Count.ToString().Length;
			double needed = Math.Max(35, maxDigits * 8 + 10);

			if (lstPages.View is GridView gridView && gridView.Columns.Count > 0)
			{
				// Thay đổi chiều rộng cột #
				gridView.Columns[0].Width = needed;
			}

			UpdatePageColumnWidth();
		}

		private void UpdatePageColumnWidth()
		{
			if (lstPages.ActualWidth <= 0 ||
				lstPages.View is not GridView gridView ||
				gridView.Columns.Count < 4)
				return;

			double fixedColumnsWidth = 0;
			for (int i = 0; i < 3; i++)
				fixedColumnsWidth += gridView.Columns[i].ActualWidth;

			double reservedWidth = SystemParameters.VerticalScrollBarWidth + 8;
			double availableWidth = lstPages.ActualWidth - fixedColumnsWidth - reservedWidth;
			gridView.Columns[3].Width = Math.Max(90, availableWidth);
		}

		/// <summary>Tạo màu pastel theo golden angle để phân biệt nhóm PDF.</summary>
		private System.Drawing.Color GetNextColor()
		{
			double hue = (_colorIndex * 137.508) % 360.0;
			_colorIndex++;
			return HslToRgb(hue, 0.4, 0.85);
		}

		private System.Drawing.Color HslToRgb(double h, double s, double l)
		{
			double c = (1.0 - Math.Abs(2.0 * l - 1.0)) * s;
			double x = c * (1.0 - Math.Abs((h / 60.0) % 2.0 - 1.0));
			double m = l - c / 2.0;

			double r = 0, g = 0, b = 0;
			if (h < 60) { r = c; g = x; }
			else if (h < 120) { r = x; g = c; }
			else if (h < 180) { g = c; b = x; }
			else if (h < 240) { g = x; b = c; }
			else if (h < 300) { r = x; b = c; }
			else { r = c; b = x; }

			return System.Drawing.Color.FromArgb(
				(int)((r + m) * 255),
				(int)((g + m) * 255),
				(int)((b + m) * 255));
		}

		// ─── Window Lifecycle ───────────────────────────────────────────────

		protected override void OnClosing(CancelEventArgs e)
		{
			base.OnClosing(e);
			if (e.Cancel) return;

			if (_isBusy || specializedToolWorkspace.IsBusy)
			{
				e.Cancel = true;
				MessageBox.Show(
					"Please wait for the current PDF operation to finish.",
					"TPL PDF Editor",
					MessageBoxButton.OK,
					MessageBoxImage.Information);
				return;
			}

			if (!_forceClose && _isDirty && _pages.Count > 0)
			{
				MessageBoxResult result = MessageBox.Show(
					"Save changes before closing?",
					"TPL PDF Editor",
					MessageBoxButton.YesNoCancel,
					MessageBoxImage.Warning);
				if (result == MessageBoxResult.Cancel)
				{
					e.Cancel = true;
					return;
				}

				if (result == MessageBoxResult.Yes)
				{
					e.Cancel = true;
					Dispatcher.BeginInvoke(new Action(async () =>
					{
						if (await SaveDocumentAsync(saveAs: false))
						{
							_forceClose = true;
							Close();
						}
					}));
					return;
				}
			}

			_isClosing = true;
			ClearDropIndicator();
			_previewRequestId++;
			_loadCancellation.Cancel();
		}

		protected override void OnClosed(EventArgs e)
		{
			specializedToolWorkspace.Dispose();

			// Cleanup PDF viewer
			try
			{
				if (_hwndSource != null)
				{
					_hwndSource.RemoveHook(HwndHook);
					_hwndSource = null;
				}
				_pdfViewer.Renderer.HandleCreated -= PdfRenderer_HandleCreated;
				_pdfViewer.Renderer.ZoomChanged -= PdfRenderer_ZoomChanged;
				var oldDoc = _pdfViewer?.Document;
				if (_pdfViewer != null) _pdfViewer.Document = null;
				oldDoc?.Dispose();
				_currentPreviewStream?.Dispose();
				_currentPreviewStream = null;
			}
			catch (Exception ex)
			{
				System.Diagnostics.Debug.WriteLine($"[PdfEditor] Preview cleanup error: {ex.Message}");
			}

			DeleteOwnedSourceFiles();
			_colorIndex = 0;
			_groupIdCounter = 0;
			_pages.Clear();
			_instance = null;

			base.OnClosed(e);
		}

		[DllImport("user32.dll")]
		private static extern IntPtr MonitorFromWindow(IntPtr windowHandle, uint flags);

		[DllImport("user32.dll", CharSet = CharSet.Auto)]
		[return: MarshalAs(UnmanagedType.Bool)]
		private static extern bool GetMonitorInfo(IntPtr monitorHandle, ref MonitorInfo monitorInfo);

		[DllImport("uxtheme.dll", CharSet = CharSet.Unicode)]
		private static extern int SetWindowTheme(IntPtr windowHandle, string subAppName, string subIdList);

		[StructLayout(LayoutKind.Sequential)]
		private struct NativePoint
		{
			public int X;
			public int Y;
		}

		[StructLayout(LayoutKind.Sequential)]
		private struct MinMaxInfo
		{
			public NativePoint Reserved;
			public NativePoint MaxSize;
			public NativePoint MaxPosition;
			public NativePoint MinTrackSize;
			public NativePoint MaxTrackSize;
		}

		[StructLayout(LayoutKind.Sequential)]
		private struct NativeRectangle
		{
			public int Left;
			public int Top;
			public int Right;
			public int Bottom;
		}

		[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Auto)]
		private struct MonitorInfo
		{
			public int Size;
			public NativeRectangle MonitorArea;
			public NativeRectangle WorkArea;
			public uint Flags;
		}
	}

}

